// Valid Shatter baseline report (pass 24): validity checks, ascensions, per-run replay, Keep/Hollow King, horizons at 24/36/48/60/72h, totals; audited against a prior batch through the first ascension (or first Shatter).
// Usage: node tests/sim/baseline72.js --dir batch_out_p24 [--base batch_out_p22] [--profiles idle,light,casual] [--seedStart 31 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const D=String(args.dir||'batch_out_p24'),BASE=args.base?String(args.base):null,P=String(args.profiles||'idle,light,casual').split(','),S0=args.seedStart||31,N=args.seeds||10,H=[24,36,48,60,72];
const KEEP='Ashen Keep',FND='The Foundry';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0);
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'  '+D+(BASE?'  (audited against '+BASE+')':''));
  const V={hours:0,shOk:0,audit:0,legal:0,n:0},S={sh:[],asc:[],keepLv:[],keepLoss:[],keepFar:[],hk:0,hkW:0,hkSum:0,keepClear:0,fnd:0,zBest:{},zCur:{},def:[],train:[],gold:[],ore:[],run3zones:[],run3h:[],fight36:0,keepRuns:0};
  for(let s=S0;s<S0+N;s++){const r=rd(D,p,s);if(!r){console.log('seed '+s+': missing');continue;}V.n++;
    const sh=r.shatters||[],asc=r.ascensions||[],rz=r.runZones||{},rc=r.runClears||{},spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
    const hoursOk=r.simHours>=71.9;if(hoursOk)V.hours++;const shOk=sh.length<=3;if(shOk)V.shOk++;
    const cap=x=>Math.min(4,1+x.run);const illegal=asc.filter(a=>!(a.to===a.from+1&&a.from<cap(a)&&Math.abs(a.cost-Math.round(40*Math.pow(4,a.from)*Math.pow(1.14,a.lvl)))<=1&&a.oreBefore-a.oreAfter===a.cost));if(!illegal.length&&!(r.ascAnomalies||[]).length)V.legal++;
    let auditTxt='no baseline';if(BASE){const b=rd(BASE,p,s);if(b){const h0=Math.min(asc[0]?asc[0].h:1e9,sh[0]?sh[0].h:1e9);const ra=(r.hourly||[]).filter(g=>g.h<h0),rb=(b.hourly||[]).filter(g=>g.h<h0);let same=0;for(let i=0;i<Math.min(ra.length,rb.length);i++)if(JSON.stringify(ra[i])===JSON.stringify(rb[i]))same++;const shSame=(sh[0]?sh[0].h:null)===(b.shatters[0]?b.shatters[0].h:null)&&(sh[0]?sh[0].zone:null)===(b.shatters[0]?b.shatters[0].zone:null);const buysA=JSON.stringify((r.dustBuys||[]).filter(x=>x.h<h0)),buysB=JSON.stringify((b.dustBuys||[]).filter(x=>x.h<h0));const ok=same===Math.min(ra.length,rb.length)&&ra.length===rb.length&&shSame&&buysA===buysB;if(ok)V.audit++;auditTxt=(ok?'OK':'MISMATCH')+' (hourly '+same+'/'+ra.length+' before h'+f(h0,2)+', first Shatter '+(shSame?'same':'DIFFERS')+', dust buys '+(buysA===buysB?'same':'DIFFER')+')';}}
    console.log('\nseed '+s+'  hours '+f(r.simHours,2)+(hoursOk?'':' SHORT')+'  Shatters '+sh.length+(shOk?'':' OVER CAP')+'  ascensions '+asc.length+(illegal.length?' ILLEGAL '+illegal.length:'')+((r.ascAnomalies||[]).length?' anomalies '+(r.ascAnomalies||[]).length:'')+'  audit '+auditTxt);
    if(sh.length)(S.first=S.first||[]).push(sh[0].h);for(let i=0;i<sh.length;i++){const e=sh[i];const rk=String((e.run||0)+1),c=rc[rk]||{};const zs=Object.entries(c).sort((a,b)=>a[1]-b[1]);console.log('  Shatter '+(i+1)+' h'+e.h+' in '+e.zone+' fight '+e.prog+' Lv'+e.lv+' +'+e.gain+' dust (stalled '+e.stallH+'h)  -> run '+rk+': '+zs.length+' zones cleared'+(zs.length?', last '+zs[zs.length-1][0].split(' ')[0]+' @'+zs[zs.length-1][1]+'h':'')+(rz[rk]&&rz[rk][KEEP]?', Keep @'+rz[rk][KEEP].enterH+'h Lv'+rz[rk][KEEP].lvAtEntry:''));S.sh.push(e.h);}
    if(asc.length)console.log('  ascensions: '+asc.map(a=>'h'+a.h+' r'+a.run+' '+a.hero+'/'+a.slot+' '+a.from+'>'+a.to+' L'+a.lvl+' '+a.cost+'ore').join('; '));S.asc.push(asc.length);
    const ke=Object.keys(rz).filter(k=>rz[k][KEEP]).map(k=>({run:+k,...rz[k][KEEP]}));if(ke.length)S.keepRuns++;for(const e of ke){S.keepLv.push(e.lvAtEntry);console.log('  Keep entry run'+e.run+' @'+e.enterH+'h Lv'+e.lvAtEntry+' pw'+e.power+' ore'+e.ore+' gear['+e.gear+']');}
    const bz=(r.byZone||{})[KEEP]||{},zt=(r.zoneTime||{})[KEEP]||{sec:0};const enc=Math.round(zt.sec/spe),loss=bz.defeats||0,lp=enc?100*loss/enc:null;const far=Math.max(0,...(r.hourly||[]).filter(g=>g.zone===KEEP).map(g=>g.prog),...sh.filter(x=>x.zone===KEEP).map(x=>x.farMark||0),r.final.zone===KEEP?r.final.prog:0);if(enc){S.keepLoss.push(lp);S.keepFar.push(far);console.log('  Keep ordinary: enc '+enc+' L'+loss+' ('+f(lp,0)+'%) '+f(zt.sec/3600,1)+'h far '+far+' rewalk '+f((bz.rewalk||0)*spe/3600,2)+'h');}
    const hk=(r.bossFailRates||{})[KEEP];if(hk){S.fight36++;const L=hk.attemptLog;S.hk+=L.length;S.hkW+=L.filter(a=>a.win).length;S.hkSum+=L.filter(a=>a.summoned).length;console.log('  Hollow King '+L.filter(a=>a.win).length+'/'+L.length+': '+L.map(a=>(a.win?'W':'L')+f(a.dur,0)+'s '+Math.round(100*(a.win?a.partyHp:a.hpLeft))+'%'+(a.summoned?' summon':'')+' Lv'+a.lv+' r'+a.run+' bossLv'+a.bossLv+' atk'+a.bossAtk).join(' | ')+(hk.attemptsToClear?'  CLEARED after '+hk.attemptsToClear:''));}
    const kc=Object.keys(rc).filter(k=>rc[k][KEEP]!=null);if(kc.length){S.keepClear++;console.log('  KEEP CLEARED '+kc.map(k=>'run'+k+' @'+rc[k][KEEP]+'h').join(' '));}const fe=Object.keys(rz).filter(k=>rz[k][FND]);if(fe.length){S.fnd++;console.log('  FOUNDRY '+fe.map(k=>'run'+k+' @'+rz[k][FND].enterH+'h Lv'+rz[k][FND].lvAtEntry+' pw'+rz[k][FND].power).join(' '));}
    const at=h=>{let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}return [cur,best];};
    console.log('  zones cur/best '+H.map(h=>h+'h '+at(h).join('/')).join(', ')+' | defeats '+(r.final.defeats||0)+' | training '+f((r.autoTrain&&r.autoTrain.timeSec||0)/3600,1)+'h | gold earned '+Math.round((r.econPerHour.goldEarned||0)*r.simHours/1000)+'K spent '+Math.round((r.econPerHour.goldSpent||0)*r.simHours/1000)+'K | ore earned '+Math.round((r.econPerHour.oreEarned||0)*r.simHours)+' spent '+Math.round((r.econPerHour.oreSpent||0)*r.simHours)+' | dust earned '+sum(sh.map(x=>x.gain))+' left '+r.final.dust+' | final run '+(r.final.shatters||0)+' '+r.final.zone+' fight '+r.final.prog+' Lv'+r.final.partyLv);
    for(const h of H){(S.zCur[h]=S.zCur[h]||[]).push(at(h)[0]);(S.zBest[h]=S.zBest[h]||[]).push(at(h)[1]);}S.def.push(r.final.defeats||0);S.train.push((r.autoTrain&&r.autoTrain.timeSec||0)/3600);S.gold.push((r.econPerHour.goldEarned||0)*r.simHours/1e6);S.ore.push((r.econPerHour.oreEarned||0)*r.simHours);
    if(sh.length>=3){const c3=rc['3']||{};S.run3zones.push(Object.keys(c3).length);S.run3h.push(r.simHours-sh[2].h);}
  }
  console.log('\n-- '+p+' validity: 72h reached '+V.hours+'/'+V.n+', Shatter cap respected '+V.shOk+'/'+V.n+', pre-first-ascension/Shatter audit OK '+V.audit+'/'+V.n+', ascension legality OK '+V.legal+'/'+V.n);
  console.log('-- '+p+' summary: Shatters '+S.sh.length+' (first Shatter h med '+f(med(S.first||[]),1)+'); ascensions per run med '+med(S.asc)+' total '+sum(S.asc)+'; runs entering the Keep '+S.keepRuns+'/'+V.n+', entry Lv med '+f(med(S.keepLv),0)+'; Keep loss% med '+f(med(S.keepLoss),0)+', furthest fight med '+med(S.keepFar)+'; fight 36 reached '+S.fight36+' runs, Hollow King '+S.hkW+'/'+S.hk+' (summons '+S.hkSum+'); Keep clears '+S.keepClear+', Foundry '+S.fnd+'; run-3 replay: '+S.run3zones.length+' runs, zones cleared med '+med(S.run3zones)+' in '+f(med(S.run3h),1)+'h');
  console.log('   zones cur/best med '+H.map(h=>h+'h '+med(S.zCur[h])+'/'+med(S.zBest[h])).join(', ')+' | defeats med '+med(S.def)+' | training h med '+f(med(S.train),1)+' | gold earned med '+f(med(S.gold),2)+'M | ore earned med '+Math.round(med(S.ore)));
}
