// Paired late-boss candidate report, parametrized by zone (pass 29: Foundry Core). Audit through the first boss attempt (approximated by the first hour the zone's progress reaches the boss fight),
// proof that upstream boss rows are identical, attempts/wins by run and window, loss phases (opening / charge landed / after summon), damage shares, downstream (Endless), horizons, totals, outliers.
// Usage: node tests/sim/bosscmp.js --a batch_out_p28 --b batch_out_p29 --zone "The Foundry" --boss "The Foundry Core" [--upstream "Ashen Keep"] [--profiles idle,light,casual,engaged] [--seedStart 51 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const A=String(args.a||'batch_out_p28'),B=String(args.b||'batch_out_p29'),Z=String(args.zone||'The Foundry'),BOSS=String(args.boss||'The Foundry Core'),UP=String(args.upstream||'Ashen Keep'),P=String(args.profiles||'idle,light,casual,engaged').split(','),S0=args.seedStart||51,N=args.seeds||10,H=[24,48,72,96],END='The Endless Road';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0),mean=a=>{a=a.filter(v=>v!=null&&!isNaN(v));return a.length?sum(a)/a.length:null};
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const pair=(va,vb,d=1)=>{const dd=va.map((v,i)=>(vb[i]==null||v==null)?null:vb[i]-v).filter(x=>x!=null);return 'med '+f(med(va),d)+' -> '+f(med(vb),d)+(dd.length?' (paired med '+f(med(dd),d)+', +'+dd.filter(x=>x>0).length+' 0'+dd.filter(x=>x===0).length+' -'+dd.filter(x=>x<0).length+')':'');};
const phase=a=>a.summons&&a.summons[0]?'after summon':(a.chargeHits>0?'charge landed':'opening');
const shares=a=>{const t=a.taken||{};const tot=sum(Object.values(t))||1;const boss=t[BOSS]||0;return{boss:boss/tot,adds:(tot-boss)/tot};};
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],hr=r.hourly||[],spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
  o.simH=r.simHours;o.nsh=sh.length;
  const zi=Object.keys(rz).filter(k=>rz[k][Z]).map(k=>({run:+k,h:rz[k][Z].enterH,lv:rz[k][Z].lvAtEntry,pw:rz[k][Z].power}));o.zoneIn=zi.length?zi[0]:null;const zc=Object.keys(rc).filter(k=>rc[k][Z]!=null).map(k=>rc[k][Z]);o.zoneClr=zc.length?zc[0]:null;const zt=(r.zoneTime||{})[Z]||{sec:0};o.zoneH=zt.sec/3600;const bz=(r.byZone||{})[Z]||{};o.zoneEnc=Math.round(zt.sec/spe);o.zoneLoss=bz.defeats||0;o.zoneFar=Math.max(0,...hr.filter(g=>g.zone===Z).map(g=>g.prog),r.final.zone===Z?r.final.prog:0);
  o.firstBossHour=o.zoneIn?o.zoneIn.h:null;
  const b=(r.bossFailRates||{})[Z];const L=b?b.attemptLog.filter(a=>a.win!=null):[];o.att=L.length;o.w=L.filter(a=>a.win).length;o.auto=[L.filter(a=>a.window==='auto'&&a.win).length,L.filter(a=>a.window==='auto').length];o.act=[L.filter(a=>a.window!=='auto'&&a.win).length,L.filter(a=>a.window!=='auto').length];o.stall=b?b.stallH:null;o.firstTry=b?!!b.firstTryClear:null;o.atk=L[0]?L[0].bossAtk:null;o.lv=med(L.map(a=>a.lv));o.pw=med(L.map(a=>a.power));
  const losses=L.filter(a=>!a.win),wins=L.filter(a=>a.win);o.lossDur=med(losses.map(a=>a.dur));o.lossHp=med(losses.map(a=>a.hpLeft));o.lossDeaths=med(losses.map(a=>a.deaths));o.winSurv=med(wins.map(a=>a.survivors));o.winHp=med(wins.map(a=>a.partyHp));o.winDur=med(wins.map(a=>a.dur));o.chargeHits=mean(L.map(a=>a.chargeHits||0));o.chargeKills=mean(L.map(a=>a.chargeKills||0));
  const cd=[].concat(...L.map(a=>a.chargeDetail||[]));o.volleyN=cd.length;o.volleyPct=med(cd.map(d=>d.pct));o.volleyLethal=cd.length?cd.filter(d=>d.pct>=1).length/cd.length:null;o.volleyPctFront=med(cd.filter(d=>d.front).map(d=>d.pct));o.parried=sum(L.map(a=>a.parried||0));o.interrupted=sum(L.map(a=>a.interrupted||0));o.telegraphs=sum(L.map(a=>a.telegraphs||0));o.hitsPerAtt=mean(L.map(a=>a.bossHits||0));o.phases={opening:0,charge:0,summon:0};for(const a of losses){const ph=phase(a);if(ph==='opening')o.phases.opening++;else if(ph==='charge landed')o.phases.charge++;else o.phases.summon++;}const sh2=losses.filter(a=>a.taken).map(shares);o.shareBoss=mean(sh2.map(x=>x.boss));o.shareAdds=mean(sh2.map(x=>x.adds));
  const up=(r.bossFailRates||{})[UP];const zr=o.zoneIn?o.zoneIn.run:99;const UL=up?up.attemptLog.filter(a=>a.win!=null&&(a.run==null||a.run<=zr)):[];o.upAtt=UL.length;o.upW=UL.filter(a=>a.win).length;o.upStall=up?up.stallH:null;o.upAtk=UL[0]?UL[0].bossAtk:null;
  const AZ=args.auditZone?(r.bossFailRates||{})[String(args.auditZone)]:null;const AL=AZ?AZ.attemptLog.filter(a=>a.win!=null):[];const acd=[].concat(...AL.map(a=>a.chargeDetail||[]));o.auditHits=sum(AL.map(a=>a.chargeHits||0));o.auditKills=sum(AL.map(a=>a.chargeKills||0));o.auditPct=med(acd.map(d=>d.pct));o.auditAtk=AL[0]?AL[0].bossAtk:null;
  const ei=Object.keys(rz).filter(k=>rz[k][END]).map(k=>rz[k][END].enterH);o.endIn=ei.length?ei[0]:null;o.endH=((r.zoneTime||{})[END]||{sec:0}).sec/3600;o.endBest=r.endless&&r.endless.best||0;
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}o.zAt[h]=[cur,best];}
  o.def=r.final.defeats||0;o.train=(r.autoTrain&&r.autoTrain.timeSec||0)/3600;o.gold=(r.econPerHour.goldEarned||0)*r.simHours/1e6;o.ore=(r.econPerHour.oreEarned||0)*r.simHours;o.final=(r.final.shatters||0)+' '+r.final.zone+' f'+r.final.prog+' Lv'+r.final.partyLv;const l96=hr.filter(x=>x.h<=96).pop();o.lv96=l96?l96.lv:null;o.pw96=l96?l96.power:null;
  return o;}
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'   baseline '+A+' -> candidate '+B+'   boss: '+BOSS+' in '+Z);
  const MA=[],MB=[],V={h:0,cap:0,audit:0,up:0,n:0},outl=[];
  for(let s=S0;s<S0+N;s++){const a=rd(A,p,s),b=rd(B,p,s);if(!a||!b){console.log('seed '+s+': missing');continue;}const ma=m(a),mb=m(b);MA.push(ma);MB.push(mb);V.n++;if(mb.simH>=95.9)V.h++;if(mb.nsh<=3)V.cap++;
    const h0=ma.firstBossHour!=null?ma.firstBossHour:1e9;const ra=(a.hourly||[]).filter(g=>g.h<h0),rb=(b.hourly||[]).filter(g=>g.h<h0);let same=0;for(let i=0;i<Math.min(ra.length,rb.length);i++)if(JSON.stringify(ra[i])===JSON.stringify(rb[i]))same++;
    const upSame=ma.upAtt===mb.upAtt&&ma.upW===mb.upW&&ma.upStall===mb.upStall&&ma.upAtk===mb.upAtk;if(upSame)V.up++;const zoneInSame=JSON.stringify(ma.zoneIn)===JSON.stringify(mb.zoneIn);
    const ok=same===ra.length&&ra.length===rb.length&&upSame&&zoneInSame&&mb.atk!=null&&ma.atk!=null&&(args.sameAtk?mb.atk===ma.atk:mb.atk<ma.atk);if(ok)V.audit++;
    console.log('\nseed '+s+'  hours '+f(mb.simH,2)+'  Shatters '+ma.nsh+'->'+mb.nsh+'  audit through zone entry (h'+f(ma.firstBossHour,0)+'): hourly '+same+'/'+ra.length+', '+UP+' rows through that run '+(upSame?'identical':'DIFFER')+' ('+ma.upW+'/'+ma.upAtt+' stall '+f(ma.upStall,1)+'h atk '+ma.upAtk+'), zone entry '+(zoneInSame?'same':'DIFFER')+', boss ATK '+ma.atk+'->'+mb.atk+' -> '+(ok?'OK':'MISMATCH'));
    console.log('  '+BOSS+': attempts '+ma.att+'->'+mb.att+' wins '+ma.w+'->'+mb.w+' [auto '+ma.auto.join('/')+'->'+mb.auto.join('/')+', active '+ma.act.join('/')+'->'+mb.act.join('/')+'] stall '+f(ma.stall,1)+'->'+f(mb.stall,1)+'h'+(mb.firstTry?' FIRST-TRY':'')+' | entry @'+(ma.zoneIn?ma.zoneIn.h+'h Lv'+ma.zoneIn.lv+' pw'+Math.round(ma.zoneIn.pw/1000)+'K':'-')+' | at boss Lv '+f(ma.lv,0)+'->'+f(mb.lv,0)+' | loss dur '+f(ma.lossDur,0)+'->'+f(mb.lossDur,0)+'s HP left '+f(100*(ma.lossHp||0),0)+'->'+f(100*(mb.lossHp||0),0)+'% deaths '+ma.lossDeaths+'->'+mb.lossDeaths+' | charge hits/kills per att '+f(ma.chargeHits,2)+'/'+f(ma.chargeKills,2)+' -> '+f(mb.chargeHits,2)+'/'+f(mb.chargeKills,2)+' | win surv '+ma.winSurv+'->'+mb.winSurv+' HP '+f(100*(ma.winHp||0),0)+'->'+f(100*(mb.winHp||0),0)+'%');
    console.log('  volley: telegraphs '+ma.telegraphs+'->'+mb.telegraphs+' hits '+f(ma.chargeHits*ma.att,0)+'->'+f(mb.chargeHits*mb.att,0)+' kills '+f(ma.chargeKills*ma.att,0)+'->'+f(mb.chargeKills*mb.att,0)+' parried '+ma.parried+'->'+mb.parried+' interrupted '+ma.interrupted+'->'+mb.interrupted+' | volley dmg % of target max HP med '+(ma.volleyPct!=null?f(100*ma.volleyPct,0)+'%':'n/a')+' -> '+(mb.volleyPct!=null?f(100*mb.volleyPct,0)+'%':'n/a')+' (front '+(mb.volleyPctFront!=null?f(100*mb.volleyPctFront,0)+'%':'n/a')+'; hits >=100% '+(mb.volleyLethal!=null?f(100*mb.volleyLethal,0)+'%':'n/a')+' of '+mb.volleyN+') | ordinary boss hits per attempt '+f(ma.hitsPerAtt,1)+'->'+f(mb.hitsPerAtt,1)+(args.auditZone?' | audit '+args.auditZone+' volley: kills/hit '+f(ma.auditHits?ma.auditKills/ma.auditHits:null,2)+'->'+f(mb.auditHits?mb.auditKills/mb.auditHits:null,2)+' dmg% med '+(mb.auditPct!=null?f(100*mb.auditPct,0)+'%':'n/a')+' atk '+ma.auditAtk+'->'+mb.auditAtk:''));
    console.log('  phases opening/charge/summon '+ma.phases.opening+'/'+ma.phases.charge+'/'+ma.phases.summon+' -> '+mb.phases.opening+'/'+mb.phases.charge+'/'+mb.phases.summon+' | damage share boss '+f(100*(ma.shareBoss||0),0)+'% -> '+f(100*(mb.shareBoss||0),0)+'% adds '+f(100*(ma.shareAdds||0),0)+'% -> '+f(100*(mb.shareAdds||0),0)+'% | zone ordinary enc '+ma.zoneEnc+' L'+ma.zoneLoss+' far '+ma.zoneFar+' -> enc '+mb.zoneEnc+' L'+mb.zoneLoss+' far '+mb.zoneFar+' | time in zone '+f(ma.zoneH,1)+'->'+f(mb.zoneH,1)+'h | cleared '+(ma.zoneClr!=null?'@'+ma.zoneClr:'-')+'->'+(mb.zoneClr!=null?'@'+mb.zoneClr:'-')+' | Endless '+(ma.endIn!=null?'@'+ma.endIn+' ('+f(ma.endH,1)+'h, wave '+ma.endBest+')':'-')+' -> '+(mb.endIn!=null?'@'+mb.endIn+' ('+f(mb.endH,1)+'h, wave '+mb.endBest+')':'-'));
    console.log('  zones cur/best '+H.map(h=>h+'h '+ma.zAt[h].join('/')+'->'+mb.zAt[h].join('/')).join(', ')+' | defeats '+ma.def+'->'+mb.def+' | training '+f(ma.train,1)+'->'+f(mb.train,1)+'h | Lv@96h '+ma.lv96+'->'+mb.lv96+' pw '+Math.round((ma.pw96||0)/1000)+'K->'+Math.round((mb.pw96||0)/1000)+'K | gold '+f(ma.gold,1)+'->'+f(mb.gold,1)+'M ore '+Math.round(ma.ore/1000)+'K->'+Math.round(mb.ore/1000)+'K | final '+ma.final+' -> '+mb.final);
    if(mb.firstTry||(ma.endIn==null&&mb.endIn!=null)||(ma.gold&&mb.gold>1.5*ma.gold))outl.push('seed '+s+': '+(mb.firstTry?'first-try clear; ':'')+(ma.endIn==null&&mb.endIn!=null?'Endless newly reached @'+mb.endIn+'; ':'')+(ma.gold&&mb.gold>1.5*ma.gold?'gold x'+f(mb.gold/ma.gold,1):''));}
  console.log('\n-- '+p+' validity: 96h '+V.h+'/'+V.n+', Shatter cap '+V.cap+'/'+V.n+', '+UP+' rows identical '+V.up+'/'+V.n+', audit through zone entry OK '+V.audit+'/'+V.n);
  const agg=(M,k)=>M.reduce((a,x)=>[a[0]+x[k][0],a[1]+x[k][1]],[0,0]);const ph=(M,k)=>sum(M.map(x=>x.phases[k]));
  console.log('-- '+p+' '+BOSS+': reached '+MA.filter(x=>x.att).length+'->'+MB.filter(x=>x.att).length+' runs, cleared '+MA.filter(x=>x.zoneClr!=null).length+'->'+MB.filter(x=>x.zoneClr!=null).length+' | attempts '+pair(MA.map(x=>x.att),MB.map(x=>x.att),0)+' | Auto-Cast wins/att '+agg(MA,'auto').join('/')+' -> '+agg(MB,'auto').join('/')+' ('+f(100*agg(MB,'auto')[0]/Math.max(1,agg(MB,'auto')[1]),1)+'%) | active wins/att '+agg(MA,'act').join('/')+' -> '+agg(MB,'act').join('/')+' ('+f(100*agg(MB,'act')[0]/Math.max(1,agg(MB,'act')[1]),0)+'%) | stall h (cleared runs) '+pair(MA.map(x=>x.zoneClr!=null?x.stall:null),MB.map(x=>x.zoneClr!=null?x.stall:null),1)+' | first-try '+MA.filter(x=>x.firstTry).length+'->'+MB.filter(x=>x.firstTry).length+' | loss dur '+pair(MA.map(x=>x.lossDur),MB.map(x=>x.lossDur),0)+' | HP left% '+pair(MA.map(x=>100*(x.lossHp||0)),MB.map(x=>100*(x.lossHp||0)),0));
  console.log('   phases opening/charge/summon '+ph(MA,'opening')+'/'+ph(MA,'charge')+'/'+ph(MA,'summon')+' -> '+ph(MB,'opening')+'/'+ph(MB,'charge')+'/'+ph(MB,'summon')+' | boss damage share '+f(100*mean(MA.map(x=>x.shareBoss)),0)+'% -> '+f(100*mean(MB.map(x=>x.shareBoss)),0)+'% | charge hits/kills per attempt '+f(mean(MA.map(x=>x.chargeHits)),2)+'/'+f(mean(MA.map(x=>x.chargeKills)),2)+' -> '+f(mean(MB.map(x=>x.chargeHits)),2)+'/'+f(mean(MB.map(x=>x.chargeKills)),2)+' | zone entry h '+pair(MA.map(x=>x.zoneIn&&x.zoneIn.h),MB.map(x=>x.zoneIn&&x.zoneIn.h),1)+' | zone clear h '+pair(MA.map(x=>x.zoneClr),MB.map(x=>x.zoneClr),1)+' | time in zone h '+pair(MA.map(x=>x.zoneH),MB.map(x=>x.zoneH),1)+' | ordinary loss% '+pair(MA.map(x=>x.zoneEnc?100*x.zoneLoss/x.zoneEnc:null),MB.map(x=>x.zoneEnc?100*x.zoneLoss/x.zoneEnc:null),0));
  console.log('-- '+p+' volley: hits per attempt '+f(mean(MA.map(x=>x.chargeHits)),2)+' -> '+f(mean(MB.map(x=>x.chargeHits)),2)+' | kills per hit '+f(sum(MA.map(x=>x.chargeKills*x.att))/Math.max(1,sum(MA.map(x=>x.chargeHits*x.att))),2)+' -> '+f(sum(MB.map(x=>x.chargeKills*x.att))/Math.max(1,sum(MB.map(x=>x.chargeHits*x.att))),2)+' | parried '+sum(MA.map(x=>x.parried))+' -> '+sum(MB.map(x=>x.parried))+' of '+sum(MA.map(x=>x.telegraphs))+' -> '+sum(MB.map(x=>x.telegraphs))+' telegraphs | candidate volley dmg % of target max HP med '+f(100*(med(MB.map(x=>x.volleyPct))||0),0)+'% (front '+f(100*(med(MB.map(x=>x.volleyPctFront))||0),0)+'%), hits >=100%: '+f(100*(mean(MB.map(x=>x.volleyLethal))||0),0)+'%'+(args.auditZone?' | audit '+args.auditZone+': kills/hit '+f(sum(MA.map(x=>x.auditKills))/Math.max(1,sum(MA.map(x=>x.auditHits))),2)+' -> '+f(sum(MB.map(x=>x.auditKills))/Math.max(1,sum(MB.map(x=>x.auditHits))),2)+', candidate volley dmg% med '+f(100*(med(MB.map(x=>x.auditPct))||0),0)+'%':''));
  console.log('-- '+p+' downstream: Endless reached '+MA.filter(x=>x.endIn!=null).length+'->'+MB.filter(x=>x.endIn!=null).length+' (entry h '+pair(MA.map(x=>x.endIn),MB.map(x=>x.endIn),1)+', hours '+pair(MA.map(x=>x.endH),MB.map(x=>x.endH),1)+', best wave '+pair(MA.map(x=>x.endBest||null),MB.map(x=>x.endBest||null),0)+') | horizons cur/best med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][0]))+'/'+med(MA.map(x=>x.zAt[h][1]))+'->'+med(MB.map(x=>x.zAt[h][0]))+'/'+med(MB.map(x=>x.zAt[h][1]))).join(', ')+' | defeats '+pair(MA.map(x=>x.def),MB.map(x=>x.def),0)+' | training h '+pair(MA.map(x=>x.train),MB.map(x=>x.train),1)+' | Lv@96h '+pair(MA.map(x=>x.lv96),MB.map(x=>x.lv96),0)+' | gold M '+pair(MA.map(x=>x.gold),MB.map(x=>x.gold),1)+' | ore '+pair(MA.map(x=>x.ore),MB.map(x=>x.ore),0));
  console.log('-- '+p+' outliers: '+(outl.length?outl.join(' || '):'none'));
}
