// Headless balance simulator: a bot plays a fresh account through Shatters and reports timings.
// Usage: node tests/sim/bot.js [--hours 48] [--shatters 3] [--seed 1] [--dt 0.1] [--json out.json] [--quiet] [--stallRule far|clear] [--stallHours 3] [--stopAtShatters N]
// --shatters N caps how many Shatters the bot may perform; the run continues to --hours afterwards. --stopAtShatters N ends the run at the Nth Shatter (the pre-pass-24 behaviour of --shatters).
// Shatter rule: once the game allows it and the projected gain is >= 15, the bot Shatters when stalled for --stallHours: 'clear' = no zone clear; 'far' (default) = no zone clear and no new furthest-fight mark in the current zone.
//        node tests/sim/bot.js --endless 300    (start from a strong late save and run the Endless Road)
'use strict';
const {load}=require('./headless.js');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2);const n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const HOURS=args.hours||24,SHATTERS=args.shatters||0,DT=args.dt||(1/60),QUIET=!!args.quiet,SEED=args.seed||1;
const FPS=Math.round(1/DT);if(!(Math.abs(1/FPS-DT)<1e-12))throw new Error('--dt must be 1/N for an integer N (frame-counted time): got '+DT); /* simulated seconds = frames/FPS, the game clock = start + frames*1000/FPS: exact at whole seconds, no running float sum */
// player activity: taps per second on enemies while in battle (0 = idle player), abilities and surge always used when active
// activeMin = minutes of manual play per simulated hour; the rest of the hour runs on Auto-Cast with no taps or Surge
const PROFILES={idle:{activeMin:0,taps:0,boost:false},idleboost:{activeMin:0,taps:0,boost:true},light:{activeMin:5,taps:1,boost:true},casual:{activeMin:10,taps:1.5,boost:true},engaged:{activeMin:15,taps:2,boost:true},stress:{activeMin:60,taps:2,boost:true},active:{activeMin:60,taps:1,boost:true}};
// boost:true = the profile re-buys the production four-hour Auto-Cast boost whenever it lapses (outside its active minutes); boost:false = never has Auto-Cast
const STALL_RULE=String(args.stallRule||'far');const RETREAT_AFTER=args.noRetreat?0:(args.retreatAfter==null?0:Number(args.retreatAfter)),TRAIN_MODE=String(args.trainUntil||'level'),RETREAT_ON=String(args.retreatOn||'boss');
// real-player model (2026-09-16, all opt-in so the default harness stays frame-identical): --schedule "2:2,2:8,2:8" = blocks of play hours : offline hours, cycling; the offline block is skipped, not simulated, and the production offline report pays it out on return;
// --double claims the ad double on every offline report; --boosts uses the daily time warp and daily chest whenever they are ready during active minutes; --drills runs the Training Drill on every open bracket once per play session during active minutes; --clericBack keeps the Cleric last in the party (the front hero draws the hits)
const SCHEDULE=(()=>{if(!args.schedule)return null;const bl=String(args.schedule).split(',').map(x=>{const [p,o]=x.split(':').map(Number);return{play:p,off:o||0};}).filter(x=>x.play>0);return bl.length?bl:null;})();const DRILLS=!!args.drills,DOUBLE=!!args.double,BOOSTS=!!args.boosts,CLERIC_BACK=!!args.clericBack;
let curTick=-1; // simulated second of the current tick (set in the main loop; -1 before it starts)
const PROFILE=args.idle?'idle':(args.profile||'casual');const P=Object.assign({},PROFILES[PROFILE]||PROFILES.casual);if(args.taps!=null)P.taps=Number(args.taps);if(args.activeMin!=null)P.activeMin=Number(args.activeMin);if(args.boost!=null)P.boost=!!Number(args.boost);const TAPS=P.taps,ACTIVE=true,BOOST_MS=4*3600*1000,SPEED=Number(args.speed||1),FRAME_CAP=0.05; // default step 1/60 (a phone's frame); production's emergency cap is 0.05; the bot refuses a step above the cap unless --allowCoarseDt // --speed N: the game's speed toggle; N updates per real tick, so hours, taps, active minutes and boost timers stay in real time and taps per game second fall by N

if(![1,2,4].includes(SPEED))throw new Error('--speed must be 1, 2 or 4 (the production toggle states)');const SPEED4_BUYS=args.speed4Buys==null?Infinity:Number(args.speed4Buys); /* --speed 4: the bot buys the production two-hour 4x boost (buySpeed4) and rebuys it whenever it lapses, up to --speed4Buys purchases (default unlimited: the boost is held for the whole session); after the last purchase expires the road runs at 2x, as in the game */
// provenance: the exact source this run executed (commit, and content hashes of the game and the harness)
const PROVENANCE=(()=>{const crypto=require('crypto'),cp=require('child_process');const h=f=>crypto.createHash('sha256').update(require('fs').readFileSync(require('path').join(__dirname,f))).digest('hex').slice(0,16);let commit='unknown';try{commit=cp.execSync('git rev-parse HEAD',{cwd:__dirname,stdio:['ignore','pipe','ignore']}).toString().trim();}catch(e){}let dirty=[];try{dirty=cp.execSync('git status --porcelain -- source/game.js build/assets.json tests/sim/bot.js tests/sim/headless.js',{cwd:__dirname,stdio:['ignore','pipe','ignore']}).toString().trim().split('\n').filter(Boolean);}catch(e){dirty=['unknown'];}return{dirty,commit,gameHash:h('../../source/game.js'),harnessHash:h('bot.js')+':'+h('headless.js')};})();
// seeded RNG so runs are reproducible
let seed=SEED>>>0;function srand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
Math.random=srand;

const replace=[];if(args.bossHp!=null||args.bossAtk!=null){const z=args.bossZone==null?1:Number(args.bossZone);const cur={0:'0:{hp:0.75,atk:0.80}',1:'1:{hp:0.75,atk:0.82}'}[z];if(!cur)throw new Error('no override for zone '+z);const m=cur.match(/hp:([\d.]+),atk:([\d.]+)/);const hp=args.bossHp!=null?args.bossHp:Number(m[1]),atk=args.bossAtk!=null?args.bossAtk:Number(m[2]);replace.push([cur,z+':{hp:'+hp+',atk:'+atk+'}']);}
if(args.replace){for(const r of String(args.replace).split('||')){const [f,t]=r.split('=>');replace.push([f,t]);}}
if(args.replaceFile){for(const [f,t] of JSON.parse(require('fs').readFileSync(String(args.replaceFile),'utf8')))replace.push([f,t]);}  // JSON array of [from,to] pairs; use when the source contains '||' or '=>'
if(replace.length){const crypto=require('crypto'),fs=require('fs'),path=require('path');let src=fs.readFileSync(path.join(__dirname,'../../source/game.js'),'utf8');for(const [a,c] of replace)src=src.replace(a,c);PROVENANCE.gameHash=crypto.createHash('sha256').update(src).digest('hex').slice(0,16);PROVENANCE.replaced=replace.map(r=>r[0].slice(0,60));} /* the hash attests the source that ran, after every --replace */
const S=load({startMs:1700000000000,replace,seed:SEED});
const M={hours:0,events:[],taps:0,speedBuys:0,speedBoosts:[],speedCur:null,gameSec:0,recruits:{},talents:{},promotions:{},zones:{},zoneRec:{},firsts:{},shatters:[],boss:{},drops:{},gold:[],econ:{goldEarned:0,goldSpent:0,oreEarned:0,oreSpent:0},gearUps:0,dmgActive:{basic:0,ability:0,tap:0,surge:0},dmgAuto:{basic:0,ability:0,tap:0,surge:0},activeSec:0,delve:{best:0,runs:0,deaths:0},endless:{best:0,milestones:0},stuck:[]};
function ev(kind,text){M.events.push({h:+M.hours.toFixed(2),kind,text});if(!QUIET)console.log(M.hours.toFixed(2).padStart(7)+'h  '+kind.padEnd(9)+' '+text);}

S.ready.then(main).catch(e=>{console.error(e);process.exit(1);});

function main(){
  const G=S.G,Z=S.ZONES;
  const origMakeItem=S.makeItem;
  // count every drop by zone and rank
  const bag=G.pack;let lastPack=bag.length;
  G.title=false;G.tut=null;G.autoSalvage=0;G.mult='max';G.speed=SPEED===4?2:SPEED;G.speedUntil=0; /* the production toggle state; at --speed 4 the boost itself is bought below */
  if(args.endless){const lv=args.lvl||120;G.campfireDone=true;G.wins=Math.max(G.wins||0,3);for(let i=0;i<Z.length-1;i++){G.cleared[i]=true;G.prog[i]=Z[i].fights;}for(const def of S.HEROES){if(!G.roster.find(h=>h.id===def.id||h.name===def.name)){S.addHero(def,lv);}}for(const h of G.roster){h.lvl=lv;h.abLvl=args.rank||40;h.tier=3;h.tierMax=3;h.talents=h.talents||{};for(const t of S.TALENTS[h.cls])h.talents[t.id]=true;for(const slot of ['weapon','cape','charm']){const it=S.makeItem(Z.length-2,4);it.slot=slot;if(slot==='weapon')it.kind=S.CLASSES[h.cls].weapon;it.lvl=args.gear||60;h.eq[slot]=it;}S.refreshStats(h);h.hp=h.maxhp;}G.tree.hp=args.tree||60;G.tree.atk=args.tree||60;G.tree.def=Math.min(30,args.tree||60);G.tree.abil=30;G.reforges=args.reforged||3;G.endlessSeen=true;G.gold=1e9;G.ore=1e7;G.dust=500;travelTo(Z.length-1);ev('endless','start: party Lv '+avgLv()+', '+G.roster.length+' heroes, rank '+G.roster[0].abLvl+', gear +'+(args.gear||60));}
  let simSec=0,rosterChecked=-1,rosterRun=-1,nextAct=0,nextHour=1,lastZone=-1,zoneEnter=0,zoneDefeats=0,bossWas=false,lastLosses=0,lastRoster=G.roster.length,lastCleared=0,lastReforges=G.reforges||0;
  let farMark={};
  let retreatUntil=0,farmTarget=0,farmFights=0,trainingFor=0,tapAcc=0,lastProgressH=0,lastGold=G.gold,lastOre=G.ore,surgeReadyAt=0,wasActive=null,dmgMark={},bossStart=0,bossHpMax=0,bossZoneName='',prevBossFight=false;
  let offlineSec=0,blockIdx=0,blockStart=0,blockEnd=SCHEDULE?SCHEDULE[0].play*3600:Infinity,drillQueue=[],drillTapAcc=0,drillFirstCycle={};M.schedule=SCHEDULE;M.offline=[];M.drills={runs:0,paid:0,gold:0,ore:0,dust:0,tiers:{},first:{zone:{claims:0,gold:0,dust:0},endless:{claims:0,gold:0,dust:0}},repeat:{zone:{claims:0,gold:0,dust:0},endless:{claims:0,gold:0,dust:0}}};M.drillLog=[];let drillAttempts={},drillCycle=-1;M.boosts={warps:0,chests:0,doubles:0};
  const t0=Date.now();drillQueue=DRILLS?S.drillBrackets().slice():[]; /* the first session drills too */
  const target=HOURS*3600;S.clock.setFps(FPS);const frame0=S.clock.frames();
  while(simSec<target){
    if(SCHEDULE&&simSec>=blockEnd){const blk=SCHEDULE[blockIdx%SCHEDULE.length];goOffline(blk.off);blockIdx++;blockStart=simSec;blockEnd=simSec+SCHEDULE[blockIdx%SCHEDULE.length].play*3600;if(simSec>=target)break;continue;} /* end of a play block: the offline hours pass in one jump, then the next play block begins */
    S.clock.frame();simSec=(S.clock.frames()-frame0)/FPS+offlineSec;curTick=simSec;S.setRT(simSec);M.hours=simSec/3600; /* frame-counted time: simulated seconds, the game clock and RT all derive from the same integer frame count; offline jumps add whole seconds on top */
    G.title=false;if(G.tut!=null)G.tut=null;
    {const clk0=S.clock.get();if(M.speedCur&&!(G.speedUntil>clk0)){M.speedCur.realSec=+(simSec-M.speedCur.at).toFixed(3);M.speedCur.gameSec=+M.speedCur.gameSec.toFixed(3);M.speedCur=null;}if(SPEED===4&&!(G.speedUntil>clk0)&&M.speedBuys<SPEED4_BUYS){S.buySpeed4();M.speedBuys++;M.speedCur={h:+M.hours.toFixed(3),at:+simSec.toFixed(3),until:G.speedUntil,realSec:null,gameSec:0};M.speedBoosts.push(M.speedCur);}}
    const n=S.speedNow(); /* production speed every frame: 1, 2, or 4 while the boost runs and 2 after it lapses */
    {const want=SPEED<4?SPEED:(G.speedUntil>S.clock.get()?4:2);if(n!==want||(SPEED<4&&G.speedUntil)){ev('ERROR','assert: game speed '+n+' but expected '+want+(SPEED<4&&G.speedUntil?' (a boost exists at --speed '+SPEED+')':''));M.assertFail=['game speed '+n+' != '+want];break;}}
    if(M.speedCur)M.speedCur.gameSec+=n*DT;M.gameSec+=n*DT;
    try{for(let k=0;k<n;k++)S.update(DT,k===0);}catch(e){ev('ERROR','update: '+e.message+' @ '+(e.stack||'').split('\n')[1]);break;}
    {const zn=Z[G.zone]&&Z[G.zone].name;if(zn){M.zoneTime=M.zoneTime||{};const zt=M.zoneTime[zn]=M.zoneTime[zn]||{sec:0,trainSec:0};if(G.train&&G.train.active)zt.trainSec+=DT;else zt.sec+=DT;}}
    if(args.noAutoTrain)G.autoTrainOff=true;if(G.parts.length)G.parts.length=0;if(G.floats.length)G.floats.length=0;
    if(G.roster.length>lastRoster){for(let i=lastRoster;i<G.roster.length;i++){const h=G.roster[i];h.joinSec=curTick;M.recruits[h.name]=+M.hours.toFixed(2);ev('recruit',h.name+' the '+S.CLASSES[h.cls].name);}lastRoster=G.roster.length;}
    {let bad=null;const push=m=>{(bad||(bad=[])).push(m);};const clk=S.clock.get();if(DT>FRAME_CAP+1e-9&&!args.allowCoarseDt)push('dt '+DT+' coarser than the production frame cap '+FRAME_CAP);if(S.gameNow&&S.gameNow()!==clk)push('game clock '+S.gameNow()+' != sim clock '+clk);if(M.postFail)push(M.postFail);if(M.postChecks){for(const pc of M.postChecks){if(pc.done)continue;const h=G.roster.find(x=>x.id===pc.id);if(!h||!G.castle.garrison.includes(pc.id)){pc.done=true;continue;}const el=simSec-pc.at,left=S.postLeft(h);if(el>=3600+DT&&left>0)push('recall of '+pc.name+' still '+left.toFixed(1)+'s away one simulated hour after posting');if(el>=3600+DT)pc.done=true;else if(Math.abs((3600-el)-left)>DT*2+1)push('post timer for '+pc.name+' drifts: '+left.toFixed(1)+'s left after '+el.toFixed(1)+'s');}}if(S.zoneUnlocked&&!G.delve&&!G.hordeFight&&!S.zoneUnlocked(G.zone))push('illegal zone '+Z[G.zone].name+' with '+(G.reforges||0)+' Shatters');if(G.roster.length!==rosterChecked||(G.reforges||0)!==rosterRun){rosterChecked=G.roster.length;rosterRun=G.reforges||0;const names=G.roster.map(h=>h.name);if(new Set(names).size!==names.length)push('duplicate hero: '+names.join(','));}for(let i=0;i<G.active.length;i++)if(!G.roster.includes(G.active[i])){push('active hero not in roster');break;}if(!P.boost&&(G.autoCast||G.autoUntil>clk))push('Auto-Cast on for an unboosted profile');if(G.autoUntil>clk+BOOST_MS+1000)push('boost longer than one 4h purchase');if(M.bossDirty){M.bossDirty=false;for(const k in M.boss){const al=M.boss[k].attemptLog||[],last=al[al.length-1];if(last&&!(Number.isFinite(last.lv)&&Number.isFinite(last.power)&&(last.bossLv==null||Number.isFinite(last.bossLv))))push('bad boss telemetry at '+k);}}if(bad){ev('ERROR','assert: '+bad.join('; '));M.assertFail=bad;break;}} /* per-tick assertions; the roster and boss-telemetry checks run when their inputs change, everything else every tick */
    if(ACTIVE)play();
    if(DRILLS)drillStep();
    // observations every tick
    {const dg=G.gold-lastGold,dO=G.ore-lastOre;if(dg>0)M.econ.goldEarned+=dg;else M.econ.goldSpent-=dg;if(dO>0)M.econ.oreEarned+=dO;else M.econ.oreSpent-=dO;lastGold=G.gold;lastOre=G.ore;}
    const bossRise=G.bossFight&&!prevBossFight;prevBossFight=G.bossFight;
    if(bossRise&&!bossWas){bossWas=true;const b=(M.boss[Z[G.zone].name]=M.boss[Z[G.zone].name]||{attempts:0,fails:0,streak:0,maxStreak:0,firstTry:0,losses:[],wins:[]});b.attempts++;(b.attemptLog=b.attemptLog||[]).push({n:b.attempts,window:inWindow()?'active':'auto',hp:+(G.active.reduce((q,h)=>q+Math.max(0,h.hp),0)/Math.max(1,G.active.reduce((q,h)=>q+h.maxhp,0))).toFixed(2),charge:Math.round(G.active.reduce((q,h)=>q+(h.charge||0),0)/Math.max(1,G.active.length)),surge:Math.round(G.surge||0),win:null,bossAtk:(()=>{const e=G.enemies.find(x=>x.boss);return e?e.atk:null;})(),bossLv:(()=>{const e=G.enemies.find(x=>x.boss);return e?e.lvl:null;})(),lv:+avgLv().toFixed(1),power:S.partyPower()});M.bossDirty=true;if(b.lossAt){b.retryStall=(b.retryStall||0)+(simSec-b.lossAt);b.lossAt=0;}{const st=S.partyState();const at=(G.stats&&G.stats.autoTrain)||{log:[],returns:0};const last=at.log.length?at.log[at.log.length-1]:null;if(last&&last.afterReturn&&!last.nextBoss)last.nextBoss=Object.assign({boss:Z[G.zone].name},st);if(!b.firstTry){b.arrival=Object.assign({},st,{trainingsBefore:at.triggers||0,returnsBefore:at.returns||0,fightsSinceReturn:(G.train&&G.train.returnFights!=null)?G.train.returnFights:null,minSinceReturn:(G.train&&G.train.returnedAt)?+((S.clock.get()-G.train.returnedAt)/60000).toFixed(1):null,via:(G.train&&G.train.returnFights!=null&&G.train.returnFights<=10)?'training-return':'progression',power:S.partyPower()});}}if(!b.firstTry){b.firstTry=simSec;b.lvFirst=avgLv();b.winsAtFirst=G.wins;b.upsAtFirst=M.gearUps;if(args.snapshots){try{const fs=require('fs'),path=require('path');fs.mkdirSync(String(args.snapshots),{recursive:true});const key=(function(n){const w=n.toLowerCase().split(' ');return Z.filter(z=>z.name.toLowerCase().split(' ')[0]===w[0]).length>1?w.slice(0,2).join('_'):w[0];})(Z[G.zone].name)+'_'+PROFILE+'_'+SEED+'.json';fs.writeFileSync(path.join(String(args.snapshots),key),JSON.stringify({zone:G.zone,zoneName:Z[G.zone].name,profile:PROFILE,seed:SEED,hours:+M.hours.toFixed(2),lv:avgLv(),hp:Object.fromEntries(G.active.map(h=>[h.id,+(h.hp/h.maxhp).toFixed(3)])),charge:Object.fromEntries(G.active.map(h=>[h.id,Math.round(h.charge||0)])),save:S.serialize()}));}catch(e){}}}bossStart=simSec;bossHpMax=0;bossZoneName=Z[G.zone].name;if(args.replayBoss&&Z[G.zone].name.toLowerCase().startsWith(String(args.replayBoss).toLowerCase())&&b.attempts===1){replayFight(Number(args.replayN)||30);}if(args.verbose)ev('boss','#'+b.attempts+' '+Z[G.zone].name+' window='+(inWindow()?'active':'auto')+' autoCast='+G.autoCast+' partyHP='+Math.round(100*G.active.reduce((q,h)=>q+Math.max(0,h.hp),0)/Math.max(1,G.active.reduce((q,h)=>q+h.maxhp,0)))+'% Lv='+avgLv()+' mode='+G.mode+' heroes='+G.active.map(h=>h.id+':'+h.hp+'/'+h.maxhp+' a'+h.atk+' d'+h.def+' c'+Math.round(h.charge))+' surge='+Math.round(G.surge||0)+' tree='+JSON.stringify(G.tree)+' boss='+G.enemies.map(e=>e.name+':'+e.maxhp+'/a'+e.atk+'/d'+e.def+'/L'+e.lvl));}
    if(bossWas&&G.mode==='battle'&&!bossHpMax){const e=G.enemies.find(x=>x.boss)||G.enemies[0];if(e)bossHpMax=e.maxhp;}
    if(bossWas&&G.mode==='victory'){bossWas=false;const b=M.boss[bossZoneName];const alive=G.active.filter(h=>!h.dead);b.wins.push({dur:+(simSec-bossStart).toFixed(1),survivors:alive.length,partyHp:+(G.active.reduce((a,h)=>a+Math.max(0,h.hp),0)/Math.max(1,G.active.reduce((a,h)=>a+h.maxhp,0))).toFixed(2)});}
    else if(!G.bossFight&&bossWas&&G.mode!=='defeat'){bossWas=false;const b=M.boss[bossZoneName];if(b)b.attempts--;/* interrupted, not an attempt */}
    if(G.mode==='defeat'&&G.timer>2.5){if(bossWas){const b=M.boss[bossZoneName];if(args.verbose){const e=G.enemies.find(x=>x.boss)||G.enemies[0];ev('bossLOSS',bossZoneName+' after '+(simSec-bossStart).toFixed(0)+'s bossHP='+(e&&bossHpMax?Math.round(100*e.hp/bossHpMax):'?')+'% enemies='+G.enemies.filter(x=>!x.dead).map(x=>x.name).join('/'));}b.fails++;b.streak++;b.maxStreak=Math.max(b.maxStreak,b.streak);if(b.attemptLog&&b.attemptLog.length)b.attemptLog[b.attemptLog.length-1].win=false;const e=G.enemies.find(x=>x.boss)||G.enemies[0];b.losses.push({dur:+(simSec-bossStart).toFixed(1),hpLeft:e&&bossHpMax?+(e.hp/bossHpMax).toFixed(2):null,wipe:G.active.every(h=>h.dead)});if(b.attemptLog&&b.attemptLog.length){const L=b.attemptLog[b.attemptLog.length-1],fsx=G.fs||{};Object.assign(L,{dur:+(simSec-bossStart).toFixed(1),hpLeft:e&&bossHpMax?+(e.hp/bossHpMax).toFixed(2):null,summoned:!!(e&&e.mech&&e.mech.summon&&e.mech.summon[0]&&e.mech.summon[0].done),telegraphs:fsx.chargeTelegraphs||0,chargeHits:fsx.chargeHits||0,chargeKills:fsx.chargeKills||0,parried:fsx.chargeParried||0,interrupted:fsx.chargeInterrupted||0,bossHits:fsx.bossHits||0,raised:fsx.raised||0,run:G.reforges||0,chargeDetail:(fsx.chargeDetail||[]).map(d=>({pct:+(d.dmg/Math.max(1,d.maxhp)).toFixed(2),front:!!d.front,ranged:!!d.ranged})),taken:Object.fromEntries(Object.entries(fsx.taken||{}).map(([k,v])=>[k,Math.round(v)])),summons:(e&&e.mech&&e.mech.summon?e.mech.summon.map(x=>!!x.done):[]),deaths:G.active.filter(h=>h.dead).length,enemiesAlive:G.enemies.filter(x=>!x.dead).map(x=>x.name)});}b.combatStall=(b.combatStall||0)+(simSec-bossStart);b.lossAt=simSec;bossWas=false;}zoneDefeats++;}
    if(G.pack.length>lastPack){for(let i=lastPack;i<G.pack.length;i++){const it=G.pack[i];const k=Z[G.zone].name;(M.drops[k]=M.drops[k]||[0,0,0,0,0,0])[Math.min(5,it.rank||0)]++;const rn=['common','uncommon','rare','epic','legendary','mythic'][Math.min(5,it.rank||0)];if(M.firsts['first '+rn]==null)M.firsts['first '+rn]=+M.hours.toFixed(2);}}
    lastPack=G.pack.length;
    if(STALL_RULE==='far'){const fm=(G.far&&G.far[G.zone])||0;if(fm>(farMark[G.zone]||0)){farMark[G.zone]=fm;lastProgressH=M.hours;}}
    let cl=0;for(let i=0;i<G.cleared.length;i++)if(G.cleared[i])cl++;if(cl>lastCleared){lastCleared=cl;const zi=G.cleared.lastIndexOf(true);M.zones[Z[zi].name]=M.zones[Z[zi].name]||+M.hours.toFixed(2);lastProgressH=M.hours;{const rk=String(G.reforges||0);M.runClears=M.runClears||{};M.runClears[rk]=M.runClears[rk]||{};M.runClears[rk][Z[zi].name]=M.runClears[rk][Z[zi].name]||+M.hours.toFixed(2);}const zr=M.zoneRec[Z[zi].name];if(zr&&!zr.clearH){zr.clearH=+M.hours.toFixed(2);zr.lvAtClear=avgLv();zr.hours=+(zr.clearH-zr.enterH).toFixed(2);const b=M.boss[Z[zi].name];if(b){b.streak=0;b.stallH=+((simSec-b.firstTry)/3600).toFixed(2);b.lvClear=avgLv();b.attemptsToClear=b.attempts;if(b.attemptLog&&b.attemptLog.length){const L=b.attemptLog[b.attemptLog.length-1],fsx=G.fs||{};L.win=true;Object.assign(L,{dur:+(simSec-b.firstTry-(b.retryStall||0)-(b.combatStall||0)).toFixed(1),survivors:G.active.filter(h=>!h.dead).length,partyHp:+(G.active.reduce((q,h)=>q+Math.max(0,h.hp),0)/Math.max(1,G.active.reduce((q,h)=>q+h.maxhp,0))).toFixed(2),telegraphs:fsx.chargeTelegraphs||0,chargeHits:fsx.chargeHits||0,chargeKills:fsx.chargeKills||0,parried:fsx.chargeParried||0,interrupted:fsx.chargeInterrupted||0,bossHits:fsx.bossHits||0,raised:fsx.raised||0,run:G.reforges||0,chargeDetail:(fsx.chargeDetail||[]).map(d=>({pct:+(d.dmg/Math.max(1,d.maxhp)).toFixed(2),front:!!d.front,ranged:!!d.ranged})),taken:Object.fromEntries(Object.entries(fsx.taken||{}).map(([k,v])=>[k,Math.round(v)])),deaths:G.active.filter(h=>h.dead).length});}b.fightsBetween=G.wins-b.winsAtFirst-b.attempts+1;b.lvGain=b.lvClear-b.lvFirst;b.upsBetween=M.gearUps-b.upsAtFirst;b.combatStallH=+((b.combatStall||0)/3600).toFixed(2);b.retryStallH=+((b.retryStall||0)/3600).toFixed(2);}}ev('cleared',Z[zi].name+' (party Lv '+avgLv()+')');}
    if(G.zone!==lastZone){lastZone=G.zone;zoneEnter=simSec;zoneDefeats=0;const zn=Z[G.zone].name;if(!M.zoneRec[zn])M.zoneRec[zn]={enterH:+M.hours.toFixed(2),lvAtEntry:avgLv()};const rk=String(G.reforges||0);M.runZones=M.runZones||{};M.runZones[rk]=M.runZones[rk]||{};if(!M.runZones[rk][zn])M.runZones[rk][zn]={enterH:+M.hours.toFixed(2),lvAtEntry:+avgLv().toFixed(1),power:S.partyPower(),gear:G.active.map(h=>h.name+':'+['weapon','cape','charm'].map(sl=>h.eq&&h.eq[sl]?h.eq[sl].rank+'/'+h.eq[sl].lvl:'-').join(',')).join('|'),ore:Math.round(G.ore)};}
    if(G.delve){M.delve.best=Math.max(M.delve.best,G.delve.floor||0);}
    if(Z[G.zone].endless){const b=G.prog[G.zone]||0;if(b>M.endless.best){const m0=Math.floor(M.endless.best/25),m1=Math.floor(b/25);M.endless.best=b;if(m1>m0&&(m1%10===0||m1<=3))ev('milestone','#'+m1+' at fight '+b+' (party Lv '+avgLv()+', omens '+(G.omens||[]).length+', renown '+S.fmtNum(G.renown||0)+')');}}
    if(simSec>=nextAct){nextAct=simSec+5;act();}
    while(M.hours>=nextHour){const hh=nextHour;nextHour++;M.gold.push(Object.assign(SCHEDULE?{played:+((simSec-offlineSec)/3600).toFixed(2)}:{},{h:hh,gold:Math.round(G.gold),ore:Math.round(G.ore),dust:G.dust,zone:Z[G.zone].name,prog:G.prog[G.zone],lv:avgLv(),wins:G.wins,power:S.partyPower(),run:G.reforges||0,defeats:G.stats.defeats||0,earnedGold:Math.round(M.econ.goldEarned),earnedOre:Math.round(M.econ.oreEarned),spentGold:Math.round(M.econ.goldSpent),spentOre:Math.round(M.econ.oreSpent),spendBy:Object.assign({},M.spendBy||{}),renown:Math.round(G.renown||0),wave:Z[G.zone].endless?G.prog[G.zone]:null,bestWave:Z[G.zone].endless?(G.run&&G.run.endless)||0:null,enemyLv:Z[G.zone].endless?Z[G.zone].lv+Math.floor(G.prog[G.zone]*0.15):null,gearUps:M.gearUps,treeLv:Object.values(G.tree||{}).reduce((a,b)=>a+b,0),castle:Object.values(G.castle.b||{}).reduce((a,b)=>a+b,0),trainSec:(G.stats.autoTrain&&G.stats.autoTrain.timeSec)||0,itemRank:+(G.active.reduce((a,h)=>a+['weapon','cape','charm'].reduce((x,sl)=>x+(h.eq&&h.eq[sl]?h.eq[sl].rank:0),0),0)/Math.max(1,3*G.active.length)).toFixed(2),itemLvl:+(G.active.reduce((a,h)=>a+['weapon','cape','charm'].reduce((x,sl)=>x+(h.eq&&h.eq[sl]?h.eq[sl].lvl:0),0),0)/Math.max(1,3*G.active.length)).toFixed(1)}));if(!QUIET&&(M.hours|0)%4===0)console.log(`   -- ${M.hours|0}h zone ${Z[G.zone].name} prog ${G.prog[G.zone]} Lv ${avgLv()} gold ${S.fmtNum(G.gold)} ore ${S.fmtNum(G.ore)} dust ${G.dust} shatters ${G.reforges||0} (${((Date.now()-t0)/1000).toFixed(0)}s real)`);}
    if(args.stopAtShatters&&(G.reforges||0)>=Number(args.stopAtShatters))break;
    if(args.untilZone&&Object.keys(M.zones).some(z=>z.toLowerCase().startsWith(String(args.untilZone).toLowerCase())))break;
    if(args.untilShatter&&(G.reforges||0)>=Number(args.untilShatter))break;
    if(args.untilLevel&&avgLv()>=Number(args.untilLevel))break;
    if(args.endless&&Math.floor(M.endless.best/25)>=args.endless)break;
  }
  report();

  function inWindow(){return (simSec%3600)<P.activeMin*60;}
  function checkin(){return SCHEDULE?(simSec-blockStart)<180:simSec<180;} /* the first three minutes of every session: the player opens the game, collects and drills, whatever the profile */
  function goOffline(offH){if(!(offH>0))return;const lastT=S.clock.get(),g0=G.gold,o0=G.ore;if(G.drill&&G.drill.running)S.abortDrill();S.clock.advance(offH*3600*1000);offlineSec+=offH*3600;simSec=(S.clock.frames()-frame0)/FPS+offlineSec;curTick=simSec;S.setRT(simSec);M.hours=simSec/3600;G.sheet=null;try{S.offlineReport(lastT);}catch(e){ev('ERROR','offline: '+e.message);}const o=G.offline;let doubled=false;if(o&&DOUBLE&&S.doubleOffline){doubled=S.doubleOffline();if(doubled)M.boosts.doubles++;}M.offline.push({h:+M.hours.toFixed(2),offH,fights:o?o.fights:0,gold:Math.round(G.gold-g0),ore:Math.round(G.ore-o0),doubled});M.econ.goldEarned+=Math.max(0,G.gold-g0);M.econ.oreEarned+=Math.max(0,G.ore-o0);lastGold=G.gold;lastOre=G.ore; /* counted here so the final break is in the totals even when the run ends on it */G.offline=null;G.sheet=null;ev('offline',offH+'h away: +'+S.fmtNum(G.gold-g0)+' gold, +'+S.fmtNum(G.ore-o0)+' ore'+(doubled?' (doubled)':''));drillQueue=DRILLS?S.drillBrackets().slice():[];} /* the production offline report (capped at its own hours), the ad double when the model says so, and a fresh drill queue for the next session */
  function drillScore(x){return x.atk*(1+(S.abilityPower?S.abilityPower(x):0))*(x.spd||1);} /* expected 30-second output: attack, ability power and speed */
  function drillStep(){const d=G.drill;if(d&&d.running){S.drillTick(DT);drillTapAcc+=TAPS*DT;while(drillTapAcc>=1){drillTapAcc-=1;M.taps++;try{S.withDrill(()=>S.tapEnemy(G.enemies[0]));}catch(e){}}return;}
    if(d&&!d.running&&!d.aborted&&!d.logged){d.logged=true;M.drills.runs++;const t=d.tier,tn=t<0?'none':S.DRILL.tiers[t];M.drills.tiers[tn]=(M.drills.tiers[tn]||0)+1;{const n=G.reforges||0;if(n!==drillCycle){drillCycle=n;drillAttempts={};}const key=S.drillBracketKey(d.bracket);drillAttempts[key]=(drillAttempts[key]||0)+1;const tg=S.drillTarget(d.bracket);if(drillFirstCycle[key]==null)drillFirstCycle[key]=n;const firstCycle=drillFirstCycle[key]===n;if(d.paid){const bk=M.drills[firstCycle?'first':'repeat'][d.bracket.kind];bk.claims++;bk.gold+=d.paid.gold;bk.dust+=d.paid.dust;}M.drillLog.push({h:+M.hours.toFixed(2),played:+((simSec-offlineSec)/3600).toFixed(2),key,kind:d.bracket.kind,shatters:n,firstCycle,attempt:drillAttempts[key],tier:t,total:Math.round(d.stats.total),crystal:tg?tg[3]:null,lv:d.hero&&d.hero.lvl,dust:d.paid?d.paid.dust:0,gold:d.paid?d.paid.gold:0});}if(d.paid){M.drills.paid++;M.drills.gold+=d.paid.gold;M.drills.ore+=d.paid.ore;M.drills.dust+=d.paid.dust;ev('drill',d.bracket.name+' '+S.fmtNum(d.stats.total)+' -> '+tn+' +'+S.fmtNum(d.paid.gold)+' gold'+(d.paid.ore?' +'+S.fmtNum(d.paid.ore)+' ore':'')+(d.paid.dust?' +'+d.paid.dust+' dust':''));}S.closeSheet();G.screen='road';}
    if(!(inWindow()||checkin())||G.delve||G.hordeFight||!drillQueue.length)return;const br=drillQueue.shift();const rec=S.drillRecords(),cl=rec.claimed[S.drillBracketKey(br)];if(cl!=null&&cl>=3)return;const hs=G.active.filter(x=>!x.dead&&S.heroStatus(x)!=='quest');if(!hs.length)return;const hero=hs.slice().sort((a,c)=>drillScore(c)-drillScore(a))[0];try{if(S.startDrill(hero,br))G.drill.logged=false;}catch(e){}} /* one drill per open bracket per session, the hardest-hitting hero, taps at the profile rate; the road keeps running underneath as in production */
  function ensureBoost(){if(!P.boost){G.autoCast=false;G.autoUntil=0;return;}const t=S.clock.get();if(!(G.autoUntil>t)){G.autoUntil=t+BOOST_MS;M.boostBuys=(M.boostBuys||0)+1;}G.autoCast=true;}
  function play(){const act=inWindow();if(act!==wasActive){wasActive=act;const d=Object.assign({basic:0,ability:0,tap:0,surge:0},(G.stats&&G.stats.dmgBy)||{});const bucket=act?M.dmgAuto:M.dmgActive;for(const k in d)bucket[k]+=d[k]-(dmgMark[k]||0);dmgMark=d;}if(act)M.activeSec+=DT;
    if(!act){ensureBoost();surgeReadyAt=0;return;}if(DRILLS&&G.drill&&G.drill.running)return; /* on the drill screen there are no road inputs at all */G.autoCast=false;if(G.mode!=='battle'){surgeReadyAt=0;return;}for(const h of G.active){if(!h.dead&&h.charge>=100&&!h.tapCast){if(S.reactTo(h)){if(S.noteAttention)S.noteAttention();continue;}if(S.tapCastHero)S.tapCastHero(h);else{h.tapCast=true;h.charge=0;}}}if(G.surge>=100&&!G.delve&&!G.hordeFight){try{S.castSurge();}catch(e){}}tapAcc+=TAPS*DT;while(tapAcc>=1){M.taps++;tapAcc-=1;const foes=G.enemies.filter(e=>!e.dead);if(!foes.length)break;const t=(G.focus&&G.focus.e&&!G.focus.e.dead)?G.focus.e:foes.sort((a,b)=>a.hp-b.hp)[0];try{S.tapEnemy(t);}catch(e){}}}
  function avgLv(){let hs=G.active.filter(h=>h.joinSec==null||h.joinSec!==curTick);if(!hs.length)hs=G.active;return Math.round(hs.reduce((a,h)=>a+h.lvl,0)/Math.max(1,hs.length));} // a hero recruited this tick (at a zone clear) does not drag the sampled level down
  function zoneOk(i){return S.zoneUnlocked?S.zoneUnlocked(i):(i===0||G.cleared[i-1]);} // the game's rule: previous boss beaten and enough Shatters for the zone
  function travelTo(i){if(i===G.zone||!zoneOk(i))return;S.goZone(i);G.screen='road';ev('travel',Z[i].name);}

  function act(){
    G.sheet=null;
    if(CLERIC_BACK&&G.mode==='walk'){const cl=G.active.filter(x=>x.cls==='cleric');if(cl.length&&G.active[G.active.length-1].cls!=='cleric'){const rest=G.active.filter(x=>x.cls!=='cleric');G.active.length=0;for(const x of rest.concat(cl))G.active.push(x);S.layout();ev('formation','cleric to the back: '+G.active.map(x=>x.name).join(' > '));}} /* survival strategy: the Cleric never stands in front */
    if(BOOSTS&&(inWindow()||checkin())){if(S.useWarp&&S.useWarp()){M.boosts.warps++;ev('warp','time warp used');}if(S.openDailyChest){const it=S.openDailyChest();if(it){M.boosts.chests++;ev('chest','daily chest: '+S.itemName(it));}}}
    // omens: take the first offer
    if(G.omenOffer&&G.omenOffer.length){G.omens=(G.omens||[]).concat([G.omenOffer[0]]);G.omenOffer=null;}
    if(G.hordeFight||G.delve){delveStep();return;}
    // gear: equip the best, salvage the rest
    {const before=G.roster.map(h=>Object.values(h.eq||{}).map(i=>i&&i.id).join(',')).join('|');try{S.equipBest();}catch(e){}const after=G.roster.map(h=>Object.values(h.eq||{}).map(i=>i&&i.id).join(',')).join('|');if(after!==before)M.gearUps++;}
    for(const it of G.pack.slice()){if(it.super)continue;S.salvageItem(it);}
    // gear ascension (pass 24 policy): after the first Shatter, ascend equipped items of the active party toward the production cap, heroes in party order, slots weapon, cape, charm, restarting from the top after each purchase; then the item-level policy below
    let ascHold=0;{ /* ascension is the gear ladder from run 0: rank 1 needs no Shatter, the level cap binds first */for(let guard=0;guard<200;guard++){let did=false;for(const h of G.active){for(const slot of ['weapon','cape','charm']){const it=h.eq&&h.eq[slot];if(!it||it.super)continue;if(it.rank>=4||it.rank>=S.ascendCap())continue;const c=S.ascendCost(it);if(G.ore<c)continue;const o0=G.ore,r0=it.rank,cap=S.ascendCap();S.ascendItem(it,h);const rec={h:+M.hours.toFixed(2),run:G.reforges||0,hero:h.name,slot,id:it.id,from:r0,to:it.rank,lvl:it.lvl,cost:c,cap,oreBefore:Math.round(o0),oreAfter:Math.round(G.ore)};if(it.rank===r0+1&&Math.abs((o0-G.ore)-c)<1e-6){(M.ascensions=M.ascensions||[]).push(rec);acc('ascendOre',c);did=true;break;}else{(M.ascAnomalies=M.ascAnomalies||[]).push(rec);}}if(did)break;}if(!did)break;}
      if(args.ascendReserve){let cheapest=Infinity;for(const h of G.active)for(const slot of ['weapon','cape','charm']){const it=h.eq&&h.eq[slot];if(!it||it.super||it.rank>=4||it.rank>=S.ascendCap())continue;cheapest=Math.min(cheapest,S.ascendCost(it));}const income=(M.econ.oreEarned||0)/Math.max(0.5,M.hours);if(cheapest<Infinity&&cheapest<=Number(args.ascendReserve)*income)ascHold=cheapest;}}
    // gear upgrades: cheapest equipped item first while ore allows
    for(let k=0;k<6;k++){let best=null,bc=Infinity,bh=null;for(const h of G.roster){for(const it of Object.values(h.eq||{})){if(!it)continue;if(S.itemLvlCap&&it.lvl>=S.itemLvlCap(it))continue;const c=S.upgradeCost(it);if(c<bc){bc=c;best=it;bh=h;}}}if(!best||bc>(G.ore-ascHold)*0.8)break;const m=G.mult;G.mult=1;const o0=G.ore;S.upgradeItem(best,bh);G.mult=m;if(G.ore<o0){M.gearUps++;acc('gearOre',o0-G.ore);}}
    spend();
    // promotions and talents (gated by level in the game itself)
    for(const h of G.roster){const q=S.promoteReq(h);if((h.tier||0)<3&&h.lvl>=q.lvl&&G.gold>=q.gold&&G.dust>=q.dust){const t=h.tier||0;{const g0=G.gold,d0=G.dust;S.promoteHero(h);acc('promoteGold',g0-G.gold);acc('promoteDust',d0-G.dust);}if((h.tier||0)>t){M.promotions[h.name+' T'+h.tier]=+M.hours.toFixed(2);if(M.firsts['first T'+h.tier]==null)M.firsts['first T'+h.tier]=+M.hours.toFixed(2);ev('promote',h.name+' -> tier '+h.tier);}}
      const TL=S.TALENTS[h.cls]||[];TL.forEach((t,i)=>{if(h.talents&&h.talents[t.id])return;const q=S.talentReq(i);if(h.lvl>=q.lvl&&G.gold>=q.gold*1.2){{const g0=G.gold;S.buyTalent(h,i);acc('talentsGold',g0-G.gold);}if(h.talents[t.id]){M.talents[h.name+': '+t.name]=+M.hours.toFixed(2);if(M.firsts['first talent']==null)M.firsts['first talent']=+M.hours.toFixed(2);ev('talent',h.name+' learns '+t.name);}}});}
    // road decisions
    const zi=G.zone;
    if(G.train&&G.train.active){/* the game is training in the previous zone */}
    else if(retreatUntil&&simSec<retreatUntil){/* farming the previous zone */}
    else if(G.cleared[zi]&&zi<Z.length-1&&zoneOk(zi+1)){if(!Z[zi+1].endless||avgLv()>=Z[zi+1].lv-2)travelTo(zi+1);}
    else if(RETREAT_AFTER>0&&(RETREAT_ON==='defeats'?zoneDefeats:((M.boss[Z[zi].name]||{}).streak||0))>=RETREAT_AFTER&&zi>0&&!Z[zi].endless&&G.mode==='walk'){M.stuck.push({zone:Z[zi].name,h:+M.hours.toFixed(2),lv:avgLv()});ev('retreat',Z[zi].name+' after '+(RETREAT_ON==='defeats'?zoneDefeats+' defeats':((M.boss[Z[zi].name]||{}).streak||0)+' boss losses')+', training in '+Z[zi-1].name);const b=M.boss[Z[zi].name];if(b){b.trainStart=simSec;b.lvTrainStart=avgLv();b.winsTrainStart=G.wins;}travelTo(zi-1);trainingFor=zi;if(M.boss[Z[zi].name])M.boss[Z[zi].name].streak=0;retreatUntil=simSec+7200;farmTarget=TRAIN_MODE.startsWith('level')?avgLv()+Number(TRAIN_MODE.slice(5)||1):0;zoneDefeats=0;farmFights=TRAIN_MODE.startsWith('fights')?G.wins+Number(TRAIN_MODE.slice(6)||10):0;G.bossStreak=0;}
    if(retreatUntil&&(simSec>=retreatUntil||(farmTarget&&avgLv()>=farmTarget)||(farmFights&&G.wins>=farmFights))&&G.mode==='walk'){const b=M.boss[Z[trainingFor].name];if(b&&b.trainStart){b.trainTime=(b.trainTime||0)+(simSec-b.trainStart);b.trainLv=(b.trainLv||0)+(avgLv()-b.lvTrainStart);b.trainFights=(b.trainFights||0)+(G.wins-b.winsTrainStart);b.trainStart=0;}retreatUntil=0;farmTarget=0;farmFights=0;travelTo(trainingFor);}
    // hordes: prepare and fight when due
    if(G.castle.hordeDue&&S.hordeWindow().used<2&&G.mode==='walk'){const p=G.castle.prep||(G.castle.prep={});for(const k of ['walls','merc']){const c=S.prepCost(k);if(!p[k]&&G.gold>=c*3){G.gold-=c;p[k]=true;if(k==='merc')p.mercLv=1;}}const before=G.castle.hordeCount||0;try{S.startHordeFight();}catch(e){}if(G.hordeFight)ev('horde','#'+((G.castle.currentHorde||{}).number||'?')+' '+S.hordeTier()+' threat '+S.fmtNum(S.hordeThreat())+' vs defense '+S.defense().total);}
    // catacombs when a key is ready and the road is quiet
    if(!G.delve&&(G.delveKeys||0)>0&&G.mode==='walk'&&G.roster.length>=3){const h=G.roster.slice().sort((a,b)=>b.lvl-a.lvl)[0];try{S.startDelve(h);M.delve.runs++;}catch(e){}}
    // shatter: once eligible, when the party has been stuck a while or the gain is large
    if(S.canReforge()&&SHATTERS&&(G.reforges||0)<SHATTERS){const gain=S.reforgeGain();const stalled=(M.hours-lastProgressH)>=(args.stallHours||3);const sealed=!!(G.cleared[G.zone]&&G.zone<Z.length-1&&!zoneOk(G.zone+1));if(gain>=15&&(stalled||sealed||(Z[G.zone].endless&&(G.prog[G.zone]||0)>=100))){const rec={h:+M.hours.toFixed(2),run:G.reforges||0,zone:Z[G.zone].name,prog:G.prog[G.zone]||0,cleared:G.cleared.filter(Boolean).length,lv:+avgLv().toFixed(1),power:S.partyPower(),gain,dustBefore:G.dust,stallH:+(M.hours-lastProgressH).toFixed(2),reason:sealed?'sealed':stalled?'stalled':'endless',farMark:farMark[G.zone]||0,lastProgressH:+lastProgressH.toFixed(2),before:S.partyState(),defeatsAt:G.stats.defeats||0,winsAt:G.wins,trainSecAt:(G.stats.autoTrain&&G.stats.autoTrain.timeSec)||0,byZoneAt:JSON.parse(JSON.stringify((G.stats&&G.stats.byZone)||{})),zoneTimeAt:JSON.parse(JSON.stringify(M.zoneTime||{})),bossAt:Object.fromEntries(Object.entries(M.boss).map(([k,v])=>[k,(v.attemptLog||[]).length]))};G.oathPick=null;if(args.snapshots){try{const fs=require('fs'),path=require('path');fs.mkdirSync(String(args.snapshots),{recursive:true});fs.writeFileSync(path.join(String(args.snapshots),'shatter'+((G.reforges||0)+1)+'_'+PROFILE+'_'+SEED+'.json'),JSON.stringify({shatter:(G.reforges||0)+1,profile:PROFILE,seed:SEED,hours:+M.hours.toFixed(2),zone:Z[G.zone].name,endless:(G.run&&G.run.endless)||0,lv:avgLv(),save:S.serialize()}));}catch(e){}} /* the state at its peak, just before the Shatter (drill benches) */S.doReforge();lastProgressH=M.hours;lastCleared=0;farMark={};rec.dustAfterGain=G.dust;rec.purchases=dustSpend();rec.dustAfter=G.dust;rec.treeAfter={b_start:S.treeLv('b_start'),b_hp:S.treeLv('b_hp'),b_dmg:S.treeLv('b_dmg')};rec.startLvNextRun=1+5*S.treeLv('b_start');rec.lvAfter=+avgLv().toFixed(1);rec.powerAfter=S.partyPower();rec.dust=G.dust;M.shatters.push(rec);M.firsts['shatter '+G.reforges]=+M.hours.toFixed(2);ev('shatter','#'+G.reforges+' for +'+gain+' dust (total '+G.dust+')');zoneDefeats=0;retreatUntil=0;}}
  }
  function delveStep(){const d=G.delve;if(!d)return;if(d.choose&&(d.floor||0)>=(args.delveCap||30)){S.endDelve(false,true);return;}if(d.choose){const h=d.hero;const f=h.hp/h.maxhp;const pick=(k)=>d.doors.includes(k)?k:null;let k=null;if(f<0.45)k=pick('rest')||pick('chest')||pick('shrine');if(!k&&f>0.8)k=pick('elite')||pick('chest')||pick('fight');if(!k)k=pick('chest')||pick('fight')||pick('rest')||pick('shrine')||pick('merchant')||d.doors[0];if(f<0.3&&!pick('rest')){M.delve.runs;S.endDelve(false,true);return;}try{S.chooseDoor(k);}catch(e){}}}

  // Post-Shatter dust policy (pass 22): spend dust on b_start, then b_hp, then b_dmg; restart at b_start after every purchase; stop when no next rank is affordable.
  function dustSpend(){const DUST_PRIORITY=['b_start','b_hp','b_dmg'];const bought=[];for(;;){let did=false;for(const id of DUST_PRIORITY){const n=S.TREE.find(x=>x.id===id);if(!n)continue;const lv=S.treeLv(id);if(lv>=n.max)continue;const c=S.nodeCost(n,lv);if(G.dust>=c&&S.buyTreeRank(n)){for(const h of G.roster)S.refreshStats(h);bought.push({id,cost:c,rank:lv+1,dustLeft:G.dust,h:+M.hours.toFixed(2)});acc('blessingsDust',c);did=true;break;}}if(!did)break;}if(bought.length){M.dustBuys=(M.dustBuys||[]).concat(bought);}return bought;}
  function acc(k,v){if(!(v>0))return;M.spendBy=M.spendBy||{};M.spendBy[k]=(M.spendBy[k]||0)+v;}
  function spend(){if((G.reforges||0)>0)dustSpend();
    const C=G.castle;
    for(let guard=0;guard<40;guard++){let did=false;
      // buildings: cheapest of the three while it is under a third of our gold
      let bk=null,bc=Infinity;for(const k of ['market','mine','walls']){const c=S.buildCost(k);if(c<bc){bc=c;bk=k;}}
      const pressure=zoneDefeats>=2||retreatUntil>0;if(bk&&bc<=G.gold*(pressure?0.08:0.3)){G.gold-=bc;C.b[bk]++;acc('castleGold',bc);did=true;}
      // villagers: hire while cheap, then assign idle ones
      const hc=S.hireCost();if(C.vil.total<S.vilCap()&&hc<=G.gold*0.15){G.gold-=hc;C.hired++;C.vil.total++;acc('hiresGold',hc);did=true;}
      while(S.idleVil()>0){const canM=C.vil.market<C.b.market*3,canI=C.vil.mine<C.b.mine*3;if(canM&&(!canI||C.vil.market<=C.vil.mine))C.vil.market++;else if(canI)C.vil.mine++;else break;did=true;}
      // ability ranks: cheapest hero while under a fifth of gold
      let rh=null,rc=Infinity;for(const h of G.roster){const c=S.rankCost(h);if(c<rc){rc=c;rh=h;}}
      if(rh&&rc<=G.gold*(pressure?0.4:0.2)){G.gold-=rc;rh.abLvl++;acc('ranksGold',rc);did=true;}
      // tree: cheapest gold node under a fifth of gold; dust nodes with spare dust
      let tn=null,tc=Infinity;for(const n of S.TREE){if(S.treeLv(n.id)>=n.max)continue;const isD=n.cur==='dust';if(isD&&(G.reforges||0)>0)continue;const c=S.nodeCost(n,S.treeLv(n.id)); /* the production price, per-node growth included */const combat=['hp','atk','def','abil','front','crit'].includes(n.id);const budget=isD?G.dust*0.5:G.gold*((pressure&&combat)?0.45:combat?0.25:0.12);if(c<=budget&&c<tc){tc=c;tn=n;}}
      if(tn){const g0=G.gold,d0=G.dust;if(S.buyTreeRank(tn)){acc('treeDust',d0-G.dust);acc('treeGold',g0-G.gold);for(const h of G.roster)S.refreshStats(h);did=true;}} /* bought through the production function */
      // garrison: post idle heroes on the walls
      const slots=S.garrisonSlots();if(C.garrison.length<slots){const idle=G.roster.find(h=>!G.active.includes(h)&&!C.garrison.includes(h.id)&&S.heroStatus(h)==='camp');if(idle){const before=C.garrison.length;S.postHero(idle);if(C.garrison.length>before){did=true;const left=S.postLeft(idle);M.postChecks=M.postChecks||[];M.postChecks.push({id:idle.id,name:idle.name,at:simSec,left0:left});if(!(left>3599&&left<=3600))M.postFail=M.postFail||('post timer '+left+'s right after posting '+idle.name);}}}
      if(!did)break;}
  }

  function replayFight(K){const keep=structuredClone(G);const rt0=S.getRT(),ms0=S.clock.get(),cm=S.clock.mark();let wins=0,n=0,res=[];for(let k=0;k<K;k++){for(const key of Object.keys(G))delete G[key];Object.assign(G,structuredClone(keep));S.setRT(rt0);S.clock.restore(cm);let out=null;for(let i=0;i<20*600;i++){S.clock.frame();S.setRT(rt0+(i+1)/FPS);G.tut=null;{const n=S.speedNow();for(let k=0;k<n;k++)S.update(DT,k===0);}G.parts.length=0;G.floats.length=0;if(ACTIVE){const act=inWindow();if(!act){ensureBoost();}else{G.autoCast=false;for(const h of G.active){if(!h.dead&&h.charge>=100&&!h.tapCast){if(S.reactTo(h)){if(S.noteAttention)S.noteAttention();continue;}if(S.tapCastHero)S.tapCastHero(h);else{h.tapCast=true;h.charge=0;}}}}}if(G.mode==='victory'){out='W';break;}if(G.mode==='defeat'){out='L';break;}}if(out){n++;if(out==='W')wins++;res.push(out);}}for(const key of Object.keys(G))delete G[key];Object.assign(G,keep);S.setRT(rt0);S.clock.restore(cm);ev('replay',bossZoneName+' live-state replay x'+n+': '+Math.round(100*wins/Math.max(1,n))+'% wins ('+res.join('')+') window='+(inWindow()?'active':'auto'));}
  function med(a){a=a.filter(v=>v!=null).sort((x,y)=>x-y);return a.length?a[Math.floor((a.length-1)/2)]:null;}
  function report(){
    if(args.snapshots){try{const fs=require('fs'),path=require('path');fs.mkdirSync(String(args.snapshots),{recursive:true});fs.writeFileSync(path.join(String(args.snapshots),'final_'+PROFILE+'_'+SEED+'.json'),JSON.stringify({final:true,profile:PROFILE,seed:SEED,hours:+M.hours.toFixed(2),zone:Z[G.zone].name,reforges:G.reforges||0,endless:(G.run&&G.run.endless)||0,lv:avgLv(),save:S.serialize()}));}catch(e){}} /* the end-of-run state (drill benches for the deepest brackets) */
    if(M.speedCur){M.speedCur.partial=true;M.speedCur.realSec=+(simSec-M.speedCur.at).toFixed(3);M.speedCur.gameSec=+M.speedCur.gameSec.toFixed(3);M.speedCur=null;}
    const dm=(G.stats&&G.stats.dmgBy)||{};const dtot=Object.values(dm).reduce((a,b)=>a+b,0)||1;const dmgShare=Object.fromEntries(['basic','ability','tap','surge'].map(k=>[k,+((dm[k]||0)/dtot).toFixed(3)]));const hrs=Math.max(0.01,M.hours);
    const dmgPerHour=Object.fromEntries(['basic','ability','tap','surge'].map(k=>[k,Math.round((dm[k]||0)/hrs)]));dmgPerHour.total=Math.round(dtot/hrs);const castsPerHour=Math.round(((G.stats&&G.stats.casts)||0)/hrs);
    {const d=Object.assign({basic:0,ability:0,tap:0,surge:0},dm);const bucket=wasActive?M.dmgActive:M.dmgAuto;for(const k in d)bucket[k]+=d[k]-(dmgMark[k]||0);dmgMark=d;}
    const shareOf=o=>{const t=Object.values(o).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(Object.entries(o).map(([k,v])=>[k,+(v/t).toFixed(3)]));};const activeH=Math.max(0.001,M.activeSec/3600);const dmgActiveWindow={share:shareOf(M.dmgActive),perHour:Math.round(Object.values(M.dmgActive).reduce((a,b)=>a+b,0)/activeH),hours:+activeH.toFixed(2)};
    const out={config:{hours:HOURS,shatters:SHATTERS,seed:SEED,dt:DT,frameCap:FRAME_CAP,profile:PROFILE,commit:PROVENANCE.commit,dirty:PROVENANCE.dirty,replaced:PROVENANCE.replaced||null,gameHash:PROVENANCE.gameHash,harnessHash:PROVENANCE.harnessHash,taps:TAPS,activeMin:P.activeMin,boost:!!P.boost,speed:SPEED,speed4Buys:SPEED4_BUYS===Infinity?'unlimited':SPEED4_BUYS,schedule:args.schedule||null,drills:DRILLS,double:DOUBLE,boosts:BOOSTS,clericBack:CLERIC_BACK,retreatAfter:RETREAT_AFTER,retreatOn:RETREAT_ON,trainUntil:TRAIN_MODE,stallRule:STALL_RULE,stallHours:args.stallHours||3,noAutoTrain:!!args.noAutoTrain,bossHp:args.bossHp,bossAtk:args.bossAtk},hordes:{repelled:G.castle.repelled||0,lost:G.castle.lost||0,fought:G.stats.hordes||0},byZone:(G.stats&&G.stats.byZone)||{},zoneTime:M.zoneTime||{},autoTrain:(G.stats&&G.stats.autoTrain)||null,deadTime:{rewalkFights:(G.stats&&G.stats.rewalk)||0,rewalkBossFights:(G.stats&&G.stats.rewalkBoss)||0,rewalkWhileTraining:(G.stats&&G.stats.rewalkTrain)||0,defeatsOutsideTraining:(G.stats&&G.stats.defeatsNoTrain)||0,encounters:G.wins+((G.stats&&G.stats.defeats)||0),secPerEncounter:+(simSec/Math.max(1,G.wins+((G.stats&&G.stats.defeats)||0))).toFixed(1)},dmgShare,dmgPerHour,castsPerHour,dmgActiveWindow,firsts:M.firsts,zoneRec:M.zoneRec,econPerHour:{goldEarned:Math.round(M.econ.goldEarned/hrs),goldSpent:Math.round(M.econ.goldSpent/hrs),oreEarned:Math.round(M.econ.oreEarned/hrs),oreSpent:Math.round(M.econ.oreSpent/hrs),renown:Math.round((G.renown||0)/hrs)},simHours:+M.hours.toFixed(2),final:{zone:Z[G.zone].name,prog:G.prog[G.zone],partyLv:avgLv(),gold:Math.round(G.gold),ore:Math.round(G.ore),dust:G.dust,shatters:G.reforges||0,wins:G.wins,defeats:G.stats.defeats||0,castle:G.castle.b,renown:G.renown||0},
      profile:PROFILE,boost:!!P.boost,boostBuys:M.boostBuys||0,schedule:SCHEDULE,playHours:+((simSec-offlineSec)/3600).toFixed(2),offlineHours:+(offlineSec/3600).toFixed(2),offline:M.offline,drills:M.drills,drillLog:M.drillLog,boosts:M.boosts,dustBySource:{shatters:M.shatters.reduce((a,s)=>a+(s.gain||0),0),drills:M.drills.dust},model:{drills:DRILLS,double:DOUBLE,boosts:BOOSTS,clericBack:CLERIC_BACK},speedModel:SPEED===4?'timed 2h boost via buySpeed4, rebought when lapsed (max '+(SPEED4_BUYS===Infinity?'unlimited':SPEED4_BUYS)+' purchases)':'toggle held',speedBoosts:M.speedBoosts,speedBuys:M.speedBuys,gameHours:+(M.gameSec/3600).toFixed(3),taps:M.taps,tapsPerActiveSec:+(M.taps/Math.max(1,M.activeSec)).toFixed(3),assertFail:M.assertFail||null,postChecks:M.postChecks||[],recruits:M.recruits,zonesCleared:M.zones,runZones:M.runZones||{},runClears:M.runClears||{},dustBuys:M.dustBuys||[],ascensions:M.ascensions||[],ascAnomalies:M.ascAnomalies||[],spendBy:M.spendBy||{},promotions:M.promotions,talents:M.talents,shatters:M.shatters,bossFailRates:Object.fromEntries(Object.entries(M.boss).map(([k,v])=>[k,{attempts:v.attempts,fails:v.fails,rate:v.attempts?+(v.fails/v.attempts).toFixed(2):0,maxStreak:v.maxStreak,stallH:v.stallH==null?null:v.stallH,lvFirst:v.lvFirst,lvClear:v.lvClear==null?null:v.lvClear,attemptsToClear:v.attemptsToClear==null?null:v.attemptsToClear,firstTryClear:v.attemptsToClear==null?null:(v.attemptsToClear===1?1:0),arrival:v.arrival||null,attemptLog:v.attemptLog||[],combatStallH:v.combatStallH,retryStallH:v.retryStallH,trainH:v.trainTime==null?0:+(v.trainTime/3600).toFixed(2),inZoneRetryH:v.retryStallH==null?null:+(v.retryStallH-(v.trainTime||0)/3600).toFixed(2),trainLv:v.trainLv==null?0:+v.trainLv.toFixed(1),trainFights:v.trainFights||0,fightsBetween:v.fightsBetween,lvGain:v.lvGain,upsBetween:v.upsBetween,lossDur:med(v.losses.map(l=>l.dur)),winDur:med(v.wins.map(w=>w.dur)),hpLeft:med(v.losses.map(l=>l.hpLeft)),wipePct:v.losses.length?Math.round(100*v.losses.filter(l=>l.wipe).length/v.losses.length):null,survivors:med(v.wins.map(w=>w.survivors)),partyHp:med(v.wins.map(w=>w.partyHp))}])),
      rngCalls:S.rngCalls?S.rngCalls():null,rngState:S.seed?S.seed():null,roster:G.roster.map(h=>({name:h.name,cls:h.cls,lvl:h.lvl,tier:h.tier||0,abLvl:h.abLvl||0,talents:Object.keys(h.talents||{}).filter(k=>h.talents[k]).sort(),gear:Object.fromEntries(['weapon','cape','charm'].map(sl=>{const it=h.eq&&h.eq[sl];return [sl,it?{id:it.id,rank:it.rank||0,lvl:it.lvl||0}:null];}))})),drops:Object.fromEntries(Object.entries(M.drops).map(([k,v])=>[k,{common:v[0],uncommon:v[1],rare:v[2],epic:v[3],legendary:v[4],mythic:v[5]}])),catacombs:{best:Math.max(M.delve.best,G.delveBest||0),runs:M.delve.runs},endless:{best:Math.max(M.endless.best,(G.far||[])[Z.length-1]||0),milestones:Math.floor(Math.max(M.endless.best,(G.far||[])[Z.length-1]||0)/25)},stuck:M.stuck,hourly:M.gold};
    if(args.json)require('fs').writeFileSync(args.json,JSON.stringify(out,null,1));
    console.log('\n=== SUMMARY ('+out.simHours+'h simulated, seed '+SEED+') ===');
    console.log('final: '+JSON.stringify(out.final));
    console.log('recruits (h): '+JSON.stringify(out.recruits));
    console.log('zones cleared (h): '+JSON.stringify(out.zonesCleared));
    console.log('promotions (h): '+JSON.stringify(out.promotions));
    console.log('talents (h): '+JSON.stringify(out.talents));
    console.log('shatters: '+JSON.stringify(out.shatters));
    console.log('boss fail rates: '+JSON.stringify(out.bossFailRates));
    console.log('active window: '+JSON.stringify(out.dmgActiveWindow));
    console.log('damage share: '+JSON.stringify(out.dmgShare)+'  dmg/h: '+JSON.stringify(out.dmgPerHour)+'  casts/h: '+out.castsPerHour+'  econ/h: '+JSON.stringify(out.econPerHour));
    console.log('firsts: '+JSON.stringify(out.firsts));
    console.log('drops by zone: '+JSON.stringify(out.drops));
    console.log('catacombs: '+JSON.stringify(out.catacombs)+'  endless: '+JSON.stringify(out.endless));
    if(SCHEDULE)console.log('schedule: played '+out.playHours+'h, offline '+out.offlineHours+'h in '+out.offline.length+' breaks; drills '+JSON.stringify(out.drills)+'; boosts '+JSON.stringify(out.boosts));
    if(out.stuck.length)console.log('stuck: '+JSON.stringify(out.stuck));
    process.exit(0);
  }
}
