// Bounded-growth checks for a candidate batch (the human's shipping criteria of 2026-09-15, replacing "within 3x of the reference").
// Reads one batch directory (2x is the reference speed; 4x is the labelled upper bound) and prints PASS/FAIL per check, per profile:
//   1. Shatter 8 does not occur before 48 h            5. Endless wave gain in hours 72-96 is lower than in hours 48-72
//   2. Shatter 10 is not reached within 96 h           6. no boss softlocks (a Road boss never cleared after >= 3 attempts, or a fail streak >= 8) and a usable ore economy
//   3. gear: recorded only since the level cap was removed   (at least one ascension per run and ore spent > 0 in the last 24 h)
//      on 2026-09-16 (item level and rank at the end)       //   7a. at 2x, engaged enters Endless 5-12% earlier than boosted idle in WALL hours; 7b. 15-30% earlier in PLAYED hours (rows carry `played` under a schedule); at 4x both are recorded only (upper bound)
//   4. power growth in the final 24 h is no more than 80% of the previous 24 h (log-growth ratio <= 0.8; human 2026-09-16, real-player schedule)
// Also prints the record values: 1T gold arrival (the human accepts about 35-40 h at 2x), Shatter hours, power and wave series, assertion failures.
// Usage: node tests/sim/bounded.js --dir batch_out_p46x2 [--profiles idleboost,light,casual,engaged] [--seedStart 81] [--seeds 10] [--schedule "2:2,2:8,2:8" for batches whose rows lack played hours]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const DIR=path.join(__dirname,String(args.dir||'')),P=String(args.profiles||'idleboost,light,casual,engaged').split(','),S0=Number(args.seedStart||81),N=Number(args.seeds||10);
if(!args.dir||!fs.existsSync(DIR)){console.log('BOUNDED FAIL: --dir <batch directory> is required');process.exit(1);}
const med=a=>{a=a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y);return a.length?a[Math.floor((a.length-1)/2)]:null;};const f=(v,d=1)=>v==null?'-':(+v).toFixed(d);
const load=p=>{const o=[];for(let s=S0;s<S0+N;s++){const fp=path.join(DIR,p+'_'+s+'.json');if(fs.existsSync(fp))o.push(JSON.parse(fs.readFileSync(fp,'utf8')));}return o;};
const at=(r,h)=>r.hourly.filter(x=>x.h<=h).pop()||{};
const endIn=r=>{const e=Object.values(r.runZones||{}).map(z=>z['The Endless Road']&&z['The Endless Road'].enterH).filter(x=>x!=null);return e.length?Math.min(...e):null;};
const t1=r=>{const x=r.hourly.find(x=>x.earnedGold>=1e12);return x?x.h:null;};
const R={};for(const p of P)R[p]=load(p);
let fails=0;const say=(okv,msg)=>{console.log('  '+(okv?'PASS ':'FAIL ')+msg);if(!okv)fails++;};
console.log('bounded-growth checks: '+path.basename(DIR)+'  profiles '+P.join('/')+'  seeds '+S0+'-'+(S0+N-1));
{const sig=r=>{const c=r.config||{};return JSON.stringify({commit:c.commit,dirty:c.dirty,replaced:c.replaced,gameHash:c.gameHash,harnessHash:c.harnessHash,speed:c.speed,speed4Buys:c.speed4Buys,shatters:c.shatters,hours:c.hours,dt:c.dt,schedule:c.schedule,drills:c.drills,double:c.double,boosts:c.boosts,clericBack:c.clericBack,retreatAfter:c.retreatAfter,retreatOn:c.retreatOn,trainUntil:c.trainUntil,stallRule:c.stallRule,stallHours:c.stallHours,noAutoTrain:c.noAutoTrain,bossHp:c.bossHp,bossAtk:c.bossAtk});};const all=P.flatMap(p=>R[p]);const sigs=new Set(all.map(sig));const dirty=all.filter(r=>r.config&&r.config.dirty&&r.config.dirty.length);console.log('\n== configuration binding');say(sigs.size===1,'one behavioural configuration across '+all.length+' runs ('+sigs.size+' distinct)'+(sigs.size===1?': '+[...sigs][0]:''));say(dirty.length===0,'clean source tree at run time ('+dirty.length+' runs from a dirty tree'+(dirty.length?': '+JSON.stringify(dirty[0].config.dirty):'')+')');const prof=all.map(r=>r.profile+':'+r.config.taps+'/'+r.config.activeMin+'/'+r.config.boost);console.log('  INFO profiles (taps/activeMin/boost): '+[...new Set(prof)].join(', '));}
for(const p of P){const rs=R[p];if(!rs.length){console.log('\n== '+p+': no runs');fails++;continue;}
  const cfg=rs[0].config||{};console.log('\n== '+p+' (n='+rs.length+', speed '+cfg.speed+', commit '+String(cfg.commit||'').slice(0,10)+', game '+cfg.gameHash+')');
  const af=rs.filter(r=>r.assertFail).length;say(af===0,'assertion failures: '+af);
  const sh8=med(rs.map(r=>r.shatters[7]?r.shatters[7].h:null)),n8=rs.filter(r=>r.shatters[7]&&r.shatters[7].h<48).length;say(n8===0,'1. Shatter 8 before 48 h in '+n8+' of '+rs.length+' runs (median hour '+f(sh8)+', Shatter hours seed '+S0+': '+rs[0].shatters.map(s=>f(s.h,1)).join(', ')+')');
  const n10=rs.filter(r=>r.shatters.length>=10).length;say(n10===0,'2. Shatter 10 reached within 96 h in '+n10+' of '+rs.length+' runs (median Shatters '+f(med(rs.map(r=>r.shatters.length)),0)+')');
  console.log('  INFO 3. gear (no level cap since 2026-09-16, recorded only): item level at the end '+f(med(rs.map(r=>at(r,96).itemLvl)),0)+', rank '+f(med(rs.map(r=>at(r,96).itemRank)),2)+'; ascensions per run '+f(med(rs.map(r=>(r.ascensions||[]).length)),0));
  const lg=(r,a,b)=>Math.log10(Math.max(1,at(r,b).power))-Math.log10(Math.max(1,at(r,a).power));const g1=med(rs.map(r=>lg(r,48,72))),g2=med(rs.map(r=>lg(r,72,96)));say(g2<=0.8*g1,'4. power growth 72-96 h vs 48-72 h: x'+f(Math.pow(10,g2),2)+' vs x'+f(Math.pow(10,g1),2)+' (ratio of log growth '+f(g1?g2/g1:0,2)+', want <= 0.8)');
  const wv=(r,a,b)=>(at(r,b).bestWave||0)-(at(r,a).bestWave||0);const w1=med(rs.map(r=>wv(r,48,72))),w2=med(rs.map(r=>wv(r,72,96)));say(w2<w1,'5. Endless waves gained 72-96 h '+f(w2,0)+' < 48-72 h '+f(w1,0)+' (best wave at 96 h '+f(med(rs.map(r=>at(r,96).bestWave||0)),0)+')');
  const soft=rs.map(r=>Object.entries(r.bossFailRates||{}).filter(([z,b])=>z!=='The Endless Road'&&b.attempts>=3&&r.zonesCleared[z]==null).map(([z])=>z)).flat(); /* softlock: a Road boss attempted three times and never cleared in any run; Endless milestone bosses are not clears */const walls=rs.map(r=>Object.entries(r.bossFailRates||{}).filter(([z,b])=>z!=='The Endless Road'&&b.maxStreak>=8).map(([z,b])=>z+' x'+b.maxStreak)).flat();const asc=med(rs.map(r=>(r.ascensions||[]).length)),oreLate=med(rs.map(r=>at(r,96).spentOre-at(r,72).spentOre));say(soft.length===0&&asc>=1&&oreLate>0,'6. boss softlocks '+soft.length+(soft.length?' ('+[...new Set(soft)].join(', ')+')':'')+'; ascensions per run '+f(asc,0)+'; ore spent in the last 24 h '+f(oreLate/1e6,1)+'M'+(walls.length?'  [walls, loss streak >= 8 but cleared: '+walls.length+' in '+rs.length+' runs, e.g. '+walls[0]+']':''));
  {const dsh=med(rs.map(r=>r.shatters.reduce((a,s)=>a+(s.gain||0),0))),ddr=med(rs.map(r=>(r.drills&&r.drills.dust)||0)),share=dsh+ddr>0?100*ddr/(dsh+ddr):0;const f2=(r,k)=>r.drills&&r.drills[k]?r.drills[k]:null;const fc=med(rs.map(r=>{const x=f2(r,'first');return x?x.zone.dust+x.endless.dust:null;})),rc=med(rs.map(r=>{const x=f2(r,'repeat');return x?x.zone.dust+x.endless.dust:null;}));if(rs[0].config&&rs[0].config.drills)say(share<20,'8. drill dust '+f(ddr,0)+' vs Shatter dust '+f(dsh,0)+' per run: '+f(share,1)+'% of all dust (want < 20%); first-cycle claims '+f(fc,0)+' dust, repeat claims '+f(rc,0)+' dust');else console.log('  INFO 8. drills off in this batch');}
  console.log('  record: 1T gold at h '+f(med(rs.map(t1)),0)+' ('+rs.filter(r=>t1(r)!=null).length+'/'+rs.length+' runs); Endless entered '+f(med(rs.map(endIn)),1)+' h; power 24/48/72/96 h '+[24,48,72,96].map(h=>f(med(rs.map(r=>at(r,h).power))/1e9,2)+'B').join(' / ')+'; waves '+[24,48,72,96].map(h=>f(med(rs.map(r=>at(r,h).bestWave||0)),0)).join(' / ')+'; level at 96 h '+f(med(rs.map(r=>at(r,96).lv)),0)+'; defeats '+f(med(rs.map(r=>r.final.defeats)),0));}
if(R.idleboost&&R.engaged&&R.idleboost.length&&R.engaged.length){const SCH=args.schedule?String(args.schedule).split(',').map(x=>{const [pl,of]=x.split(':').map(Number);return{play:pl,off:of||0};}):null;const playedFromWall=h=>{if(!SCH)return h;let wall=0,played=0,i=0;for(;;){const b=SCH[i%SCH.length];if(h<=wall+b.play)return played+(h-wall);played+=b.play;wall+=b.play;if(h<=wall+b.off)return played;wall+=b.off;i++;if(i>10000)return played;}};const playedAt=(r,h)=>{if(h==null)return null;const row=r.hourly.filter(x=>x.h<=h).pop();return row&&row.played!=null?row.played+(h-row.h):playedFromWall(h);}; /* rows carry played hours under a schedule; older batches fall back to --schedule "2:2,2:8,2:8" */const a=med(R.idleboost.map(endIn)),b=med(R.engaged.map(endIn)),adv=100*(1-b/a);const ap=med(R.idleboost.map(r=>playedAt(r,endIn(r)))),bp=med(R.engaged.map(r=>playedAt(r,endIn(r)))),advP=100*(1-bp/ap);const sp=(R.engaged[0].config||{}).speed;console.log('\n== interaction');if(sp===2){say(adv>=5&&adv<=12,'7a. engaged ahead of boosted idle on Endless entry by '+f(adv,1)+'% in wall hours ('+f(b,1)+' vs '+f(a,1)+' h; want 5-12% at 2x)');say(advP>=15&&advP<=30,'7b. engaged ahead by '+f(advP,1)+'% in played hours ('+f(bp,1)+' vs '+f(ap,1)+' h; want 15-30%)');}else{console.log('  INFO 7. at '+sp+'x (upper bound, recorded only): engaged ahead on Endless entry by '+f(adv,1)+'% wall ('+f(b,1)+' vs '+f(a,1)+' h), '+f(advP,1)+'% played ('+f(bp,1)+' vs '+f(ap,1)+' h)');}}
else{console.log('\n== interaction: needs both idleboost and engaged in the batch');fails++;}
console.log(fails?'\nBOUNDED FAIL ('+fails+' checks)':'\nBOUNDED PASS');process.exit(fails?1:0);
