// Compare two batch output folders (paired seeds) side by side: node tests/sim/compare.js --a batch_out_p8c --b batch_out_p8x [--profiles idle,casual,engaged] [--labels control,candidate]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const P=String(args.profiles||'idle,casual,engaged').split(','),[LA,LB]=String(args.labels||'control,candidate').split(',');
const load=d=>{const dir=path.join(__dirname,d);const R={};for(const p of P)R[p]=fs.readdirSync(dir).filter(f=>f.startsWith(p+'_')&&f.endsWith('.json')).sort((x,y)=>Number(x.match(/_(\d+)/)[1])-Number(y.match(/_(\d+)/)[1])).map(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8')));return R;};
const A=load(args.a),B=load(args.b);
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y);const med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null;};const p90=a=>{a=srt(a);return a.length?a[Math.min(a.length-1,Math.ceil((a.length-1)*0.9))]:null;};const mean=a=>{a=srt(a);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null;};
const f=(v,d=2)=>v==null?'-':String(+(+v).toFixed(d));
const zones=['Greenhollow Fields','Stillwater Lagoon','Thornwood','Ironvein Caverns','Emberwaste','Amberfall Woods','Ashen Approach','Ashen Keep','The Foundry'];const FIGHTS=[24,30,30,36,36,36,36,40,40];
const at=r=>r.autoTrain||{triggers:0,returns:0,cancels:0,timeSec:0,log:[]};
const medOf=a=>med(a);
const rows=[];
function row(name,fn,dec=2,agg='med'){const line={name,cells:[]};for(const p of P){const va=A[p].map(fn),vb=B[p].map(fn);const g=agg==='mean'?(x=>{const m=mean(x);return m==null?null:Math.round(100*m);}):med;const ga=g(va),gb=g(vb);const pa=agg==='mean'?null:p90(va),pb=agg==='mean'?null:p90(vb);let d='';if(ga!=null&&gb!=null&&ga!==0)d=' ('+(gb>ga?'+':'')+Math.round(100*(gb-ga)/Math.abs(ga))+'%)';line.cells.push((agg==='mean'?f(ga,0)+'%':f(ga,dec)+' / '+f(pa,dec))+' -> '+(agg==='mean'?f(gb,0)+'%':f(gb,dec)+' / '+f(pb,dec))+d);}rows.push(line);}
function section(t){rows.push({name:'-- '+t,cells:P.map(()=>'')});}
section('AUTO TRAINING (24h)   med / P90   '+LA+' -> '+LB);
row('triggers',r=>at(r).triggers,0);row('completed returns',r=>at(r).returns,0);row('cancelled (build change)',r=>at(r).cancels,0);
row('training hours',r=>at(r).timeSec/3600,1);row('training share of 24h %',r=>100*at(r).timeSec/3600/24,0);row('levels earned training',r=>at(r).xp,1);
for(const z of zones.slice(1,6))row('triggers for '+z,r=>at(r).log.filter(l=>l.ret===z).length,0);
section('RETRIGGERS (same zone after a completed return)');
row('retriggers within 10 fresh fights',r=>at(r).log.filter(l=>l.retrigger&&l.retrigger.fights<=10).length,0);
row('retriggers within 20 fresh fights',r=>at(r).log.filter(l=>l.retrigger&&l.retrigger.fights<=20).length,0);
row('share of triggers that are retriggers <=20 %',r=>{const L=at(r).log;return L.length?100*L.filter(l=>l.retrigger&&l.retrigger.fights<=20).length/L.length:null;},0);
row('fresh fights to retrigger (med of run medians)',r=>medOf(at(r).log.filter(l=>l.retrigger).map(l=>l.retrigger.fights)),0);
row('minutes to retrigger (med of run medians)',r=>medOf(at(r).log.filter(l=>l.retrigger).map(l=>l.retrigger.minutes)),0);
row('win% first 10 fights after return',r=>{const v=medOf(at(r).log.filter(l=>l.winAfter!=null).map(l=>l.winAfter));return v==null?null:100*v;},0);
row('win% first 20 fights after return',r=>{const v=medOf(at(r).log.filter(l=>l.winAfter20!=null).map(l=>l.winAfter20));return v==null?null:100*v;},0);
row('win% in window at trigger',r=>{const v=medOf(at(r).log.filter(l=>l.window).map(l=>l.window.split('').filter(c=>c==='1').length/l.window.length));return v==null?null:100*v;},0);
row('enemy Lv minus party Lv at trigger',r=>medOf(at(r).log.filter(l=>l.enemyLv!=null).map(l=>l.enemyLv-l.lvBefore)),1);
row('zone progress % at trigger',r=>medOf(at(r).log.filter(l=>l.prog!=null).map(l=>100*l.prog/FIGHTS[zones.indexOf(l.ret)])),0);
section('DEAD TIME outside training');
row('ordinary defeats outside training',r=>r.deadTime&&r.deadTime.defeatsOutsideTraining,0);
row('rewalk fights (ordinary defeats)',r=>r.deadTime&&r.deadTime.rewalkFights,0);
row('rewalk fights (boss losses)',r=>r.deadTime&&r.deadTime.rewalkBossFights,0);
row('rewalk hours equiv (ordinary)',r=>r.deadTime&&r.deadTime.rewalkFights*r.deadTime.secPerEncounter/3600,2);
row('rewalk hours equiv (boss)',r=>r.deadTime&&r.deadTime.rewalkBossFights*r.deadTime.secPerEncounter/3600,2);
row('total defeats in 24h',r=>r.final.defeats,0);
section('STILLWATER');
row('first-try clear (mean)',r=>r.bossFailRates['Stillwater Lagoon']?r.bossFailRates['Stillwater Lagoon'].firstTryClear:null,0,'mean');
row('attempts to clear',r=>r.bossFailRates['Stillwater Lagoon']&&r.bossFailRates['Stillwater Lagoon'].attemptsToClear,0);
row('stall h',r=>r.bossFailRates['Stillwater Lagoon']&&r.bossFailRates['Stillwater Lagoon'].stallH,2);
row('zone clear h',r=>r.zonesCleared['Stillwater Lagoon'],2);
row('Lv at first try',r=>r.bossFailRates['Stillwater Lagoon']&&r.bossFailRates['Stillwater Lagoon'].lvFirst,1);
section('IRONVEIN');
row('first-try clear (mean)',r=>r.bossFailRates['Ironvein Caverns']?r.bossFailRates['Ironvein Caverns'].firstTryClear:null,0,'mean');
row('attempts to clear',r=>r.bossFailRates['Ironvein Caverns']&&r.bossFailRates['Ironvein Caverns'].attemptsToClear,0);
row('stall h',r=>r.bossFailRates['Ironvein Caverns']&&r.bossFailRates['Ironvein Caverns'].stallH,2);
row('zone clear h',r=>r.zonesCleared['Ironvein Caverns'],2);
row('Lv entering zone',r=>r.zoneRec['Ironvein Caverns']&&r.zoneRec['Ironvein Caverns'].lvAtEntry,1);
row('Lv at first try',r=>r.bossFailRates['Ironvein Caverns']&&r.bossFailRates['Ironvein Caverns'].lvFirst,1);
section('EARLY ROAD CLEAR TIMES (h)');
for(const z of zones.slice(1,5))row(z,r=>r.zonesCleared[z],2);
row('zones cleared @24h',r=>Object.keys(r.zonesCleared).length,0);
row('party Lv @24h',r=>r.final.partyLv,0);
const w=Math.max(...rows.map(r=>r.name.length))+1;const cw=Math.max(...rows.flatMap(r=>r.cells.map(c=>c.length)))+2;
console.log(''.padEnd(w)+P.map(p=>p.padEnd(cw)).join(''));for(const r of rows)console.log(r.name.padEnd(w)+r.cells.map(c=>c.padEnd(cw)).join(''));
