// Compare two batch output folders (paired seeds) side by side: node tests/sim/compare.js --a batch_out_p8c --b batch_out_p8x [--profiles idle,casual,engaged] [--labels control,candidate]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const P=String(args.profiles||'idle,casual,engaged').split(','),[LA,LB]=String(args.labels||'control,candidate').split(',');
const load=d=>{const dir=path.join(__dirname,d);const R={};for(const p of P)R[p]=fs.readdirSync(dir).filter(f=>f.startsWith(p+'_')&&f.endsWith('.json')).sort((x,y)=>Number(x.match(/_(\d+)/)[1])-Number(y.match(/_(\d+)/)[1])).map(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8')));return R;};
const A=load(args.a),B=load(args.b);
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y);const med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null;};const p90=a=>{a=srt(a);return a.length?a[Math.min(a.length-1,Math.ceil((a.length-1)*0.9))]:null;};const mean=a=>{a=srt(a);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null;};
const f=(v,d=2)=>v==null?'-':String(+(+v).toFixed(d));
const zones=['Greenhollow Fields','Stillwater Lagoon','Thornwood','Ironvein Caverns','Emberwaste','Amberfall Woods','Ashen Approach','Ashen Keep','The Foundry'];const FIGHTS=[24,30,30,36,36,36,36,40,40];
const at=r=>r.autoTrain||{triggers:0,returns:0,cancels:0,timeSec:0,log:[]};
const medOf=a=>med(a);
const rows=[];
function row(name,fn,dec=2,agg='med'){const line={name,cells:[]};for(const p of P){const va=A[p].map(fn),vb=B[p].map(fn);const g=agg==='mean'?(x=>{const m=mean(x);return m==null?null:Math.round(100*m);}):med;const ga=g(va),gb=g(vb);const pa=agg==='mean'?null:p90(va),pb=agg==='mean'?null:p90(vb);let d='';if(ga!=null&&gb!=null&&ga!==0)d=' ('+(gb>ga?'+':'')+Math.round(100*(gb-ga)/Math.abs(ga))+'%)';line.cells.push((agg==='mean'?f(ga,0)+'%':f(ga,dec)+' / '+f(pa,dec))+' -> '+(agg==='mean'?f(gb,0)+'%':f(gb,dec)+' / '+f(pb,dec))+d);}rows.push(line);}
function section(t){rows.push({name:'-- '+t,cells:P.map(()=>'')});}
section('AUTO TRAINING (24h)   med / P90   '+LA+' -> '+LB);
row('triggers',r=>at(r).triggers,0);row('completed returns',r=>at(r).returns,0);row('cancelled (build change)',r=>at(r).cancels,0);
row('training hours',r=>at(r).timeSec/3600,1);row('training share of 24h %',r=>100*at(r).timeSec/3600/24,0);row('levels earned training',r=>at(r).xp,1);
for(const z of zones.slice(1,6))row('triggers for '+z,r=>at(r).log.filter(l=>l.ret===z).length,0);
row('trainings with +1 target',r=>at(r).log.filter(l=>(l.target||1)===1).length,0);row('trainings with +2 target',r=>at(r).log.filter(l=>(l.target||1)===2).length,0);
for(const z of zones.slice(1,6))row('  +2 trainings for '+z,r=>at(r).log.filter(l=>l.ret===z&&(l.target||1)===2).length,0);
row('training fights total',r=>at(r).fights,0);row('back-to-back +2 in same zone (max run)',r=>{let best=0;for(const z of zones){let run=0;for(const l of at(r).log.filter(l=>l.ret===z)){if((l.target||1)===2){run++;best=Math.max(best,run);}else run=0;}}return best;},0);
section('RETRIGGERS (same zone after a completed return)');
row('retriggers within 10 ordinary fights',r=>at(r).log.filter(l=>l.retrigger&&l.retrigger.fights>=1&&l.retrigger.fights<=10).length,0);
row('retriggers within 20 ordinary fights',r=>at(r).log.filter(l=>l.retrigger&&l.retrigger.fights>=1&&l.retrigger.fights<=20).length,0);
row('retriggers exactly on ordinary fight 20',r=>at(r).log.filter(l=>l.retrigger&&l.retrigger.fights===20).length,0);
row('quick-classified triggers (game)',r=>at(r).log.filter(l=>l.quick).length,0);
row('share of triggers that are retriggers <=20 %',r=>{const L=at(r).log;return L.length?100*L.filter(l=>l.retrigger&&l.retrigger.fights<=20).length/L.length:null;},0);
row('fresh fights to retrigger (med of run medians)',r=>medOf(at(r).log.filter(l=>l.retrigger).map(l=>l.retrigger.fights)),0);
row('minutes to retrigger (med of run medians)',r=>medOf(at(r).log.filter(l=>l.retrigger).map(l=>l.retrigger.minutes)),0);
row('win% first 10 fights after return',r=>{const v=medOf(at(r).log.filter(l=>l.winAfter!=null).map(l=>l.winAfter));return v==null?null:100*v;},0);
row('win% first 20 fights after return',r=>{const v=medOf(at(r).log.filter(l=>l.winAfter20!=null).map(l=>l.winAfter20));return v==null?null:100*v;},0);
row('win% in window at trigger',r=>{const v=medOf(at(r).log.filter(l=>l.window).map(l=>l.window.split('').filter(c=>c==='1').length/l.window.length));return v==null?null:100*v;},0);
row('enemy Lv minus party Lv at trigger',r=>medOf(at(r).log.filter(l=>l.enemyLv!=null).map(l=>l.enemyLv-l.lvBefore)),1);
row('pre-rollback loss position % of zone at trigger',r=>medOf(at(r).log.filter(l=>l.lossProg!=null).map(l=>100*l.lossProg/FIGHTS[zones.indexOf(l.ret)])),0);
row('checkpoint % of zone after rollback',r=>medOf(at(r).log.filter(l=>l.prog!=null).map(l=>100*l.prog/FIGHTS[zones.indexOf(l.ret)])),0);
section('DEAD TIME outside training');
row('ordinary defeats outside training',r=>r.deadTime&&r.deadTime.defeatsOutsideTraining,0);
row('rewalk fights (ordinary defeats)',r=>r.deadTime&&r.deadTime.rewalkFights,0);
row('rewalk fights (boss losses)',r=>r.deadTime&&r.deadTime.rewalkBossFights,0);
row('rewalk hours equiv (ordinary)',r=>r.deadTime&&r.deadTime.rewalkFights*r.deadTime.secPerEncounter/3600,2);
row('rewalk hours equiv (boss)',r=>r.deadTime&&r.deadTime.rewalkBossFights*r.deadTime.secPerEncounter/3600,2);
row('total defeats in 24h',r=>r.final.defeats,0);
section('STILLWATER');
row('first-try clear (mean)',r=>r.bossFailRates['Stillwater Lagoon']?r.bossFailRates['Stillwater Lagoon'].firstTryClear:null,0,'mean');
row('attempts to clear',r=>r.bossFailRates['Stillwater Lagoon']&&r.bossFailRates['Stillwater Lagoon'].attemptsToClear,0);
row('stall h',r=>r.bossFailRates['Stillwater Lagoon']&&r.bossFailRates['Stillwater Lagoon'].stallH,2);
row('zone clear h',r=>r.zonesCleared['Stillwater Lagoon'],2);
row('Lv at first try',r=>r.bossFailRates['Stillwater Lagoon']&&r.bossFailRates['Stillwater Lagoon'].lvFirst,1);
section('IRONVEIN');
row('first-try clear (mean)',r=>r.bossFailRates['Ironvein Caverns']?r.bossFailRates['Ironvein Caverns'].firstTryClear:null,0,'mean');
row('attempts to clear',r=>r.bossFailRates['Ironvein Caverns']&&r.bossFailRates['Ironvein Caverns'].attemptsToClear,0);
row('stall h',r=>r.bossFailRates['Ironvein Caverns']&&r.bossFailRates['Ironvein Caverns'].stallH,2);
row('zone clear h',r=>r.zonesCleared['Ironvein Caverns'],2);
row('Lv entering zone',r=>r.zoneRec['Ironvein Caverns']&&r.zoneRec['Ironvein Caverns'].lvAtEntry,1);
row('Lv at first try',r=>r.bossFailRates['Ironvein Caverns']&&r.bossFailRates['Ironvein Caverns'].lvFirst,1);
section('IRONVEIN ATTEMPTS (attempt-level, all attempts)');
const IV='Ironvein Caverns';const att=r=>(r.bossFailRates[IV]&&r.bossFailRates[IV].attemptLog)||[];
row('Warlord ATK at first attempt (audit)',r=>{const a=att(r)[0];return a?a.bossAtk:null;},0);
row('Warlord Lv at first attempt',r=>{const a=att(r)[0];return a?a.bossLv:null;},0);
row('attempts per run',r=>att(r).length,0);
row('first attempt in active window (1=yes)',r=>{const a=att(r)[0];return a?(a.window==='active'?1:0):null;},0,'mean');
row('first attempt party HP %',r=>{const a=att(r)[0];return a?Math.round(a.hp*100):null;},0);
row('first attempt charge / surge',r=>{const a=att(r)[0];return a?a.charge:null;},0);
row('first attempt power',r=>{const a=att(r)[0];return a?a.power:null;},0);
row('active-window attempts: win % (pooled)',r=>{const x=att(r).filter(a=>a.window==='active'&&a.win!=null);return x.length?x.filter(a=>a.win).length/x.length:null;},0,'mean');
row('Auto-Cast attempts: win % (pooled)',r=>{const x=att(r).filter(a=>a.window==='auto'&&a.win!=null);return x.length?x.filter(a=>a.win).length/x.length:null;},0,'mean');
row('Auto-Cast attempts per run',r=>att(r).filter(a=>a.window==='auto').length,0);
row('charge telegraphs per attempt (run mean)',r=>{const x=att(r).filter(a=>a.telegraphs!=null);return x.length?x.reduce((q,a)=>q+a.telegraphs,0)/x.length:null;},2);
row('charge hits per attempt',r=>{const x=att(r).filter(a=>a.chargeHits!=null);return x.length?x.reduce((q,a)=>q+a.chargeHits,0)/x.length:null;},2);
row('charge kills per attempt',r=>{const x=att(r).filter(a=>a.chargeKills!=null);return x.length?x.reduce((q,a)=>q+a.chargeKills,0)/x.length:null;},2);
row('parries + interrupts per attempt',r=>{const x=att(r).filter(a=>a.parried!=null);return x.length?x.reduce((q,a)=>q+a.parried+a.interrupted,0)/x.length:null;},2);
row('boss ordinary hits on heroes per attempt',r=>{const x=att(r).filter(a=>a.bossHits!=null);return x.length?x.reduce((q,a)=>q+a.bossHits,0)/x.length:null;},1);
row('LOSS boss HP left (run median)',r=>{const x=att(r).filter(a=>a.win===false&&a.hpLeft!=null).map(a=>a.hpLeft);return x.length?100*medOf(x):null;},0);
row('LOSS reached summon % (pooled)',r=>{const x=att(r).filter(a=>a.win===false&&a.summoned!=null);return x.length?x.filter(a=>a.summoned).length/x.length:null;},0,'mean');
row('WIN survivors (run median)',r=>{const x=att(r).filter(a=>a.win===true&&a.survivors!=null).map(a=>a.survivors);return x.length?medOf(x):null;},0);
row('WIN party HP % (run median)',r=>{const x=att(r).filter(a=>a.win===true&&a.partyHp!=null).map(a=>a.partyHp);return x.length?100*medOf(x):null;},0);
section('OTHER BOSSES first-try % (mean) / attempts med');
for(const z of ['Stillwater Lagoon','Thornwood','Emberwaste','Amberfall Woods','Ashen Approach']){row(z+' first-try %',r=>r.bossFailRates[z]?r.bossFailRates[z].firstTryClear:null,0,'mean');row(z+' attempts',r=>r.bossFailRates[z]&&r.bossFailRates[z].attemptsToClear,0);row(z+' stall h',r=>r.bossFailRates[z]&&r.bossFailRates[z].stallH,2);}
section('HORDES / CATACOMBS / DAMAGE');
row('hordes fought (manual)',r=>r.hordes?r.hordes.fought:null,0);row('hordes repelled',r=>r.hordes?r.hordes.repelled:null,0);row('hordes lost',r=>r.hordes?r.hordes.lost:null,0);
row('catacomb best floor',r=>r.catacombs?r.catacombs.best:null,0);row('catacomb runs',r=>r.catacombs?r.catacombs.runs:null,0);
row('ability casts / h',r=>r.castsPerHour,0);row('dmg share basic %',r=>100*r.dmgShare.basic,0);row('dmg share ability %',r=>100*r.dmgShare.ability,0);row('dmg share tap %',r=>100*r.dmgShare.tap,0);row('dmg share surge %',r=>100*r.dmgShare.surge,0);
section('PAIRED PER-SEED DELTAS (candidate minus control): median delta | +/0/- counts');
function paired(name,fn,dec=2){const line={name,cells:[]};for(const p of P){const A2=A[p],B2=B[p];const bySeed=new Map(B2.map(r=>[r.config.seed,r]));const d=[];for(const ra of A2){const rb=bySeed.get(ra.config.seed);if(!rb)continue;const va=fn(ra),vb=fn(rb);if(va==null||vb==null)continue;d.push(vb-va);}const pos=d.filter(x=>x>0).length,zero=d.filter(x=>x===0).length,neg=d.filter(x=>x<0).length;line.cells.push(d.length?f(med(d),dec)+' | +'+pos+' 0'+zero+' -'+neg+' (n'+d.length+')':'-');}rows.push(line);}
paired('Ironvein attempts',r=>r.bossFailRates[IV]&&r.bossFailRates[IV].attemptsToClear,0);
paired('Ironvein stall h',r=>r.bossFailRates[IV]&&r.bossFailRates[IV].stallH,2);
paired('Ironvein clear h',r=>r.zonesCleared[IV],2);
paired('zones cleared @24h',r=>Object.keys(r.zonesCleared).length,0);
paired('zones cleared @20h',r=>Object.values(r.zonesCleared).filter(t=>t<=20).length,0);
paired('ordinary rewalk fights',r=>r.deadTime&&r.deadTime.rewalkFights,0);
paired('ordinary rewalk hours',r=>r.deadTime&&r.deadTime.rewalkFights*r.deadTime.secPerEncounter/3600,2);
paired('total defeats',r=>r.final.defeats,0);
section('COUNTS WITH DENOMINATORS');
function counts(name,fn){const line={name,cells:[]};for(const p of P){const ca=fn(A[p]),cb=fn(B[p]);line.cells.push(ca+' -> '+cb);}rows.push(line);}
counts('Ironvein first-try clears / runs',rs=>{const x=rs.map(r=>r.bossFailRates[IV]).filter(b=>b&&b.firstTryClear!=null);return x.filter(b=>b.firstTryClear).length+'/'+x.length;});
counts('Auto-Cast attempts: wins / attempts',rs=>{const x=rs.flatMap(r=>att(r)).filter(a=>a.window==='auto'&&a.win!=null);return x.filter(a=>a.win).length+'/'+x.length;});
counts('active-window attempts: wins / attempts',rs=>{const x=rs.flatMap(r=>att(r)).filter(a=>a.window==='active'&&a.win!=null);return x.filter(a=>a.win).length+'/'+x.length;});
counts('runs reaching a 6th zone by 24h / runs',rs=>rs.filter(r=>Object.keys(r.zonesCleared).length>=6).length+'/'+rs.length);
counts('6th-zone clear h (med of those reaching)',rs=>{const t=rs.map(r=>{const v=Object.values(r.zonesCleared).sort((a,b)=>a-b);return v[5];}).filter(v=>v!=null);return t.length?f(med(t),2):'-';});
counts('zones cleared @20h (med)',rs=>f(med(rs.map(r=>Object.values(r.zonesCleared).filter(t=>t<=20).length)),0));
section('FIRST ATTEMPT DETAIL (run medians; loss boss HP left where lost)');
row('first attempt: won (mean)',r=>{const a=att(r)[0];return a&&a.win!=null?(a.win?1:0):null;},0,'mean');
row('first attempt: boss HP left on loss %',r=>{const a=att(r)[0];return a&&a.win===false&&a.hpLeft!=null?100*a.hpLeft:null;},0);
row('first attempt: party Lv',r=>{const a=att(r)[0];return a?a.lv:null;},1);
row('first attempt: party HP %',r=>{const a=att(r)[0];return a?100*a.hp:null;},0);
row('first attempt: charge',r=>{const a=att(r)[0];return a?a.charge:null;},0);
row('first attempt: Surge',r=>{const a=att(r)[0];return a?a.surge:null;},0);
row('first attempt: boss ordinary hits',r=>{const a=att(r)[0];return a&&a.bossHits!=null?a.bossHits:null;},0);
row('first attempt: charge telegraphs / hits / kills',r=>{const a=att(r)[0];return a&&a.chargeHits!=null?a.chargeHits:null;},0);
row('first attempt: charge kills',r=>{const a=att(r)[0];return a&&a.chargeKills!=null?a.chargeKills:null;},0);
row('first attempt: reached summon on loss (mean)',r=>{const a=att(r)[0];return a&&a.win===false&&a.summoned!=null?(a.summoned?1:0):null;},0,'mean');
section('EARLY ROAD CLEAR TIMES (h)');
for(const z of zones.slice(1,5))row(z,r=>r.zonesCleared[z],2);
row('zones cleared @24h',r=>Object.keys(r.zonesCleared).length,0);
row('party Lv @24h',r=>r.final.partyLv,0);
const w=Math.max(...rows.map(r=>r.name.length))+1;const cw=Math.max(...rows.flatMap(r=>r.cells.map(c=>c.length)))+2;
console.log(''.padEnd(w)+P.map(p=>p.padEnd(cw)).join(''));for(const r of rows)console.log(r.name.padEnd(w)+r.cells.map(c=>c.padEnd(cw)).join(''));
