// Drill bench: the production Training Drill scored on saved game states, one observation per run per bracket.
//   zone brackets:    the state at the zone's first boss attempt (the bot's <zone>_<profile>_<seed>.json snapshots)
//   Shatter brackets: the state saved just before Shatter n (shatter<n>_<profile>_<seed>.json), passed through the PRODUCTION Shatter
//                     function (doReforge) so the scored build is the legal post-Shatter state with n Shatters, scored against that
//                     bracket's Endless defense. Bracket n is measured only when at least --minRuns runs (default 30) performed Shatter n.
// Every roster hero drills once with exactly --taps scripted taps a second (default 2, the calibration input); the best hero's total is
// the observation. Reports P25 / P50 / P75 / P90 (the Bronze / Silver / Gold / Crystal thresholds), the profile counts and per-profile
// medians, and the provenance of the batch that produced the states (its manifest) and of the tree scoring them.
// Usage: node tests/sim/drillbench.js --dir snapshots_calib [--profiles idleboost,light,casual,engaged] [--seeds 81-90] [--taps 2] [--minRuns 30] [--json out.json]
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');const H=require('./headless.js');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const DIR=path.resolve(__dirname,String(args.dir||'snapshots_calib')),PROFILES=String(args.profiles||'idleboost,light,casual,engaged').split(','),TAPS=Number(args.taps==null?2:args.taps),MIN_RUNS=Number(args.minRuns||30);
const [s0,s1]=String(args.seeds||'81-90').split('-').map(Number);const seeds=[];for(let s=s0;s<=(s1||s0);s++)seeds.push(s);
const pct=(a,q)=>{a=a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*q,lo=Math.floor(i),hi=Math.ceil(i);return a[lo]+(a[hi]-a[lo])*(i-lo);};const med=a=>pct(a,0.5);
const fmt=n=>n==null?'-':n>=1e12?(n/1e12).toFixed(2)+'T':n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(Math.round(n));
const ZK=['greenhollow','stillwater','thornwood','ironvein','emberwaste','amberfall','ashen_approach','ashen_keep','the_foundry'];
const files=fs.readdirSync(DIR).filter(f=>f.endsWith('.json')).filter(f=>{const m=f.match(/^(.*)_([a-z]+)_(\d+)\.json$/);return m&&PROFILES.includes(m[2])&&seeds.includes(Number(m[3]))&&(ZK.includes(m[1])||/^shatter\d+$/.test(m[1]));});
const scoring={commit:(()=>{try{return cp.execSync('git rev-parse HEAD',{cwd:__dirname,stdio:['ignore','pipe','ignore']}).toString().trim();}catch(e){return 'unknown';}})(),gameHash:crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..','..','source','game.js'))).digest('hex').slice(0,16)};
const tag=path.basename(DIR).replace(/^snapshots_/,'');let generating={tag,commit:'unknown',gameHash:'unknown'};try{const m=JSON.parse(fs.readFileSync(path.join(DIR,'..','manifests',tag+'.json'),'utf8'));generating={tag,commit:m.commit,gameHash:m.gameHash,harnessHash:m.harnessHash,config:m.config};}catch(e){}
const DT=1/60;
async function bench(file){const rec=JSON.parse(fs.readFileSync(path.join(DIR,file),'utf8'));const save=rec.save;const t=JSON.parse(save).t||1700000000000;const m=file.match(/^(.*)_([a-z]+)_(\d+)\.json$/);const sh=m[1].match(/^shatter(\d+)$/);
  const S=H.load({seed:7,startMs:t,save});await S.ready;const G=S.G;G.title=false;G.tut=null;G.sheet=null;S.DRILL.claims=false;
  if(sh){if((G.reforges||0)!==Number(sh[1])-1)throw new Error('state has '+G.reforges+' Shatters, expected '+(Number(sh[1])-1));if(!S.canReforge())throw new Error('Shatter '+sh[1]+' not legal in this state');S.doReforge();if((G.reforges||0)!==Number(sh[1]))throw new Error('Shatter did not apply');} /* the legal post-Shatter build */
  G.screen='vael';G.mode='walk';G.enc=1e9;G.enemies=[];G.action=null;G.projs=[];G.sheet=null;
  let br;if(sh){br=S.drillBrackets().find(b=>b.kind==='shatter'&&b.key===String(sh[1]));if(!br)return{skip:'bracket shatter:'+sh[1]+' not open in this state (Endless locked)'};}else{const zi=ZK.indexOf(m[1]);br=S.drillBrackets().find(b=>b.kind==='zone'&&b.zi===zi);if(!br)return{skip:'zone bracket '+zi+' not unlocked in this state'};}
  const every=TAPS?Math.round(60/TAPS):0;let best=null;for(const h of G.roster){if(!S.startDrill(h,br))continue;let f=0;const rt0=Math.ceil(S.getRT());while(G.drill.running){S.clock.frame();f++;S.setRT(rt0+f/60);S.update(DT,true);S.drillTick(DT);if(every&&f%every===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}G.sheet=null;G.screen='vael';const st=G.drill.stats;if(!best||st.total>best.total)best={total:st.total,heroDmg:st.heroDmg,tapDmg:st.tapDmg,hero:h.name+' '+S.CLASSES[h.cls].name+' Lv'+h.lvl};}
  const zi=br.kind==='zone'?br.zi:S.ZONES.length-1,rate=S.incomeRate(zi,br.kind==='zone'?S.ZONES[zi].fights-1:0);
  return{key:m[1],profile:m[2],seed:Number(m[3]),hours:rec.hours,reforges:G.reforges||0,bracket:S.drillBracketKey(br),def:G.drill.g.enemies[0].def,total:best.total,heroDmg:best.heroDmg,tapDmg:best.tapDmg,hero:best.hero,goldMin:rate.gold,oreMin:rate.ore};}
(async()=>{const rows=[],skipped=[];let n=0;for(const f of files){try{const r=await bench(f);if(r.skip)skipped.push(f+': '+r.skip);else rows.push(r);}catch(e){skipped.push(f+': '+e.message);}n++;process.stdout.write('\r'+n+'/'+files.length+'   ');}
  console.log('\nsnapshots from '+generating.tag+' (commit '+String(generating.commit).slice(0,10)+', game '+generating.gameHash+'); scored with commit '+scoring.commit.slice(0,10)+', game '+scoring.gameHash+'; best roster hero, '+TAPS+' taps/s; one observation per run per bracket');
  if(skipped.length)console.log('skipped '+skipped.length+': '+skipped.slice(0,5).join(' | ')+(skipped.length>5?' ...':''));
  const brackets=[...new Set(rows.map(r=>r.bracket))].sort((a,b)=>{const ka=a.split(':'),kb=b.split(':');if(ka[0]!==kb[0])return ka[0]==='zone'?-1:1;return Number(ka[1])-Number(kb[1]);});
  console.log('bracket        n   per profile (n: median)                                          def    P25       P50       P75       P90       hero P90   tap P90   gold/min  ore/min  status');
  const summary={};for(const b of brackets){const R=rows.filter(r=>r.bracket===b);const prof={};for(const p of PROFILES){const P=R.filter(r=>r.profile===p);if(P.length)prof[p]={n:P.length,median:med(P.map(r=>r.total))};}
    const tot=R.map(r=>r.total);const thr=[pct(tot,0.25),pct(tot,0.5),pct(tot,0.75),pct(tot,0.9)];const runsOk=R.length>=MIN_RUNS;summary[b]={n:R.length,profiles:prof,thresholds:thr,def:med(R.map(r=>r.def)),goldMin:med(R.map(r=>r.goldMin)),oreMin:med(R.map(r=>r.oreMin)),measured:runsOk};
    console.log(b.padEnd(13)+String(R.length).padStart(4)+'   '+Object.entries(prof).map(([p,v])=>p+' '+v.n+': '+fmt(v.median)).join(', ').padEnd(66)+String(med(R.map(r=>r.def))).padStart(5)+'  '+thr.map(x=>fmt(x).padStart(8)).join('  ')+'  '+fmt(pct(R.map(r=>r.heroDmg),0.9)).padStart(9)+'  '+fmt(pct(R.map(r=>r.tapDmg),0.9)).padStart(8)+'  '+fmt(med(R.map(r=>r.goldMin))).padStart(8)+'  '+fmt(med(R.map(r=>r.oreMin))).padStart(7)+'  '+(runsOk?'measured':'fewer than '+MIN_RUNS+' runs: provisional'));}
  if(args.json)fs.writeFileSync(String(args.json),JSON.stringify({meta:{model:'selected best hero, live drill rules, '+TAPS+' scripted taps/s, one post-Shatter state per run per Shatter bracket, first boss attempt per zone bracket',snapshots:generating,scoring,profiles:PROFILES,seeds:[s0,s1||s0],taps:TAPS,minRuns:MIN_RUNS,date:new Date().toISOString()},summary,rows,skipped},null,1));
})().catch(e=>{console.error(e);process.exit(1);});
