// Drill bench: the production Training Drill scored on saved game states (the bot's snapshots: one at every zone's first boss attempt,
// one just before every Shatter, one at the end of each run). Each state boots a fresh production game; every roster hero drills once in
// the state's current bracket with exactly two scripted taps a second (the calibration input); the best hero's total is the stage value.
// Records the provenance of the batch that produced the states (its manifest) and of the tree scoring them, and the profile distribution.
// Usage: node tests/sim/drillbench.js --dir snapshots_calib [--profiles idleboost,light,casual,engaged] [--seeds 81-90] [--taps 2] [--json out.json]
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');const H=require('./headless.js');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const DIR=path.resolve(__dirname,String(args.dir||'snapshots_calib')),PROFILES=String(args.profiles||'idleboost,light,casual,engaged').split(','),TAPS=Number(args.taps==null?2:args.taps);
const [s0,s1]=String(args.seeds||'81-90').split('-').map(Number);const seeds=[];for(let s=s0;s<=(s1||s0);s++)seeds.push(s);
const med=a=>{a=a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y);return a.length?a[Math.floor((a.length-1)/2)]:null;};const p90=a=>{a=a.filter(v=>v!=null).sort((x,y)=>x-y);return a.length?a[Math.min(a.length-1,Math.ceil((a.length-1)*0.9))]:null;};
const fmt=n=>n==null?'-':n>=1e12?(n/1e12).toFixed(2)+'T':n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(Math.round(n));
const ORDER=['greenhollow','stillwater','thornwood','ironvein','emberwaste','amberfall','ashen_approach','ashen_keep','the_foundry','the_endless','shatter','final'];
const files=fs.readdirSync(DIR).filter(f=>f.endsWith('.json')).filter(f=>{const m=f.match(/^(.*)_([a-z]+)_(\d+)\.json$/);return m&&PROFILES.includes(m[2])&&seeds.includes(Number(m[3]));});
const scoring={commit:(()=>{try{return cp.execSync('git rev-parse HEAD',{cwd:__dirname,stdio:['ignore','pipe','ignore']}).toString().trim();}catch(e){return 'unknown';}})(),gameHash:crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..','..','source','game.js'))).digest('hex').slice(0,16)};
const tag=path.basename(DIR).replace(/^snapshots_/,'');let generating={tag,commit:'unknown',gameHash:'unknown'};try{const m=JSON.parse(fs.readFileSync(path.join(DIR,'..','manifests',tag+'.json'),'utf8'));generating={tag,commit:m.commit,gameHash:m.gameHash,harnessHash:m.harnessHash,config:m.config};}catch(e){}
const DT=1/60;
async function bench(file){const rec=JSON.parse(fs.readFileSync(path.join(DIR,file),'utf8'));const save=rec.save;const t=JSON.parse(save).t||1700000000000;
  const S=H.load({seed:7,startMs:t,save});await S.ready;const G=S.G;G.title=false;G.tut=null;G.sheet=null;G.screen='vael';G.mode='walk';G.enc=1e9;G.enemies=[];G.action=null;G.projs=[];S.DRILL.claims=false;
  const brs=S.drillBrackets();if(!brs.length)throw new Error('no bracket unlocked');const br=brs[brs.length-1];const every=TAPS?Math.round(60/TAPS):0;
  let best=null;for(const h of G.roster){if(!S.startDrill(h,br))continue;let f=0;const rt0=Math.ceil(S.getRT());while(G.drill.running){S.clock.frame();f++;S.setRT(rt0+f/60);S.update(DT,true);S.drillTick(DT);if(every&&f%every===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}G.sheet=null;G.screen='vael';const st=G.drill.stats;if(!best||st.total>best.total)best={total:st.total,heroDmg:st.heroDmg,tapDmg:st.tapDmg,hero:h.name+' '+S.CLASSES[h.cls].name+' Lv'+h.lvl};}
  const zi=br.kind==='zone'?br.zi:S.ZONES.length-1,rate=S.incomeRate(zi,br.kind==='zone'?S.ZONES[zi].fights-1:0);const m=file.match(/^(.*)_([a-z]+)_(\d+)\.json$/);
  return{key:m[1],profile:m[2],seed:Number(m[3]),lv:rec.lv||null,hours:rec.hours,reforges:G.reforges||0,bracket:S.drillBracketKey(br),def:G.drill.g.enemies[0].def,total:best.total,heroDmg:best.heroDmg,tapDmg:best.tapDmg,hero:best.hero,goldMin:rate.gold,oreMin:rate.ore};}
(async()=>{const rows=[];let n=0;for(const f of files){try{rows.push(await bench(f));}catch(e){console.log('skip '+f+': '+e.message);}n++;process.stdout.write('\r'+n+'/'+files.length+'   ');}
  console.log('\nsnapshots from '+generating.tag+' (commit '+String(generating.commit).slice(0,10)+', game '+generating.gameHash+'); scored with commit '+scoring.commit.slice(0,10)+', game '+scoring.gameHash+'; best roster hero, '+TAPS+' taps/s');
  const groups={};for(const r of rows){const k=r.key.startsWith('final')?'final ('+r.bracket+')':r.key;(groups[k]=groups[k]||[]).push(r);}
  const keys=Object.keys(groups).sort((a,b)=>{const ia=ORDER.findIndex(z=>a.startsWith(z)),ib=ORDER.findIndex(z=>b.startsWith(z));if(ia!==ib)return ia-ib;return (parseInt(a.replace(/\D/g,''))||0)-(parseInt(b.replace(/\D/g,''))||0);});
  console.log('stage                          n (profiles)                                     hours   Lv    bracket        def     total median / P90         hero dmg P90   tap dmg P90   gold/min  ore/min');
  for(const k of keys){const R=groups[k];const prof={};for(const r of R)prof[r.profile]=(prof[r.profile]||0)+1;console.log(k.padEnd(30)+(String(R.length)+' ('+Object.entries(prof).map(([p,c])=>p+' '+c).join(', ')+')').padEnd(50)+String(med(R.map(r=>r.hours)).toFixed(1)).padStart(5)+'  '+String(med(R.map(r=>r.lv))).padStart(4)+'  '+String(R[0].bracket).padEnd(13)+String(med(R.map(r=>r.def))).padStart(6)+'  '+(fmt(med(R.map(r=>r.total)))+' / '+fmt(p90(R.map(r=>r.total)))).padStart(22)+'  '+fmt(p90(R.map(r=>r.heroDmg))).padStart(12)+'  '+fmt(p90(R.map(r=>r.tapDmg))).padStart(11)+'  '+fmt(med(R.map(r=>r.goldMin))).padStart(8)+'  '+fmt(med(R.map(r=>r.oreMin))).padStart(7));}
  if(args.json)fs.writeFileSync(String(args.json),JSON.stringify({meta:{model:'selected best hero, live drill rules, '+TAPS+' scripted taps/s',snapshots:generating,scoring,profiles:PROFILES,seeds:[s0,s1||s0],taps:TAPS,date:new Date().toISOString()},rows},null,1));
})().catch(e=>{console.error(e);process.exit(1);});
