// Paired Endless economy report (pass 31): candidate vs baseline on the same seeds. Validity (96h, cap), Core reproduction audit, identity through Endless entry,
// per-run Endless summary (entry state, hours, waves, wins/losses, gold earned/spent, power, level, ore, renown, gear), time-since-entry windows (0-6, 6-12, 12-18, 18-24h)
// with gold per kill, gold per hour, kills/deaths per hour, power, level, wave gain, purchases and growth ratios late vs early, paired between arms.
// Usage: node tests/sim/endlesscmp.js --a batch_out_p30 --b batch_out_p31 [--profiles idle,light,casual,engaged] [--seedStart 51 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const A=String(args.a||'batch_out_p30'),B=String(args.b||'batch_out_p31'),P=String(args.profiles||'idle,light,casual,engaged').split(','),S0=args.seedStart||51,N=args.seeds||10,H=[24,48,72,96],END='The Endless Road',FND='The Foundry';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0),mean=a=>{a=a.filter(v=>v!=null&&!isNaN(v));return a.length?sum(a)/a.length:null};
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const pair=(va,vb,d=1)=>{const dd=va.map((v,i)=>(vb[i]==null||v==null)?null:vb[i]-v).filter(x=>x!=null);return 'med '+f(med(va),d)+' -> '+f(med(vb),d)+(dd.length?' (paired med '+f(med(dd),d)+', +'+dd.filter(x=>x>0).length+' 0'+dd.filter(x=>x===0).length+' -'+dd.filter(x=>x<0).length+')':'');};
const WIN=[[0,6],[6,12],[12,18],[18,24]];
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],hr=r.hourly||[];o.simH=r.simHours;o.nsh=sh.length;
  const ei=Object.keys(rz).filter(k=>rz[k][END]).map(k=>({run:+k,h:rz[k][END].enterH,lv:rz[k][END].lvAtEntry,pw:rz[k][END].power,gear:rz[k][END].gear,ore:rz[k][END].ore}));o.endIn=ei.length?ei[0]:null;o.endH=((r.zoneTime||{})[END]||{sec:0}).sec/3600;o.best=r.endless&&r.endless.best||0;o.milestones=r.endless&&r.endless.milestones||0;
  const core=(r.bossFailRates||{})[FND];const CL=core?core.attemptLog.filter(a=>a.win!=null):[];o.coreAtt=CL.length;o.coreW=CL.filter(a=>a.win).length;o.coreAtk=CL[0]?CL[0].bossAtk:null;o.coreVolleyPct=med([].concat(...CL.map(a=>a.chargeDetail||[])).map(d=>d.pct));o.coreStall=core?core.stallH:null;const fc=Object.keys(rc).filter(k=>rc[k][FND]!=null).map(k=>rc[k][FND]);o.fndClr=fc.length?fc[0]:null;
  o.rows=[];if(o.endIn){const base=hr.filter(x=>x.h<=Math.floor(o.endIn.h)).pop();o.base=base;let prev=base;for(const row of hr.filter(x=>x.h>Math.floor(o.endIn.h))){if(row.wave==null){prev=row;continue;}const dh=row.h-prev.h||1;o.rows.push({t:row.h-Math.floor(o.endIn.h),h:row.h,wave:row.wave,best:row.bestWave,eLv:row.enemyLv,lv:row.lv,pw:row.power,wph:(row.wins-prev.wins)/dh,dph:(row.defeats-prev.defeats)/dh,gph:(row.earnedGold-prev.earnedGold)/dh,sph:(row.spentGold-prev.spentGold)/dh,oph:(row.earnedOre-prev.earnedOre)/dh,gpk:(row.earnedGold-prev.earnedGold)/Math.max(1,row.wins-prev.wins),renown:row.renown,tree:row.treeLv,rank:row.itemRank,ilvl:row.itemLvl,gold:row.gold,buys:Object.entries(row.spendBy||{}).reduce((a,[k,v])=>a+(v-((prev.spendBy||{})[k]||0)),0)});prev=row;}}
  o.win={};for(const [a,b] of WIN){const R=o.rows.filter(x=>x.t>a&&x.t<=b);if(R.length)o.win[a+'-'+b]={n:R.length,gpk:med(R.map(x=>x.gpk)),gph:mean(R.map(x=>x.gph)),sph:mean(R.map(x=>x.sph)),wph:mean(R.map(x=>x.wph)),dph:mean(R.map(x=>x.dph)),pw:R[R.length-1].pw,lv:R[R.length-1].lv,wave:R[R.length-1].best,buys:sum(R.map(x=>x.buys)),renown:R[R.length-1].renown,oph:mean(R.map(x=>x.oph))};}
  const last=hr[hr.length-1];o.goldEnd=last?last.gold:null;o.lv96=last?last.lv:null;o.pw96=last?last.power:null;o.renown=last?last.renown:null;o.tree=last?last.treeLv:null;o.rank=last?last.itemRank:null;o.ilvl=last?last.itemLvl:null;o.spendBy=r.spendBy||{};
  o.goldE=(r.econPerHour.goldEarned||0)*r.simHours/1e6;o.goldS=(r.econPerHour.goldSpent||0)*r.simHours/1e6;o.ore=(r.econPerHour.oreEarned||0)*r.simHours;o.def=r.final.defeats||0;o.gearUps=(hr[hr.length-1]||{}).gearUps;
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}const row=hr.filter(x=>x.h<=h).pop();o.zAt[h]=[cur,best,row?Math.round(row.power/1000):null];}
  return o;}
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'   baseline '+A+' (Endless gold 1.05^L) -> candidate '+B+' (1.04^L)');
  const MA=[],MB=[],V={h:0,cap:0,audit:0,core:0,n:0},outl=[];
  for(let s=S0;s<S0+N;s++){const a=rd(A,p,s),b=rd(B,p,s);if(!a||!b){console.log('seed '+s+': missing');continue;}const ma=m(a),mb=m(b);MA.push(ma);MB.push(mb);V.n++;if(mb.simH>=95.9)V.h++;if(mb.nsh<=3)V.cap++;
    const coreSame=ma.coreAtt===mb.coreAtt&&ma.coreW===mb.coreW&&ma.coreAtk===mb.coreAtk&&ma.fndClr===mb.fndClr&&ma.coreStall===mb.coreStall;if(coreSame)V.core++;
    const h0=ma.endIn?ma.endIn.h:1e9;const ra=(a.hourly||[]).filter(g=>g.h<=Math.floor(h0)),rb=(b.hourly||[]).filter(g=>g.h<=Math.floor(h0));let same=0;for(let i=0;i<Math.min(ra.length,rb.length);i++)if(JSON.stringify(ra[i])===JSON.stringify(rb[i]))same++;
    const endSame=JSON.stringify(ma.endIn)===JSON.stringify(mb.endIn);const noEnd=!ma.endIn&&!mb.endIn;const fullSame=noEnd&&(a.hourly||[]).length===(b.hourly||[]).length&&same===(a.hourly||[]).length;const ok=(coreSame&&same===ra.length&&ra.length===rb.length&&(endSame||noEnd))&&(!noEnd||fullSame);if(ok)V.audit++;
    console.log('\nseed '+s+'  hours '+f(mb.simH,2)+'  Shatters '+ma.nsh+'->'+mb.nsh+'  Core '+ma.coreW+'/'+ma.coreAtt+' atk '+ma.coreAtk+' volley '+(mb.coreVolleyPct!=null?f(100*mb.coreVolleyPct,0)+'%':'-')+' clear @'+(ma.fndClr!=null?ma.fndClr:'-')+' '+(coreSame?'reproduced':'DIFFERS')+'  audit through Endless entry: hourly '+same+'/'+ra.length+', entry '+(endSame?'same':(noEnd?'not reached in either':'DIFFER'))+' -> '+(ok?'OK':'MISMATCH'));
    if(mb.endIn){console.log('  Endless: entry @'+mb.endIn.h+'h run'+mb.endIn.run+' Lv'+mb.endIn.lv+' pw'+Math.round(mb.endIn.pw/1000)+'K gold '+Math.round((mb.base?mb.base.gold:0)/1e6)+'M tree '+(mb.base?mb.base.treeLv:'-')+' | hours '+f(ma.endH,1)+'->'+f(mb.endH,1)+' best wave '+ma.best+'->'+mb.best+' milestones '+ma.milestones+'->'+mb.milestones+' | gold earned '+f(ma.goldE,0)+'->'+f(mb.goldE,0)+'M spent '+f(ma.goldS,0)+'->'+f(mb.goldS,0)+'M end balance '+Math.round((ma.goldEnd||0)/1e6)+'->'+Math.round((mb.goldEnd||0)/1e6)+'M | Lv@96h '+ma.lv96+'->'+mb.lv96+' pw '+Math.round((ma.pw96||0)/1000)+'K->'+Math.round((mb.pw96||0)/1000)+'K | ore '+Math.round(ma.ore/1000)+'K->'+Math.round(mb.ore/1000)+'K gearUps '+ma.gearUps+'->'+mb.gearUps+' renown '+Math.round((ma.renown||0)/1000)+'K->'+Math.round((mb.renown||0)/1000)+'K tree '+ma.tree+'->'+mb.tree+' item '+ma.rank+'/'+ma.ilvl+'->'+mb.rank+'/'+mb.ilvl);
      for(const k of Object.keys(mb.win)){const wa=ma.win[k],wb=mb.win[k];if(!wa||!wb)continue;console.log('    '+k+'h: gold/kill '+Math.round(wa.gpk/1000)+'K->'+Math.round(wb.gpk/1000)+'K | gold/h '+f(wa.gph/1e6,1)+'->'+f(wb.gph/1e6,1)+'M spent/h '+f(wa.sph/1e6,1)+'->'+f(wb.sph/1e6,1)+'M | kills/h '+f(wa.wph,0)+'->'+f(wb.wph,0)+' deaths/h '+f(wa.dph,1)+'->'+f(wb.dph,1)+' | power '+Math.round(wa.pw/1000)+'K->'+Math.round(wb.pw/1000)+'K Lv '+wa.lv+'->'+wb.lv+' best wave '+wa.wave+'->'+wb.wave+' | purchases '+f(wa.buys/1e6,1)+'->'+f(wb.buys/1e6,1)+'M ore/h '+Math.round(wa.oph/1000)+'K->'+Math.round(wb.oph/1000)+'K renown '+Math.round((wa.renown||0)/1000)+'K->'+Math.round((wb.renown||0)/1000)+'K');}}
    else console.log('  Endless not reached'+(ma.endIn?' in candidate (baseline reached @'+ma.endIn.h+')':''));
    console.log('  zones cur/best/powerK '+H.map(h=>h+'h '+ma.zAt[h].join('/')+'->'+mb.zAt[h].join('/')).join(', ')+' | defeats '+ma.def+'->'+mb.def);
    if((ma.endIn&&!mb.endIn)||(!ma.endIn&&mb.endIn)||(ma.best&&mb.best&&Math.abs(mb.best-ma.best)/ma.best>0.3))outl.push('seed '+s+': '+((ma.endIn&&!mb.endIn)?'Endless lost; ':'')+((!ma.endIn&&mb.endIn)?'Endless newly reached; ':'')+(ma.best&&mb.best&&Math.abs(mb.best-ma.best)/ma.best>0.3?'best wave '+ma.best+'->'+mb.best:''));}
  console.log('\n-- '+p+' validity: 96h '+V.h+'/'+V.n+', Shatter cap '+V.cap+'/'+V.n+', Core reproduced '+V.core+'/'+V.n+', audit through Endless entry OK '+V.audit+'/'+V.n);
  const both=MA.map((x,i)=>[x,MB[i]]).filter(([x,y])=>x.endIn&&y.endIn);
  console.log('-- '+p+' Endless (runs reaching in both arms '+both.length+'/'+V.n+'): hours '+pair(both.map(x=>x[0].endH),both.map(x=>x[1].endH),1)+' | best wave '+pair(both.map(x=>x[0].best),both.map(x=>x[1].best),0)+' | milestones '+pair(both.map(x=>x[0].milestones),both.map(x=>x[1].milestones),0)+' | gold earned M '+pair(both.map(x=>x[0].goldE),both.map(x=>x[1].goldE),1)+' | spent M '+pair(both.map(x=>x[0].goldS),both.map(x=>x[1].goldS),1)+' | end balance M '+pair(both.map(x=>x[0].goldEnd/1e6),both.map(x=>x[1].goldEnd/1e6),1)+' | Lv@96h '+pair(both.map(x=>x[0].lv96),both.map(x=>x[1].lv96),0)+' | power@96h K '+pair(both.map(x=>x[0].pw96/1000),both.map(x=>x[1].pw96/1000),0)+' | ore '+pair(both.map(x=>x[0].ore),both.map(x=>x[1].ore),0)+' | renown K '+pair(both.map(x=>x[0].renown/1000),both.map(x=>x[1].renown/1000),0)+' | tree levels '+pair(both.map(x=>x[0].tree),both.map(x=>x[1].tree),0)+' | defeats '+pair(MA.map(x=>x.def),MB.map(x=>x.def),0));
  for(const [a,b] of WIN){const k=a+'-'+b;const pa=both.filter(x=>x[0].win[k]&&x[1].win[k]);if(!pa.length)continue;console.log('   window '+k+'h (n='+pa.length+'): gold/kill K '+pair(pa.map(x=>x[0].win[k].gpk/1000),pa.map(x=>x[1].win[k].gpk/1000),0)+' | gold/h M '+pair(pa.map(x=>x[0].win[k].gph/1e6),pa.map(x=>x[1].win[k].gph/1e6),1)+' | kills/h '+pair(pa.map(x=>x[0].win[k].wph),pa.map(x=>x[1].win[k].wph),0)+' | deaths/h '+pair(pa.map(x=>x[0].win[k].dph),pa.map(x=>x[1].win[k].dph),1)+' | power K '+pair(pa.map(x=>x[0].win[k].pw/1000),pa.map(x=>x[1].win[k].pw/1000),0)+' | Lv '+pair(pa.map(x=>x[0].win[k].lv),pa.map(x=>x[1].win[k].lv),0)+' | best wave '+pair(pa.map(x=>x[0].win[k].wave),pa.map(x=>x[1].win[k].wave),0)+' | purchases M '+pair(pa.map(x=>x[0].win[k].buys/1e6),pa.map(x=>x[1].win[k].buys/1e6),1));}
  const ratio=(M,k1,k2,field)=>M.filter(x=>x.win[k1]&&x.win[k2]).map(x=>x.win[k2][field]/Math.max(1e-9,x.win[k1][field]));
  for(const [k1,k2] of [['0-6','12-18'],['0-6','18-24']]){const ga=ratio(both.map(x=>x[0]),k1,k2,'gpk'),gb=ratio(both.map(x=>x[1]),k1,k2,'gpk'),ha=ratio(both.map(x=>x[0]),k1,k2,'gph'),hb=ratio(both.map(x=>x[1]),k1,k2,'gph'),pa2=ratio(both.map(x=>x[0]),k1,k2,'pw'),pb2=ratio(both.map(x=>x[1]),k1,k2,'pw');if(ga.length)console.log('   growth '+k1+'h -> '+k2+'h (n='+ga.length+'): gold/kill x'+f(med(ga),2)+' -> x'+f(med(gb),2)+' | gold/h x'+f(med(ha),2)+' -> x'+f(med(hb),2)+' | power x'+f(med(pa2),2)+' -> x'+f(med(pb2),2));}
  console.log('-- '+p+' horizons cur/best/powerK med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][0]))+'/'+med(MA.map(x=>x.zAt[h][1]))+'/'+med(MA.map(x=>x.zAt[h][2]))+'->'+med(MB.map(x=>x.zAt[h][0]))+'/'+med(MB.map(x=>x.zAt[h][1]))+'/'+med(MB.map(x=>x.zAt[h][2]))).join(', '));
  console.log('-- '+p+' outliers: '+(outl.length?outl.join(' || '):'none'));
}
