// Paired Hollow King candidate report (pass 28): candidate batch vs the pass 27 baseline on the same seeds. Validity, audit through first Keep entry, Hollow King by run/window with phases and damage shares,
// Keep time, Foundry/Core/Endless downstream, horizons, totals, outliers.
// Usage: node tests/sim/hkcmp.js --a batch_out_p27 --b batch_out_p28 [--profiles idle,light,casual,engaged] [--seedStart 51 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const A=String(args.a||'batch_out_p27'),B=String(args.b||'batch_out_p28'),P=String(args.profiles||'idle,light,casual,engaged').split(','),S0=args.seedStart||51,N=args.seeds||10,H=[24,48,72,96];
const KEEP='Ashen Keep',FND='The Foundry',END='The Endless Road';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0),mean=a=>{a=a.filter(v=>v!=null&&!isNaN(v));return a.length?sum(a)/a.length:null};
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const pair=(va,vb,d=1)=>{const dd=va.map((v,i)=>(vb[i]==null||v==null)?null:vb[i]-v).filter(x=>x!=null);return 'med '+f(med(va),d)+' -> '+f(med(vb),d)+(dd.length?' (paired med '+f(med(dd),d)+', +'+dd.filter(x=>x>0).length+' 0'+dd.filter(x=>x===0).length+' -'+dd.filter(x=>x<0).length+')':'');};
const classify=a=>{const t=a.taken||{};const boss=Object.entries(t).filter(([k])=>/King|Core/.test(k)).reduce((x,[,v])=>x+v,0),sk=Object.entries(t).filter(([k])=>/^skeleton$/i.test(k)).reduce((x,[,v])=>x+v,0),ar=Object.entries(t).filter(([k])=>/armou?red/i.test(k)).reduce((x,[,v])=>x+v,0);const tot=sum(Object.values(t))||1;return{boss:boss/tot,sk:sk/tot,ar:ar/tot,phase:!(a.summons&&a.summons[0])?'opening':(!(a.summons[1])?'after skeletons':'after armored')};};
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],hr=r.hourly||[],spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
  o.simH=r.simHours;o.nsh=sh.length;o.sh=sh;
  const ke=Object.keys(rz).filter(k=>rz[k][KEEP]).map(k=>({run:+k,h:rz[k][KEEP].enterH,lv:rz[k][KEEP].lvAtEntry,pw:rz[k][KEEP].power}));o.keepIn=ke;o.firstKeep=ke.length?Math.min(...ke.map(e=>e.h)):null;
  const kc=Object.keys(rc).filter(k=>rc[k][KEEP]!=null).map(k=>({run:+k,h:rc[k][KEEP]}));o.keepClr=kc.length?kc[0]:null;const zt=(r.zoneTime||{})[KEEP]||{sec:0};o.keepH=zt.sec/3600;
  const hk=(r.bossFailRates||{})[KEEP];const L=hk?hk.attemptLog.filter(a=>a.win!=null):[];o.hkAtt=L.length;o.hkW=L.filter(a=>a.win).length;o.hkAuto=[L.filter(a=>a.window==='auto'&&a.win).length,L.filter(a=>a.window==='auto').length];o.hkAct=[L.filter(a=>a.window!=='auto'&&a.win).length,L.filter(a=>a.window!=='auto').length];o.hkStall=hk?hk.stallH:null;o.hkFirstTry=hk?!!hk.firstTryClear:null;
  const losses=L.filter(a=>!a.win),wins=L.filter(a=>a.win);o.lossDur=med(losses.map(a=>a.dur));o.lossHp=med(losses.map(a=>a.hpLeft));o.lossDeaths=med(losses.map(a=>a.deaths));o.winSurv=med(wins.map(a=>a.survivors));o.winHp=med(wins.map(a=>a.partyHp));o.winDur=med(wins.map(a=>a.dur));
  const cl=losses.filter(a=>a.taken).map(classify);o.phases={opening:cl.filter(c=>c.phase==='opening').length,sk:cl.filter(c=>c.phase==='after skeletons').length,ar:cl.filter(c=>c.phase==='after armored').length};o.shares={boss:mean(cl.map(c=>c.boss)),sk:mean(cl.map(c=>c.sk)),ar:mean(cl.map(c=>c.ar))};o.hkAtk=L[0]?L[0].bossAtk:null;o.hkLv=med(L.map(a=>a.lv));o.hkPw=med(L.map(a=>a.power));
  const fi=Object.keys(rz).filter(k=>rz[k][FND]).map(k=>({run:+k,h:rz[k][FND].enterH,lv:rz[k][FND].lvAtEntry,pw:rz[k][FND].power}));o.fndIn=fi.length?fi[0]:null;const fc=Object.keys(rc).filter(k=>rc[k][FND]!=null).map(k=>rc[k][FND]);o.fndClr=fc.length?fc[0]:null;const bz=(r.byZone||{})[FND]||{},zf=(r.zoneTime||{})[FND]||{sec:0};o.fndEnc=Math.round(zf.sec/spe);o.fndLoss=bz.defeats||0;o.fndH=zf.sec/3600;o.fndFar=Math.max(0,...hr.filter(g=>g.zone===FND).map(g=>g.prog),r.final.zone===FND?r.final.prog:0);
  const core=(r.bossFailRates||{})[FND];const C=core?core.attemptLog.filter(a=>a.win!=null):[];o.coreAtt=C.length;o.coreW=C.filter(a=>a.win).length;o.coreAuto=[C.filter(a=>a.window==='auto'&&a.win).length,C.filter(a=>a.window==='auto').length];o.coreStall=core?core.stallH:null;
  const ei=Object.keys(rz).filter(k=>rz[k][END]).map(k=>rz[k][END].enterH);o.endIn=ei.length?ei[0]:null;o.endH=((r.zoneTime||{})[END]||{sec:0}).sec/3600;o.endBest=r.endless&&r.endless.best||0;
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}o.zAt[h]=[cur,best];}
  o.def=r.final.defeats||0;o.train=(r.autoTrain&&r.autoTrain.timeSec||0)/3600;o.gold=(r.econPerHour.goldEarned||0)*r.simHours/1e6;o.goldSp=(r.econPerHour.goldSpent||0)*r.simHours/1e6;o.ore=(r.econPerHour.oreEarned||0)*r.simHours;o.final=(r.final.shatters||0)+' '+r.final.zone+' f'+r.final.prog+' Lv'+r.final.partyLv;const l96=hr.filter(x=>x.h<=96).pop();o.lv96=l96?l96.lv:null;o.pw96=l96?l96.power:null;
  return o;}
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'   baseline '+A+' (ATK 1.7) -> candidate '+B+' (ATK 1.3)');
  const MA=[],MB=[],V={h:0,cap:0,audit:0,n:0},outl=[];
  for(let s=S0;s<S0+N;s++){const a=rd(A,p,s),b=rd(B,p,s);if(!a||!b){console.log('seed '+s+': missing');continue;}const ma=m(a),mb=m(b);MA.push(ma);MB.push(mb);V.n++;if(mb.simH>=95.9)V.h++;if(mb.nsh<=3)V.cap++;
    const h0=ma.firstKeep!=null?ma.firstKeep:1e9;const ra=(a.hourly||[]).filter(g=>g.h<h0),rb=(b.hourly||[]).filter(g=>g.h<h0);let same=0;for(let i=0;i<Math.min(ra.length,rb.length);i++)if(JSON.stringify(ra[i])===JSON.stringify(rb[i]))same++;
    const shA=a.shatters.filter(x=>x.h<h0).map(x=>[x.h,x.zone,x.gain]).join('|'),shB=b.shatters.filter(x=>x.h<h0).map(x=>[x.h,x.zone,x.gain]).join('|');
    const pre=z=>{const x=(a.bossFailRates||{})[z],y=(b.bossFailRates||{})[z];const fa=x?x.attemptLog.filter(t=>t.win!=null).map(t=>[t.n,t.win,t.bossAtk,t.dur]):[],fb=y?y.attemptLog.filter(t=>t.win!=null).map(t=>[t.n,t.win,t.bossAtk,t.dur]):[];return JSON.stringify(fa.slice(0,Math.min(fa.length,fb.length)))===JSON.stringify(fb.slice(0,Math.min(fa.length,fb.length)))&&fa.length<=fb.length+0;};
    const keepInSame=JSON.stringify(ma.keepIn[0]||null)===JSON.stringify(mb.keepIn[0]||null);const ok=same===ra.length&&ra.length===rb.length&&shA===shB&&keepInSame&&mb.hkAtk!=null&&mb.hkAtk<ma.hkAtk;if(ok)V.audit++;
    console.log('\nseed '+s+'  hours '+f(mb.simH,2)+'  Shatters '+ma.nsh+'->'+mb.nsh+'  audit through first Keep entry (h'+f(ma.firstKeep,1)+'): hourly '+same+'/'+ra.length+', Shatters before it '+(shA===shB?'same':'DIFFER')+', first Keep entry '+(keepInSame?'same':'DIFFER')+', boss ATK '+ma.hkAtk+'->'+mb.hkAtk+' -> '+(ok?'OK':'MISMATCH'));
    console.log('  Hollow King: attempts '+ma.hkAtt+'->'+mb.hkAtt+' wins '+ma.hkW+'->'+mb.hkW+' [auto '+ma.hkAuto.join('/')+'->'+mb.hkAuto.join('/')+', active '+ma.hkAct.join('/')+'->'+mb.hkAct.join('/')+'] stall '+f(ma.hkStall,1)+'->'+f(mb.hkStall,1)+'h'+(mb.hkFirstTry?' FIRST-TRY':'')+' | party Lv '+f(ma.hkLv,0)+'->'+f(mb.hkLv,0)+' pw '+Math.round((ma.hkPw||0)/1000)+'K->'+Math.round((mb.hkPw||0)/1000)+'K | loss dur '+f(ma.lossDur,0)+'->'+f(mb.lossDur,0)+'s HP left '+f(100*(ma.lossHp||0),0)+'->'+f(100*(mb.lossHp||0),0)+'% deaths '+ma.lossDeaths+'->'+mb.lossDeaths+' | win surv '+ma.winSurv+'->'+mb.winSurv+' HP '+f(100*(ma.winHp||0),0)+'->'+f(100*(mb.winHp||0),0)+'% dur '+f(ma.winDur,0)+'->'+f(mb.winDur,0)+'s');
    console.log('  phases (opening/skel/armored) '+ma.phases.opening+'/'+ma.phases.sk+'/'+ma.phases.ar+' -> '+mb.phases.opening+'/'+mb.phases.sk+'/'+mb.phases.ar+' | damage share boss/skel/armored '+f(100*ma.shares.boss,0)+'/'+f(100*ma.shares.sk,0)+'/'+f(100*ma.shares.ar,0)+'% -> '+f(100*mb.shares.boss,0)+'/'+f(100*mb.shares.sk,0)+'/'+f(100*mb.shares.ar,0)+'% | Keep clear h '+(ma.keepClr?ma.keepClr.h:'-')+'->'+(mb.keepClr?mb.keepClr.h:'-')+' time in Keep '+f(ma.keepH,1)+'->'+f(mb.keepH,1)+'h');
    console.log('  Foundry: entered '+(ma.fndIn?'@'+ma.fndIn.h+' Lv'+ma.fndIn.lv:'-')+' -> '+(mb.fndIn?'@'+mb.fndIn.h+' Lv'+mb.fndIn.lv:'-')+' | ordinary enc '+ma.fndEnc+' L'+ma.fndLoss+' far '+ma.fndFar+' -> enc '+mb.fndEnc+' L'+mb.fndLoss+' far '+mb.fndFar+' | Core '+ma.coreW+'/'+ma.coreAtt+' (auto '+ma.coreAuto.join('/')+') -> '+mb.coreW+'/'+mb.coreAtt+' (auto '+mb.coreAuto.join('/')+') | cleared '+(ma.fndClr!=null?'@'+ma.fndClr:'-')+'->'+(mb.fndClr!=null?'@'+mb.fndClr:'-')+' | Endless '+(ma.endIn!=null?'@'+ma.endIn+' ('+f(ma.endH,1)+'h, wave '+ma.endBest+')':'-')+' -> '+(mb.endIn!=null?'@'+mb.endIn+' ('+f(mb.endH,1)+'h, wave '+mb.endBest+')':'-'));
    console.log('  zones cur/best '+H.map(h=>h+'h '+ma.zAt[h].join('/')+'->'+mb.zAt[h].join('/')).join(', ')+' | defeats '+ma.def+'->'+mb.def+' | training '+f(ma.train,1)+'->'+f(mb.train,1)+'h | Lv@96h '+ma.lv96+'->'+mb.lv96+' pw '+Math.round((ma.pw96||0)/1000)+'K->'+Math.round((mb.pw96||0)/1000)+'K | gold '+f(ma.gold,1)+'->'+f(mb.gold,1)+'M (spent '+f(ma.goldSp,1)+'->'+f(mb.goldSp,1)+') ore '+Math.round(ma.ore/1000)+'K->'+Math.round(mb.ore/1000)+'K | final '+ma.final+' -> '+mb.final);
    if(mb.hkFirstTry||(ma.endIn==null&&mb.endIn!=null)||(mb.gold>2*ma.gold))outl.push('seed '+s+': '+(mb.hkFirstTry?'first-try Hollow King; ':'')+(ma.endIn==null&&mb.endIn!=null?'Endless newly reached @'+mb.endIn+'; ':'')+(mb.gold>2*ma.gold?'gold x'+f(mb.gold/ma.gold,1):''));}
  console.log('\n-- '+p+' validity: 96h '+V.h+'/'+V.n+', Shatter cap '+V.cap+'/'+V.n+', audit through first Keep entry OK '+V.audit+'/'+V.n);
  const agg=(M,k)=>M.reduce((a,x)=>[a[0]+x[k][0],a[1]+x[k][1]],[0,0]);const ph=(M,k)=>sum(M.map(x=>x.phases[k]));
  console.log('-- '+p+' Hollow King: attempts '+pair(MA.map(x=>x.hkAtt),MB.map(x=>x.hkAtt),0)+' | Auto-Cast wins/att '+agg(MA,'hkAuto').join('/')+' -> '+agg(MB,'hkAuto').join('/')+' ('+f(100*agg(MB,'hkAuto')[0]/Math.max(1,agg(MB,'hkAuto')[1]),1)+'%) | active wins/att '+agg(MA,'hkAct').join('/')+' -> '+agg(MB,'hkAct').join('/')+' ('+f(100*agg(MB,'hkAct')[0]/Math.max(1,agg(MB,'hkAct')[1]),0)+'%) | stall h '+pair(MA.map(x=>x.hkStall),MB.map(x=>x.hkStall),1)+' | first-try clears '+MA.filter(x=>x.hkFirstTry).length+'->'+MB.filter(x=>x.hkFirstTry).length+' | loss dur '+pair(MA.map(x=>x.lossDur),MB.map(x=>x.lossDur),0)+' | HP left% '+pair(MA.map(x=>100*(x.lossHp||0)),MB.map(x=>100*(x.lossHp||0)),0)+' | win party HP% '+pair(MA.map(x=>100*(x.winHp||0)),MB.map(x=>100*(x.winHp||0)),0));
  console.log('   loss phases opening/skeletons/armored '+ph(MA,'opening')+'/'+ph(MA,'sk')+'/'+ph(MA,'ar')+' -> '+ph(MB,'opening')+'/'+ph(MB,'sk')+'/'+ph(MB,'ar')+' | damage share boss '+f(100*mean(MA.map(x=>x.shares.boss)),0)+'% -> '+f(100*mean(MB.map(x=>x.shares.boss)),0)+'%, skeletons '+f(100*mean(MA.map(x=>x.shares.sk)),0)+'% -> '+f(100*mean(MB.map(x=>x.shares.sk)),0)+'% | Keep clear h '+pair(MA.map(x=>x.keepClr&&x.keepClr.h),MB.map(x=>x.keepClr&&x.keepClr.h),1)+' | time in Keep h '+pair(MA.map(x=>x.keepH),MB.map(x=>x.keepH),1));
  console.log('-- '+p+' downstream: Foundry entry h '+pair(MA.map(x=>x.fndIn&&x.fndIn.h),MB.map(x=>x.fndIn&&x.fndIn.h),1)+' | Foundry cleared runs '+MA.filter(x=>x.fndClr!=null).length+'->'+MB.filter(x=>x.fndClr!=null).length+' | Core wins/att '+sum(MA.map(x=>x.coreW))+'/'+sum(MA.map(x=>x.coreAtt))+' -> '+sum(MB.map(x=>x.coreW))+'/'+sum(MB.map(x=>x.coreAtt))+' (auto '+agg(MA,'coreAuto').join('/')+' -> '+agg(MB,'coreAuto').join('/')+') | Endless reached '+MA.filter(x=>x.endIn!=null).length+'->'+MB.filter(x=>x.endIn!=null).length+' (entry h '+pair(MA.map(x=>x.endIn),MB.map(x=>x.endIn),1)+', hours '+pair(MA.map(x=>x.endH),MB.map(x=>x.endH),1)+')');
  console.log('-- '+p+' horizons cur/best med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][0]))+'/'+med(MA.map(x=>x.zAt[h][1]))+'->'+med(MB.map(x=>x.zAt[h][0]))+'/'+med(MB.map(x=>x.zAt[h][1]))).join(', ')+' | defeats '+pair(MA.map(x=>x.def),MB.map(x=>x.def),0)+' | training h '+pair(MA.map(x=>x.train),MB.map(x=>x.train),1)+' | Lv@96h '+pair(MA.map(x=>x.lv96),MB.map(x=>x.lv96),0)+' | gold earned M '+pair(MA.map(x=>x.gold),MB.map(x=>x.gold),1)+' | ore earned '+pair(MA.map(x=>x.ore),MB.map(x=>x.ore),0));
  console.log('-- '+p+' outliers: '+(outl.length?outl.join(' || '):'none'));
}
