// Ashen Keep candidate comparison (pass 23): paired control vs candidate on the Shatter road. Audit through first Keep entry, Keep encounters/loss rate/furthest fight,
// fight-36 reach and Hollow King attempts, Keep clears and Foundry entries, horizons, Shatters, rewards (gold/ore earned, drops by zone), level trajectory.
// Usage: node tests/sim/keepcmp.js --a batch_out_p22 --b batch_out_p23 [--profiles idle,light,casual] [--seedStart 31 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const A=String(args.a||'batch_out_p22'),B=String(args.b||'batch_out_p23'),P=String(args.profiles||'idle,light,casual').split(','),S0=args.seedStart||31,N=args.seeds||10,H=[24,36,48,72];
const KEEP='Ashen Keep',APP='Ashen Approach',FND='The Foundry';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0);
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const pair=(va,vb,d=1)=>{const dd=va.map((v,i)=>(vb[i]==null||v==null)?null:vb[i]-v).filter(x=>x!=null);return 'med '+f(med(va),d)+' -> '+f(med(vb),d)+(dd.length?' (paired med '+f(med(dd),d)+', +'+dd.filter(x=>x>0).length+' 0'+dd.filter(x=>x===0).length+' -'+dd.filter(x=>x<0).length+')':'');};
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[];const spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
  o.keepEntries=Object.keys(rz).filter(k=>rz[k][KEEP]).map(k=>({run:+k,h:rz[k][KEEP].enterH,lv:rz[k][KEEP].lvAtEntry,pw:rz[k][KEEP].power}));o.firstKeepH=o.keepEntries.length?Math.min(...o.keepEntries.map(e=>e.h)):null;
  const bz=(r.byZone||{})[KEEP]||{},zt=(r.zoneTime||{})[KEEP]||{sec:0};o.keepH=zt.sec/3600;o.keepEnc=Math.round(zt.sec/spe);o.keepLoss=bz.defeats||0;o.keepWins=Math.max(0,o.keepEnc-o.keepLoss);o.keepLossPct=o.keepEnc?100*o.keepLoss/o.keepEnc:null;o.keepRewalk=(bz.rewalk||0)*spe/3600;
  o.keepFar=Math.max(0,...(r.hourly||[]).filter(g=>g.zone===KEEP).map(g=>g.prog),...sh.filter(s=>s.zone===KEEP).map(s=>s.farMark||0),r.final.zone===KEEP?r.final.prog:0);
  const hk=(r.bossFailRates||{})[KEEP];o.hk=hk?hk.attemptLog:[];o.hkWins=o.hk.filter(a=>a.win).length;o.hkReach=!!hk;o.keepClears=Object.keys(rc).filter(k=>rc[k][KEEP]!=null).map(k=>({run:+k,h:rc[k][KEEP]}));o.foundry=Object.keys(rz).filter(k=>rz[k][FND]).map(k=>({run:+k,h:rz[k][FND].enterH,lv:rz[k][FND].lvAtEntry,pw:rz[k][FND].power}));
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}o.zAt[h]=[cur,best];}
  o.sh=sh.map(s=>'h'+s.h+' '+s.zone.split(' ')[0]);o.shGapMin=sh.length>1?Math.min(...sh.slice(1).map((s,i)=>s.h-sh[i].h)):null;
  o.def=r.final.defeats||0;o.train=(r.autoTrain&&r.autoTrain.timeSec||0)/3600;o.goldEarned=(r.econPerHour&&r.econPerHour.goldEarned||0)*(r.simHours||72);o.oreEarned=(r.econPerHour&&r.econPerHour.oreEarned||0)*(r.simHours||72);o.dustEarned=sum(sh.map(s=>s.gain));
  o.simH=r.simHours;o.lvAt={};for(const h of [48,60,72]){const g=(r.simHours||0)>=h?(r.hourly||[]).filter(x=>x.h<=h).pop():null;o.lvAt[h]=g?g.lv:null;}o.keepDrops=(r.drops||{})[KEEP]||null;o.appEntry=Object.keys(rz).filter(k=>rz[k][APP]).map(k=>'run'+k+'@'+rz[k][APP].enterH+'/Lv'+rz[k][APP].lvAtEntry).join(' ');o.appClears=Object.keys(rc).filter(k=>rc[k][APP]!=null).map(k=>'run'+k+'@'+rc[k][APP]).join(' ');
  return o;}
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'   control '+A+' -> candidate '+B);
  const MA=[],MB=[],aud=[];
  for(let s=S0;s<S0+N;s++){const a=rd(A,p,s),b=rd(B,p,s);if(!a||!b){console.log('seed '+s+': missing');continue;}const ma=m(a),mb=m(b);MA.push(ma);MB.push(mb);
    const h0=ma.firstKeepH!=null?ma.firstKeepH:1e9;let same=0,n=0,bad=null;for(let i=0;i<Math.min(a.hourly.length,b.hourly.length);i++){if(a.hourly[i].h>=h0)break;n++;if(JSON.stringify(a.hourly[i])===JSON.stringify(b.hourly[i]))same++;else if(bad==null)bad=a.hourly[i].h;}
    const shA=a.shatters.filter(x=>x.h<h0).map(x=>x.h).join(','),shB=b.shatters.filter(x=>x.h<h0).map(x=>x.h).join(',');const appBefore=o=>Object.keys(o).filter(k=>o[k]<h0).map(k=>k+'@'+o[k]).join(' ');const rzA=a.runZones||{},rzB=b.runZones||{};const appA=Object.keys(rzA).filter(k=>rzA[k]['Ashen Approach']&&rzA[k]['Ashen Approach'].enterH<h0).map(k=>k+'@'+rzA[k]['Ashen Approach'].enterH+'/'+rzA[k]['Ashen Approach'].lvAtEntry).join(' '),appB=Object.keys(rzB).filter(k=>rzB[k]['Ashen Approach']&&rzB[k]['Ashen Approach'].enterH<h0).map(k=>k+'@'+rzB[k]['Ashen Approach'].enterH+'/'+rzB[k]['Ashen Approach'].lvAtEntry).join(' ');const okAudit=same===n&&shA===shB&&appA===appB;aud.push(okAudit);
    console.log('\nseed '+s+'  audit through first Keep entry (h'+f(ma.firstKeepH,1)+'): hourly '+same+'/'+n+(bad!=null?' first mismatch h'+bad:'')+', Shatters before it '+(shA===shB?'identical':'DIFFER ['+shA+'] vs ['+shB+']')+', Ashen Approach entries before it '+(appA===appB?'identical':'DIFFER')+' -> '+(okAudit?'OK':'MISMATCH'));
    console.log('  Keep entries: '+ma.keepEntries.map(e=>'run'+e.run+'@'+e.h+'h Lv'+e.lv+' pw'+e.pw).join(' | ')+'  ->  '+mb.keepEntries.map(e=>'run'+e.run+'@'+e.h+'h Lv'+e.lv+' pw'+e.pw).join(' | '));
    console.log('  Keep ordinary: enc '+ma.keepEnc+' W'+ma.keepWins+' L'+ma.keepLoss+' ('+f(ma.keepLossPct,0)+'%) '+f(ma.keepH,1)+'h far '+ma.keepFar+' rewalk '+f(ma.keepRewalk,2)+'h  ->  enc '+mb.keepEnc+' W'+mb.keepWins+' L'+mb.keepLoss+' ('+f(mb.keepLossPct,0)+'%) '+f(mb.keepH,1)+'h far '+mb.keepFar+' rewalk '+f(mb.keepRewalk,2)+'h');
    const hkTxt=o=>o.hk.length?o.hkWins+'/'+o.hk.length+' ('+o.hk.map(x=>(x.win?'W':'L')+(x.win?' surv'+x.survivors+' hp'+f(100*x.partyHp,0)+'%':' '+f(x.dur,0)+'s hp'+f(100*x.hpLeft,0)+'%'+(x.summoned?' summon':''))+' Lv'+x.lv+' run'+x.run).join('; ')+')':'not reached';
    console.log('  Hollow King: '+hkTxt(ma)+'  ->  '+hkTxt(mb)+(mb.keepClears.length?'   KEEP CLEARED '+mb.keepClears.map(c=>'run'+c.run+'@'+c.h+'h').join(' '):'')+(mb.foundry.length?'   FOUNDRY '+mb.foundry.map(e=>'run'+e.run+'@'+e.h+'h Lv'+e.lv+' pw'+e.pw).join(' '):''));
    console.log('  zones (cur/best) '+H.map(h=>h+'h '+ma.zAt[h].join('/')+'->'+mb.zAt[h].join('/')).join(', ')+' | Shatters '+ma.sh.join(' ')+' -> '+mb.sh.join(' ')+' (min gap '+f(mb.shGapMin,1)+'h)');
    console.log('  rewards: gold earned '+Math.round(ma.goldEarned/1000)+'K -> '+Math.round(mb.goldEarned/1000)+'K, ore '+Math.round(ma.oreEarned)+' -> '+Math.round(mb.oreEarned)+', dust '+ma.dustEarned+' -> '+mb.dustEarned+', Keep drops '+(ma.keepDrops?JSON.stringify(ma.keepDrops):'-')+' -> '+(mb.keepDrops?JSON.stringify(mb.keepDrops):'-')+' | Lv @48/60/72h '+[48,60,72].map(h=>ma.lvAt[h]).join('/')+' -> '+[48,60,72].map(h=>mb.lvAt[h]).join('/')+' | defeats '+ma.def+' -> '+mb.def+' | training '+f(ma.train,1)+' -> '+f(mb.train,1)+'h | simulated hours '+f(ma.simH,1)+' -> '+f(mb.simH,1)+' (a run ends at its third Shatter)');}
  console.log('\n-- '+p+' summary (n='+MA.length+'): audit OK '+aud.filter(Boolean).length+'/'+aud.length);
  console.log('   simulated hours (runs end at the third Shatter) '+pair(MA.map(x=>x.simH),MB.map(x=>x.simH),1));
  console.log('   runs entering the Keep '+MA.filter(x=>x.keepEntries.length).length+' -> '+MB.filter(x=>x.keepEntries.length).length+'; Keep entries per run '+pair(MA.map(x=>x.keepEntries.length),MB.map(x=>x.keepEntries.length),0)+'; first Keep entry h '+pair(MA.map(x=>x.firstKeepH),MB.map(x=>x.firstKeepH),1)+'; entry Lv (all entries) med '+f(med([].concat(...MA.map(x=>x.keepEntries.map(e=>e.lv)))),0)+' -> '+f(med([].concat(...MB.map(x=>x.keepEntries.map(e=>e.lv)))),0));
  console.log('   Keep encounters '+pair(MA.map(x=>x.keepEnc),MB.map(x=>x.keepEnc),0)+' | losses '+pair(MA.map(x=>x.keepLoss),MB.map(x=>x.keepLoss),0)+' | loss% '+pair(MA.map(x=>x.keepLossPct),MB.map(x=>x.keepLossPct),0)+' | hours '+pair(MA.map(x=>x.keepH),MB.map(x=>x.keepH),1)+' | furthest fight '+pair(MA.map(x=>x.keepFar),MB.map(x=>x.keepFar),0)+' | rewalk h '+pair(MA.map(x=>x.keepRewalk),MB.map(x=>x.keepRewalk),2));
  console.log('   fight 36 reached (runs) '+MA.filter(x=>x.hkReach).length+' -> '+MB.filter(x=>x.hkReach).length+'; Hollow King attempts/wins '+sum(MA.map(x=>x.hk.length))+'/'+sum(MA.map(x=>x.hkWins))+' -> '+sum(MB.map(x=>x.hk.length))+'/'+sum(MB.map(x=>x.hkWins))+'; attempts reaching a summon '+sum(MA.map(x=>x.hk.filter(a=>a.summoned).length))+' -> '+sum(MB.map(x=>x.hk.filter(a=>a.summoned).length))+'; loss duration med '+f(med([].concat(...MA.map(x=>x.hk.filter(a=>!a.win).map(a=>a.dur)))),0)+'s -> '+f(med([].concat(...MB.map(x=>x.hk.filter(a=>!a.win).map(a=>a.dur)))),0)+'s; Keep clears (runs) '+MA.filter(x=>x.keepClears.length).length+' -> '+MB.filter(x=>x.keepClears.length).length+'; Foundry entries (runs) '+MA.filter(x=>x.foundry.length).length+' -> '+MB.filter(x=>x.foundry.length).length);
  console.log('   zones best-run med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][1]))+'->'+med(MB.map(x=>x.zAt[h][1]))).join(', ')+' | current-run med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][0]))+'->'+med(MB.map(x=>x.zAt[h][0]))).join(', '));
  console.log('   rewards: gold earned '+pair(MA.map(x=>x.goldEarned/1e6),MB.map(x=>x.goldEarned/1e6),2)+'M | ore '+pair(MA.map(x=>x.oreEarned),MB.map(x=>x.oreEarned),0)+' | dust '+pair(MA.map(x=>x.dustEarned),MB.map(x=>x.dustEarned),0)+' | Lv@72h '+pair(MA.map(x=>x.lvAt[72]),MB.map(x=>x.lvAt[72]),0)+' | defeats '+pair(MA.map(x=>x.def),MB.map(x=>x.def),0)+' | training h '+pair(MA.map(x=>x.train),MB.map(x=>x.train),1));
}
