// Post-Keep progression diagnostic report (pass 27): Hollow King attempt attribution, Foundry exposure vs ability, Endless Road by hour since entry, economy attribution, horizons.
// Usage: node tests/sim/postkeep.js --dir batch_out_p27 [--profiles idle,light,casual,engaged] [--seedStart 51 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const D=String(args.dir||'batch_out_p27'),P=String(args.profiles||'idle,light,casual,engaged').split(','),S0=args.seedStart||51,N=args.seeds||10,H=[24,48,72,96];
const KEEP='Ashen Keep',FND='The Foundry',END='The Endless Road';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0),mean=a=>{a=a.filter(v=>v!=null&&!isNaN(v));return a.length?sum(a)/a.length:null};
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const classify=a=>{const t=a.taken||{};const boss=Object.entries(t).filter(([k])=>/King|Core/.test(k)).reduce((x,[,v])=>x+v,0),sk=Object.entries(t).filter(([k])=>/^Skeleton$/i.test(k)||/^skeleton/i.test(k)).reduce((x,[,v])=>x+v,0),ar=Object.entries(t).filter(([k])=>/armou?red/i.test(k)).reduce((x,[,v])=>x+v,0),other=sum(Object.values(t))-boss-sk-ar;const tot=boss+sk+ar+other||1;return{boss:boss/tot,sk:sk/tot,ar:ar/tot,other:other/tot,phase:!(a.summons&&a.summons[0])?'opening (before 70% summon)':(!(a.summons[1])?'after skeletons (70-35%)':'after armored skeletons (<35%)')};};
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'  '+D+'  (production 1.10, 96h)');
  const S={hk:[],core:[],fndIn:[],fndClr:[],endIn:[],endHours:[],endRows:[],zAt:{},keepClr:[],shatters:[],hkStall:[],fndStall:[],val:{h:0,cap:0,n:0}};
  for(let s=S0;s<S0+N;s++){const r=rd(D,p,s);if(!r){console.log('seed '+s+': missing');continue;}S.val.n++;if(r.simHours>=95.9)S.val.h++;if((r.shatters||[]).length<=3)S.val.cap++;
    const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],hr=r.hourly||[];
    const hk=(r.bossFailRates||{})[KEEP],core=(r.bossFailRates||{})[FND];
    const keepClr=Object.keys(rc).filter(k=>rc[k][KEEP]!=null).map(k=>({run:+k,h:rc[k][KEEP]}));const fndIn=Object.keys(rz).filter(k=>rz[k][FND]).map(k=>({run:+k,h:rz[k][FND].enterH,lv:rz[k][FND].lvAtEntry,pw:rz[k][FND].power}));const fndClr=Object.keys(rc).filter(k=>rc[k][FND]!=null).map(k=>({run:+k,h:rc[k][FND]}));const endIn=Object.keys(rz).filter(k=>rz[k][END]).map(k=>({run:+k,h:rz[k][END].enterH,lv:rz[k][END].lvAtEntry,pw:rz[k][END].power}));
    const at=h=>{let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}return cur+'/'+best;};
    console.log('\nseed '+s+'  hours '+f(r.simHours,2)+'  Shatters '+sh.map(x=>'h'+x.h+' '+x.zone.split(' ')[0]).join(', ')+'  zones cur/best '+H.map(h=>h+'h '+at(h)).join(', ')+'  final run '+(r.final.shatters||0)+' '+r.final.zone+' f'+r.final.prog+' Lv'+r.final.partyLv);
    if(hk){const L=hk.attemptLog.filter(a=>a.win!=null);const w=L.filter(a=>a.win).length;const byRun={};for(const a of L){const k='r'+a.run+'/'+(a.window==='auto'?'auto':'act');byRun[k]=byRun[k]||[0,0];byRun[k][1]++;if(a.win)byRun[k][0]++;}const losses=L.filter(a=>!a.win&&a.taken);const cl=losses.map(classify);const ph={};for(const c of cl)ph[c.phase]=(ph[c.phase]||0)+1;
      console.log('  Hollow King '+w+'/'+L.length+' ['+Object.entries(byRun).map(([k,v])=>k+' '+v[0]+'/'+v[1]).join(' ')+'] loss dur med '+f(med(losses.map(a=>a.dur)),0)+'s HP left med '+f(100*(med(losses.map(a=>a.hpLeft))||0),0)+'% deaths med '+med(losses.map(a=>a.deaths))+' | loss phase: '+Object.entries(ph).map(([k,v])=>v+' '+k).join(', ')+' | damage share at loss (mean): boss '+f(100*mean(cl.map(c=>c.boss)),0)+'% skeletons '+f(100*mean(cl.map(c=>c.sk)),0)+'% armored '+f(100*mean(cl.map(c=>c.ar)),0)+'% other '+f(100*mean(cl.map(c=>c.other)),0)+'%'+(keepClr.length?' | KEEP CLEARED '+keepClr.map(c=>'run'+c.run+'@'+c.h).join(' ')+(hk.stallH!=null?' stall '+f(hk.stallH,1)+'h':''):' | not cleared'));
      S.hk.push({att:L.length,w,losses:cl,dur:med(losses.map(a=>a.dur)),hp:med(losses.map(a=>a.hpLeft)),byRun,cleared:keepClr.length>0,stall:hk.stallH});}
    else console.log('  Hollow King not reached');
    if(fndIn.length){const bz=(r.byZone||{})[FND]||{},zt=(r.zoneTime||{})[FND]||{sec:0},spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;const enc=Math.round(zt.sec/spe);const far=Math.max(0,...hr.filter(g=>g.zone===FND).map(g=>g.prog),r.final.zone===FND?r.final.prog:0);const cl=core?core.attemptLog.filter(a=>a.win!=null):[];const cw=cl.filter(a=>a.win).length;const cls=cl.filter(a=>!a.win);const clrRow=fndClr.length?hr.filter(x=>x.h<=Math.ceil(fndClr[0].h)).pop():null;
      console.log('  Foundry: entered '+fndIn.map(e=>'run'+e.run+'@'+e.h+'h Lv'+e.lv+' pw'+e.pw).join(' ')+(fndClr.length?' | CLEARED '+fndClr.map(c=>'run'+c.run+'@'+c.h+'h').join(' ')+(clrRow?' Lv'+clrRow.lv+' pw'+clrRow.power:''):' | not cleared')+' | ordinary enc '+enc+' L'+(bz.defeats||0)+' ('+f(enc?100*(bz.defeats||0)/enc:null,0)+'%) '+f(zt.sec/3600,1)+'h far '+far+' | Core '+cw+'/'+cl.length+(cls.length?' loss dur med '+f(med(cls.map(a=>a.dur)),0)+'s HP left med '+f(100*(med(cls.map(a=>a.hpLeft))||0),0)+'% summon reached '+cls.filter(a=>a.summoned).length+' deaths med '+med(cls.map(a=>a.deaths)):'')+(core&&core.stallH!=null?' stall '+f(core.stallH,1)+'h':''));
      S.core.push({att:cl.length,w:cw,enc,loss:bz.defeats||0,h:zt.sec/3600,far,cleared:fndClr.length>0,dur:med(cls.map(a=>a.dur)),hp:med(cls.map(a=>a.hpLeft)),stall:core?core.stallH:null});S.fndIn.push(fndIn[0].h);if(fndClr.length)S.fndClr.push(fndClr[0].h-fndIn[0].h);}
    if(endIn.length){const e0=endIn[0];const rows=hr.filter(x=>x.wave!=null&&x.h>=Math.floor(e0.h));const base=hr.filter(x=>x.h<=Math.floor(e0.h)).pop();S.endIn.push(e0.h);
      const zt=(r.zoneTime||{})[END]||{sec:0};S.endHours.push(zt.sec/3600);
      console.log('  Endless: entered run'+e0.run+' @'+e0.h+'h Lv'+e0.lv+' pw'+e0.pw+' ('+f(zt.sec/3600,1)+'h in zone) carried in: gold '+Math.round((base?base.gold:0)/1e6)+'M ore '+(base?base.ore:0)+' | best wave '+(r.endless&&r.endless.best)+' milestones '+(r.endless&&r.endless.milestones));
      let prev=base;for(const row of rows){const dh=row.h-(prev?prev.h:row.h)||1;const dg=(row.earnedGold-(prev?prev.earnedGold:row.earnedGold))/dh,dsg=(row.spentGold-(prev?prev.spentGold:row.spentGold))/dh,dore=(row.earnedOre-(prev?prev.earnedOre:row.earnedOre))/dh,dw=(row.wins-(prev?prev.wins:row.wins))/dh,dd=(row.defeats-(prev?prev.defeats:row.defeats))/dh,dl=row.lv-(prev?prev.lv:row.lv),dt=(row.trainSec-(prev?prev.trainSec:row.trainSec))/3600/dh;const sb=row.spendBy||{},pb=(prev&&prev.spendBy)||{};const top=Object.keys(sb).map(k=>[k,(sb[k]||0)-(pb[k]||0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>x[0].replace(/Gold|Ore|Dust/,'')+' '+Math.round(x[1]/1000)+'K').join(', ');
        const o={t:row.h-Math.floor(e0.h),wave:row.wave,best:row.bestWave,eLv:row.enemyLv,lv:row.lv,pw:row.power,wph:dw,dph:dd,gph:dg,sgph:dsg,oph:dore,lph:dl,tph:dt,rank:row.itemRank,ilvl:row.itemLvl,top};S.endRows.push(o);
        console.log('    +'+o.t+'h: wave '+o.wave+' (best '+o.best+') enemy Lv'+o.eLv+' party Lv'+o.lv+' pw'+Math.round(o.pw/1000)+'K | wins/h '+f(o.wph,0)+' deaths/h '+f(o.dph,0)+' | gold earned/h '+Math.round(o.gph/1e6*10)/10+'M spent/h '+Math.round(o.sgph/1e6*10)/10+'M ore/h '+Math.round(o.oph)+' | +Lv '+f(o.lph,1)+' train h '+f(o.tph,2)+' | gear rank '+o.rank+' lvl '+o.ilvl+' | top spends: '+(o.top||'-'));prev=row;}}
    for(const h of H){(S.zAt[h]=S.zAt[h]||[]).push(at(h));}S.shatters.push(sh.length);
  }
  console.log('\n-- '+p+' validity: 96h reached '+S.val.h+'/'+S.val.n+', Shatter cap '+S.val.cap+'/'+S.val.n);
  const hkAll=[].concat(...S.hk.map(x=>x.losses));const byRunAll={};for(const x of S.hk)for(const [k,v] of Object.entries(x.byRun)){byRunAll[k]=byRunAll[k]||[0,0];byRunAll[k][0]+=v[0];byRunAll[k][1]+=v[1];}
  console.log('-- '+p+' Hollow King: reached in '+S.hk.length+'/'+S.val.n+' runs, cleared '+S.hk.filter(x=>x.cleared).length+'; attempts '+sum(S.hk.map(x=>x.att))+' wins '+sum(S.hk.map(x=>x.w))+' ['+Object.entries(byRunAll).sort().map(([k,v])=>k+' '+v[0]+'/'+v[1]).join(' ')+']; loss dur med '+f(med(S.hk.map(x=>x.dur)),0)+'s, HP left med '+f(100*(med(S.hk.map(x=>x.hp))||0),0)+'%; stall to clear med '+f(med(S.hk.filter(x=>x.cleared).map(x=>x.stall)),1)+'h; loss phases: '+Object.entries(hkAll.reduce((a,c)=>{a[c.phase]=(a[c.phase]||0)+1;return a;},{})).map(([k,v])=>v+' '+k).join(', ')+'; damage share at loss: boss '+f(100*mean(hkAll.map(c=>c.boss)),0)+'% skeletons '+f(100*mean(hkAll.map(c=>c.sk)),0)+'% armored '+f(100*mean(hkAll.map(c=>c.ar)),0)+'%');
  console.log('-- '+p+' Foundry: entered '+S.core.length+'/'+S.val.n+' runs (entry h med '+f(med(S.fndIn),1)+'), cleared '+S.core.filter(x=>x.cleared).length+' (hours to clear med '+f(med(S.fndClr),1)+'); ordinary loss% med '+f(med(S.core.map(x=>x.enc?100*x.loss/x.enc:null)),0)+', hours med '+f(med(S.core.map(x=>x.h)),1)+', furthest med '+med(S.core.map(x=>x.far))+'; Core attempts '+sum(S.core.map(x=>x.att))+' wins '+sum(S.core.map(x=>x.w))+', loss dur med '+f(med(S.core.map(x=>x.dur)),0)+'s HP left med '+f(100*(med(S.core.map(x=>x.hp))||0),0)+'%; stall to clear med '+f(med(S.core.filter(x=>x.cleared).map(x=>x.stall)),1)+'h');
  const er=S.endRows;console.log('-- '+p+' Endless: entered '+S.endIn.length+'/'+S.val.n+' runs (entry h med '+f(med(S.endIn),1)+', hours in zone med '+f(med(S.endHours),1)+'); per hour in zone (median over run-hours, n='+er.length+'): wins/h '+f(med(er.map(o=>o.wph)),0)+', deaths/h '+f(med(er.map(o=>o.dph)),0)+', gold earned/h '+f(med(er.map(o=>o.gph))/1e6,2)+'M, spent/h '+f(med(er.map(o=>o.sgph))/1e6,2)+'M, ore/h '+f(med(er.map(o=>o.oph)),0)+', +Lv/h '+f(med(er.map(o=>o.lph)),2)+', training h/h '+f(med(er.map(o=>o.tph)),2)+'; wave by hour since entry: '+[1,2,4,8,12,16,24].map(t=>'+'+t+'h '+f(med(er.filter(o=>o.t===t).map(o=>o.wave)),0)).join(', ')+'; enemy Lv at +1/+8/+16h: '+[1,8,16].map(t=>f(med(er.filter(o=>o.t===t).map(o=>o.eLv)),0)).join('/')+'; party Lv at +1/+8/+16h: '+[1,8,16].map(t=>f(med(er.filter(o=>o.t===t).map(o=>o.lv)),0)).join('/'));
  console.log('-- '+p+' horizons (cur/best med): '+H.map(h=>h+'h '+med(S.zAt[h].map(x=>+x.split('/')[0]))+'/'+med(S.zAt[h].map(x=>+x.split('/')[1]))).join(', ')+'; Shatters per run med '+med(S.shatters));
}
