// Production release-confidence report (pass 32): one batch on the production build, optionally alongside a reference batch (medians side by side).
// Per profile: validity, horizons (zone cur/best, level, power at 24/48/72/96h), Shatters, time per zone, late bosses (Grave Knight, Hollow King, Core) by window with stall and clear hour,
// Foundry exit and Endless entry, Endless exposure/economy, walls (any boss stall > 2h), per-seed outliers.
// Usage: node tests/sim/release.js --dir batch_out_p32 [--ref batch_out_p31 --refStart 51 --refSeeds 10] [--profiles idle,light,casual,engaged] [--seedStart 61 --seeds 20]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const D=String(args.dir||'batch_out_p32'),REF=args.ref?String(args.ref):null,P=String(args.profiles||'idle,light,casual,engaged').split(','),S0=args.seedStart||61,N=args.seeds||20,R0=args.refStart||51,RN=args.refSeeds||10,H=[24,48,72,96];
const ZONES=['Greenhollow Fields','Stillwater Lagoon','Thornwood','Ironvein Caverns','Emberwaste','Amberfall Woods','Ashen Approach','Ashen Keep','The Foundry','The Endless Road'];
const BOSSES=[['Ironvein Caverns','Warlord'],['Emberwaste','Sand Tyrant'],['Amberfall Woods','Hunter King'],['Ashen Approach','Grave Knight'],['Ashen Keep','Hollow King'],['The Foundry','Core']];
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},p90=a=>{a=srt(a);return a.length?a[Math.min(a.length-1,Math.ceil((a.length-1)*0.9))]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0);
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],hr=r.hourly||[],spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
  o.simH=r.simHours;o.nsh=sh.length;o.shH=sh.map(x=>x.h);o.gapMin=sh.length>1?Math.min(...sh.slice(1).map((s,i)=>s.h-sh[i].h)):null;
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}const row=hr.filter(x=>x.h<=h).pop();o.zAt[h]={cur,best,lv:row?row.lv:null,pw:row?row.power:null};}
  o.zoneH={};for(const z of ZONES){const zt=(r.zoneTime||{})[z];o.zoneH[z]=zt?zt.sec/3600:0;}
  o.boss={};for(const [z,name] of BOSSES){const b=(r.bossFailRates||{})[z];const L=b?b.attemptLog.filter(a=>a.win!=null):[];const clr=Object.keys(rc).filter(k=>rc[k][z]!=null).map(k=>rc[k][z]);o.boss[name]={att:L.length,w:L.filter(a=>a.win).length,auto:[L.filter(a=>a.window==='auto'&&a.win).length,L.filter(a=>a.window==='auto').length],act:[L.filter(a=>a.window!=='auto'&&a.win).length,L.filter(a=>a.window!=='auto').length],stall:b?b.stallH:null,firstClr:clr.length?Math.min(...clr):null,reached:!!b,chargeKills:L.length?sum(L.map(a=>a.chargeKills||0))/L.length:null,volleyPct:med([].concat(...L.map(a=>a.chargeDetail||[])).map(d=>d.pct)),lossDur:med(L.filter(a=>!a.win).map(a=>a.dur)),lossHp:med(L.filter(a=>!a.win).map(a=>a.hpLeft))};}
  const fe=Object.keys(rz).filter(k=>rz[k]['The Endless Road']).map(k=>rz[k]['The Endless Road'].enterH);o.endIn=fe.length?Math.min(...fe):null;o.endH=o.zoneH['The Endless Road'];o.best=r.endless&&r.endless.best||0;o.milestones=r.endless&&r.endless.milestones||0;const fc=Object.keys(rc).filter(k=>rc[k]['The Foundry']!=null).map(k=>rc[k]['The Foundry']);o.fndExit=fc.length?Math.min(...fc):null;
  if(o.endIn!=null){const base=hr.filter(x=>x.h<=Math.floor(o.endIn)).pop(),last=hr[hr.length-1];const dh=Math.max(1,last.h-(base?base.h:last.h));o.endDph=(last.defeats-(base?base.defeats:0))/dh;o.endGph=(last.earnedGold-(base?base.earnedGold:0))/dh/1e6;o.endSph=(last.spentGold-(base?base.spentGold:0))/dh/1e6;o.endLvGain=last.lv-(base?base.lv:0);o.endPwRatio=base&&base.power?last.power/base.power:null;}
  const last=hr[hr.length-1]||{};o.lv96=last.lv;o.pw96=last.power;o.renown=last.renown;o.ore=(r.econPerHour.oreEarned||0)*r.simHours;o.gold=(r.econPerHour.goldEarned||0)*r.simHours/1e6;o.def=r.final.defeats||0;o.train=(r.autoTrain&&r.autoTrain.timeSec||0)/3600;o.final=(r.final.shatters||0)+' '+r.final.zone+' f'+r.final.prog+' Lv'+r.final.partyLv;
  return o;}
const cell=(M,fn,d=1)=>{const v=M.map(fn);return f(med(v),d)+'/'+f(p90(v),d);};
for(const p of P){
  const M=[],MR=[];for(let s=S0;s<S0+N;s++){const r=rd(D,p,s);if(r)M.push(Object.assign(m(r),{seed:s}));}if(REF)for(let s=R0;s<R0+RN;s++){const r=rd(REF,p,s);if(r)MR.push(m(r));}
  console.log('\n===== '+p.toUpperCase()+'  '+D+' (n='+M.length+')'+(REF?'  reference '+REF+' (n='+MR.length+') shown after ->':'')+'   values med/P90');
  console.log('-- validity: 96h '+M.filter(x=>x.simH>=95.9).length+'/'+M.length+', Shatter cap '+M.filter(x=>x.nsh<=3).length+'/'+M.length);
  const both=(fn,d=1)=>cell(M,fn,d)+(REF?' -> '+cell(MR,fn,d):'');
  console.log('-- horizons: '+H.map(h=>h+'h zones cur/best '+cell(M,x=>x.zAt[h].cur,0)+' / '+cell(M,x=>x.zAt[h].best,0)+(REF?' (ref '+cell(MR,x=>x.zAt[h].best,0)+')':'')+' Lv '+both(x=>x.zAt[h].lv,0)+' powerK '+both(x=>x.zAt[h].pw/1000,0)).join(' | '));
  console.log('-- Shatters per run '+both(x=>x.nsh,0)+' | first h '+both(x=>x.shH[0],1)+' | third h '+both(x=>x.shH[2],1)+' | min gap '+both(x=>x.gapMin,1));
  console.log('-- hours in zone: '+ZONES.map(z=>z.replace('The ','').split(' ').slice(0,z.startsWith('Ashen')?2:1).join(' ')+' '+both(x=>x.zoneH[z],1)).join(' | '));
  for(const [,name] of BOSSES){const R=M.filter(x=>x.boss[name].reached),RR=MR.filter(x=>x.boss[name].reached);const agg=(S,k)=>S.reduce((a,x)=>[a[0]+x.boss[name][k][0],a[1]+x.boss[name][k][1]],[0,0]);
    console.log('-- '+name+': reached '+R.length+'/'+M.length+(REF?' (ref '+RR.length+'/'+MR.length+')':'')+' | attempts '+cell(R,x=>x.boss[name].att,0)+(REF?' -> '+cell(RR,x=>x.boss[name].att,0):'')+' | Auto-Cast '+agg(R,'auto').join('/')+(REF?' (ref '+agg(RR,'auto').join('/')+')':'')+' | active '+agg(R,'act').join('/')+(REF?' (ref '+agg(RR,'act').join('/')+')':'')+' | stall h '+cell(R,x=>x.boss[name].stall,1)+(REF?' -> '+cell(RR,x=>x.boss[name].stall,1):'')+' | cleared '+R.filter(x=>x.boss[name].firstClr!=null).length+'/'+R.length+' at h '+cell(R,x=>x.boss[name].firstClr,1)+(REF?' (ref '+RR.filter(x=>x.boss[name].firstClr!=null).length+'/'+RR.length+' @'+cell(RR,x=>x.boss[name].firstClr,1)+')':'')+' | loss dur/HP '+f(med(R.map(x=>x.boss[name].lossDur)),0)+'s '+f(100*(med(R.map(x=>x.boss[name].lossHp))||0),0)+'% | charge kills/att '+f(med(R.map(x=>x.boss[name].chargeKills)),2)+(name==='Core'?' | volley % of target HP '+f(100*(med(R.map(x=>x.boss[name].volleyPct))||0),0)+'%':''));}
  const E=M.filter(x=>x.endIn!=null),ER=MR.filter(x=>x.endIn!=null);
  console.log('-- Foundry exit '+M.filter(x=>x.fndExit!=null).length+'/'+M.length+' at h '+cell(M,x=>x.fndExit,1)+(REF?' (ref '+MR.filter(x=>x.fndExit!=null).length+'/'+MR.length+' @'+cell(MR,x=>x.fndExit,1)+')':'')+' | Endless entered '+E.length+'/'+M.length+' at h '+cell(E,x=>x.endIn,1)+(REF?' (ref '+ER.length+'/'+MR.length+' @'+cell(ER,x=>x.endIn,1)+')':'')+' | hours in Endless '+cell(E,x=>x.endH,1)+(REF?' -> '+cell(ER,x=>x.endH,1):'')+' | best wave '+cell(E,x=>x.best,0)+(REF?' -> '+cell(ER,x=>x.best,0):'')+' | milestones '+cell(E,x=>x.milestones,0)+' | deaths/h '+cell(E,x=>x.endDph,1)+(REF?' -> '+cell(ER,x=>x.endDph,1):'')+' | gold earned/h M '+cell(E,x=>x.endGph,1)+(REF?' -> '+cell(ER,x=>x.endGph,1):'')+' spent/h M '+cell(E,x=>x.endSph,1)+' | levels gained in Endless '+cell(E,x=>x.endLvGain,0)+' | power ratio in Endless x'+cell(E,x=>x.endPwRatio,1)+(REF?' -> x'+cell(ER,x=>x.endPwRatio,1):''));
  console.log('-- totals: Lv@96h '+both(x=>x.lv96,0)+' | power@96h K '+both(x=>x.pw96/1000,0)+' | gold earned M '+both(x=>x.gold,0)+' | ore earned K '+both(x=>x.ore/1000,0)+' | renown K '+both(x=>x.renown/1000,0)+' | defeats '+both(x=>x.def,0)+' | training h '+both(x=>x.train,1));
  const walls=[];for(const x of M)for(const [,name] of BOSSES){const b=x.boss[name];if(b.reached&&(b.stall==null?true:b.stall>2)&&b.att>=3)walls.push('seed '+x.seed+' '+name+' '+b.w+'/'+b.att+(b.stall!=null?' stall '+f(b.stall,1)+'h':' uncleared')+(b.firstClr!=null?' clear@'+f(b.firstClr,1):''));}
  console.log('-- boss walls (>2h stall or uncleared with >=3 attempts): '+(walls.length?walls.join(' | '):'none'));
  const out=[];for(const x of M){if(x.zAt[96].best<med(M.map(y=>y.zAt[96].best))-1)out.push('seed '+x.seed+' best zone '+x.zAt[96].best+' at 96h ('+x.final+')');if(x.endIn!=null&&x.best>2*med(E.map(y=>y.best)))out.push('seed '+x.seed+' Endless wave '+x.best);if(x.nsh>3)out.push('seed '+x.seed+' Shatters '+x.nsh);}
  console.log('-- outliers: '+(out.length?out.join(' | '):'none'));
}
