// Paired report for a post-Shatter scaling candidate against the valid baseline: validity/audit, horizons, Shatters and replays, Keep by run, Grave Knight and Hollow King by run, totals.
// Usage: node tests/sim/shatterscale.js --a batch_out_p24 --b batch_out_p25 [--profiles idle,light,casual] [--seedStart 31 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const A=String(args.a||'batch_out_p24'),B=String(args.b||'batch_out_p25'),P=String(args.profiles||'idle,light,casual').split(','),S0=args.seedStart||31,N=args.seeds||10,H=[24,36,48,60,72];
const KEEP='Ashen Keep',APP='Ashen Approach',FND='The Foundry';
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0);
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const pair=(va,vb,d=1)=>{const dd=va.map((v,i)=>(vb[i]==null||v==null)?null:vb[i]-v).filter(x=>x!=null);return 'med '+f(med(va),d)+' -> '+f(med(vb),d)+(dd.length?' (paired med '+f(med(dd),d)+', +'+dd.filter(x=>x>0).length+' 0'+dd.filter(x=>x===0).length+' -'+dd.filter(x=>x<0).length+')':'');};
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
  o.simH=r.simHours;o.nsh=sh.length;o.sh=sh;o.gapMin=sh.length>1?Math.min(...sh.slice(1).map((s,i)=>s.h-sh[i].h)):null;
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}o.zAt[h]=[cur,best];}
  o.runs={};for(const rk of Object.keys(rc)){const c=rc[rk],z=rz[rk]||{};o.runs[rk]={clears:Object.keys(c).length,app:c[APP],keep:c[KEEP],keepIn:z[KEEP]?z[KEEP].enterH:null,keepLv:z[KEEP]?z[KEEP].lvAtEntry:null,keepPw:z[KEEP]?z[KEEP].power:null,appIn:z[APP]?z[APP].enterH:null,appLv:z[APP]?z[APP].lvAtEntry:null};}
  const bz=(r.byZone||{})[KEEP]||{},zt=(r.zoneTime||{})[KEEP]||{sec:0};o.keepEnc=Math.round(zt.sec/spe);o.keepLoss=bz.defeats||0;o.keepLossPct=o.keepEnc?100*o.keepLoss/o.keepEnc:null;o.keepH=zt.sec/3600;o.keepFar=Math.max(0,...(r.hourly||[]).filter(g=>g.zone===KEEP).map(g=>g.prog),...sh.filter(s=>s.zone===KEEP).map(s=>s.farMark||0),r.final.zone===KEEP?r.final.prog:0);
  const by=(z)=>{const b=(r.bossFailRates||{})[z];const out={};if(b)for(const a of b.attemptLog){const k=a.run==null?'?':String(a.run);out[k]=out[k]||{n:0,w:0,atk:a.bossAtk,lv:[],dur:[],hp:[],sum:0};out[k].n++;if(a.win)out[k].w++;out[k].lv.push(a.lv);out[k].dur.push(a.dur);out[k].hp.push(a.hpLeft);if(a.summoned)out[k].sum++;}return out;};
  o.hk=by(KEEP);o.gk=by(APP);o.hkN=sum(Object.values(o.hk).map(v=>v.n));o.hkW=sum(Object.values(o.hk).map(v=>v.w));o.hkSum=sum(Object.values(o.hk).map(v=>v.sum));o.fight36=!!(r.bossFailRates||{})[KEEP];
  o.keepClears=Object.keys(rc).filter(k=>rc[k][KEEP]!=null).map(k=>'run'+k+'@'+rc[k][KEEP]);o.foundry=Object.keys(rz).filter(k=>rz[k][FND]).map(k=>'run'+k+'@'+rz[k][FND].enterH+'h Lv'+rz[k][FND].lvAtEntry+' pw'+rz[k][FND].power);
  o.def=r.final.defeats||0;o.train=(r.autoTrain&&r.autoTrain.timeSec||0)/3600;o.gold=(r.econPerHour.goldEarned||0)*r.simHours/1e6;o.goldSp=(r.econPerHour.goldSpent||0)*r.simHours/1e6;o.ore=(r.econPerHour.oreEarned||0)*r.simHours;o.oreSp=(r.econPerHour.oreSpent||0)*r.simHours;o.dustE=sum(sh.map(s=>s.gain));o.dustL=r.final.dust;o.final=(r.final.shatters||0)+' '+r.final.zone+' f'+r.final.prog+' Lv'+r.final.partyLv;o.lv72=(r.hourly||[]).filter(x=>x.h<=72).pop();o.lv72=o.lv72?o.lv72.lv:null;o.asc=(r.ascensions||[]).length;
  return o;}
const bossTxt=(o,z)=>Object.entries(o[z]).map(([k,v])=>'run'+k+' '+v.w+'/'+v.n+' atk'+v.atk+' Lv'+f(med(v.lv),0)+(v.n-v.w?' loss '+f(med(v.dur),0)+'s '+f(100*(med(v.hp)||0),0)+'%':'')+(v.sum?' summon'+v.sum:'')).join(' | ')||'none';
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'   control '+A+' -> candidate '+B);
  const MA=[],MB=[],V={h:0,cap:0,audit:0,n:0};
  for(let s=S0;s<S0+N;s++){const a=rd(A,p,s),b=rd(B,p,s);if(!a||!b){console.log('seed '+s+': missing');continue;}const ma=m(a),mb=m(b);MA.push(ma);MB.push(mb);V.n++;
    if(mb.simH>=71.9)V.h++;if(mb.nsh<=3)V.cap++;
    const h0=a.shatters[0]?a.shatters[0].h:1e9;const ra=(a.hourly||[]).filter(g=>g.h<h0),rb=(b.hourly||[]).filter(g=>g.h<h0);let same=0;for(let i=0;i<Math.min(ra.length,rb.length);i++)if(JSON.stringify(ra[i])===JSON.stringify(rb[i]))same++;
    const s0=a.shatters[0],s1=b.shatters[0];const shSame=!!s0&&!!s1&&s0.h===s1.h&&s0.zone===s1.zone&&s0.gain===s1.gain&&s0.lv===s1.lv&&s0.power===s1.power&&s0.dustBefore===s1.dustBefore;
    const buysSame=JSON.stringify((a.dustBuys||[]).filter(x=>x.h<h0))===JSON.stringify((b.dustBuys||[]).filter(x=>x.h<h0));
    const r0=z=>{const x=(a.bossFailRates||{})[z],y=(b.bossFailRates||{})[z];const fa=x?x.attemptLog.filter(t=>(t.run||0)===0).map(t=>[t.n,t.win,t.bossAtk,t.dur]):[],fb=y?y.attemptLog.filter(t=>(t.run||0)===0).map(t=>[t.n,t.win,t.bossAtk,t.dur]):[];return JSON.stringify(fa)===JSON.stringify(fb);};
    const run0Same=['Stillwater Lagoon','Thornwood','Ironvein Caverns','Emberwaste','Amberfall Woods',APP,KEEP].every(r0);
    const ok=same===ra.length&&ra.length===rb.length&&shSame&&buysSame&&run0Same;if(ok)V.audit++;
    console.log('\nseed '+s+'  hours '+f(mb.simH,2)+'  Shatters '+ma.nsh+' -> '+mb.nsh+'  audit through first Shatter: hourly '+same+'/'+ra.length+', first Shatter '+(shSame?'same':'DIFFERS')+', dust buys '+(buysSame?'same':'DIFFER')+', run-0 boss attempts '+(run0Same?'same':'DIFFER')+' -> '+(ok?'OK':'MISMATCH'));
    console.log('  Shatters: '+ma.sh.map(x=>'h'+x.h+' '+x.zone.split(' ')[0]+' +'+x.gain).join(', ')+'  ->  '+mb.sh.map(x=>'h'+x.h+' '+x.zone.split(' ')[0]+' +'+x.gain).join(', ')+' (min gap '+f(mb.gapMin,1)+'h)');
    const runTxt=o=>Object.entries(o.runs).map(([k,v])=>'run'+k+': '+v.clears+'z'+(v.app!=null?' App@'+v.app:'')+(v.keepIn!=null?' Keep in@'+v.keepIn+' Lv'+v.keepLv:'')+(v.keep!=null?' KEEP CLEAR@'+v.keep:'')).join(' ; ');
    console.log('  runs: '+runTxt(ma)+'\n     -> '+runTxt(mb));
    console.log('  Keep ordinary: enc '+ma.keepEnc+' L'+ma.keepLoss+' ('+f(ma.keepLossPct,0)+'%) far '+ma.keepFar+' '+f(ma.keepH,1)+'h  ->  enc '+mb.keepEnc+' L'+mb.keepLoss+' ('+f(mb.keepLossPct,0)+'%) far '+mb.keepFar+' '+f(mb.keepH,1)+'h');
    console.log('  Grave Knight: '+bossTxt(ma,'gk')+'\n     -> '+bossTxt(mb,'gk'));
    console.log('  Hollow King: '+bossTxt(ma,'hk')+'\n     -> '+bossTxt(mb,'hk')+(mb.keepClears.length?'   KEEP CLEARED '+mb.keepClears.join(' '):'')+(mb.foundry.length?'   FOUNDRY '+mb.foundry.join(' '):''));
    console.log('  zones cur/best '+H.map(h=>h+'h '+ma.zAt[h].join('/')+'->'+mb.zAt[h].join('/')).join(', ')+' | defeats '+ma.def+'->'+mb.def+' | training '+f(ma.train,1)+'->'+f(mb.train,1)+'h | gold '+f(ma.gold,1)+'->'+f(mb.gold,1)+'M | ore '+Math.round(ma.ore/1000)+'K->'+Math.round(mb.ore/1000)+'K | dust '+ma.dustE+'/'+ma.dustL+'->'+mb.dustE+'/'+mb.dustL+' | Lv@72h '+ma.lv72+'->'+mb.lv72+' | final '+ma.final+' -> '+mb.final);}
  console.log('\n-- '+p+' validity: 72h '+V.h+'/'+V.n+', Shatter cap '+V.cap+'/'+V.n+', audit through first Shatter OK '+V.audit+'/'+V.n+', ascensions '+sum(MB.map(x=>x.asc)));
  const agg=(M,z)=>{const t={};for(const o of M)for(const [k,v] of Object.entries(o[z])){t[k]=t[k]||{n:0,w:0,runs:0,sum:0,dur:[],hp:[]};t[k].n+=v.n;t[k].w+=v.w;t[k].runs++;t[k].sum+=v.sum;t[k].dur=t[k].dur.concat(v.dur);t[k].hp=t[k].hp.concat(v.hp);}return Object.entries(t).map(([k,v])=>'run'+k+' '+v.w+'/'+v.n+' over '+v.runs+' runs (loss med '+f(med(v.dur),0)+'s '+f(100*(med(v.hp)||0),0)+'% HP, summons '+v.sum+')').join(' | ')||'none';};
  console.log('-- '+p+' summary:');
  console.log('   zones cur/best med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][0]))+'/'+med(MA.map(x=>x.zAt[h][1]))+'->'+med(MB.map(x=>x.zAt[h][0]))+'/'+med(MB.map(x=>x.zAt[h][1]))).join(', '));
  console.log('   Shatters per run '+pair(MA.map(x=>x.nsh),MB.map(x=>x.nsh),0)+' | first h '+pair(MA.map(x=>x.sh[0]&&x.sh[0].h),MB.map(x=>x.sh[0]&&x.sh[0].h),1)+' | min gap h '+pair(MA.map(x=>x.gapMin),MB.map(x=>x.gapMin),1));
  for(const rk of ['1','2','3']){const ka=MA.map(x=>x.runs[rk]&&x.runs[rk].keepIn),kb=MB.map(x=>x.runs[rk]&&x.runs[rk].keepIn);const la=MA.map(x=>x.runs[rk]&&x.runs[rk].keepLv),lb=MB.map(x=>x.runs[rk]&&x.runs[rk].keepLv);const aa=MA.map(x=>x.runs[rk]&&x.runs[rk].app),ab=MB.map(x=>x.runs[rk]&&x.runs[rk].app);console.log('   run'+rk+': Ashen Approach cleared '+aa.filter(v=>v!=null).length+'->'+ab.filter(v=>v!=null).length+' runs (h '+f(med(aa),1)+'->'+f(med(ab),1)+'); Keep entered '+ka.filter(v=>v!=null).length+'->'+kb.filter(v=>v!=null).length+' (h '+f(med(ka),1)+'->'+f(med(kb),1)+', Lv '+f(med(la),0)+'->'+f(med(lb),0)+'); Keep cleared '+MA.filter(x=>x.runs[rk]&&x.runs[rk].keep!=null).length+'->'+MB.filter(x=>x.runs[rk]&&x.runs[rk].keep!=null).length);}
  console.log('   Keep ordinary (all runs): encounters '+pair(MA.map(x=>x.keepEnc),MB.map(x=>x.keepEnc),0)+' | loss% '+pair(MA.map(x=>x.keepLossPct),MB.map(x=>x.keepLossPct),0)+' | furthest '+pair(MA.map(x=>x.keepFar),MB.map(x=>x.keepFar),0)+' | hours '+pair(MA.map(x=>x.keepH),MB.map(x=>x.keepH),1)+' | fight 36 reached '+MA.filter(x=>x.fight36).length+'->'+MB.filter(x=>x.fight36).length+' runs');
  console.log('   Grave Knight by run: '+agg(MA,'gk')+'\n     -> '+agg(MB,'gk'));
  console.log('   Hollow King by run: '+agg(MA,'hk')+'\n     -> '+agg(MB,'hk')+'\n   Keep clears (runs) '+MA.filter(x=>x.keepClears.length).length+'->'+MB.filter(x=>x.keepClears.length).length+', Foundry entries '+MA.filter(x=>x.foundry.length).length+'->'+MB.filter(x=>x.foundry.length).length);
  console.log('   totals: defeats '+pair(MA.map(x=>x.def),MB.map(x=>x.def),0)+' | training h '+pair(MA.map(x=>x.train),MB.map(x=>x.train),1)+' | gold earned M '+pair(MA.map(x=>x.gold),MB.map(x=>x.gold),2)+' | ore earned '+pair(MA.map(x=>x.ore),MB.map(x=>x.ore),0)+' | dust earned '+pair(MA.map(x=>x.dustE),MB.map(x=>x.dustE),0)+' | Lv@72h '+pair(MA.map(x=>x.lv72),MB.map(x=>x.lv72),0));
}
