// Pass 26 fresh-seed validation report: paired control (override 1.25) vs production candidate (1.10) on the Shatter road.
// Validity/audit, horizons, Shatters (gaps, zones re-cleared between), full-Road clear times per run, Keep ordinary, four bosses by run and window, Keep/Foundry/Endless, totals, outliers.
// Usage: node tests/sim/validate26.js --a batch_out_p26c --b batch_out_p26x [--profiles idle,light,casual,engaged] [--seedStart 41 --seeds 10]
'use strict';
const fs=require('fs'),path=require('path');
const args=(()=>{const a={};const v=process.argv.slice(2);for(let i=0;i<v.length;i++){if(v[i].startsWith('--')){const k=v[i].slice(2),n=v[i+1];if(n&&!n.startsWith('--')){a[k]=isNaN(Number(n))?n:Number(n);i++;}else a[k]=true;}}return a;})();
const A=String(args.a||'batch_out_p26c'),B=String(args.b||'batch_out_p26x'),P=String(args.profiles||'idle,light,casual,engaged').split(','),S0=args.seedStart||41,N=args.seeds||10,H=[24,36,48,60,72];
const KEEP='Ashen Keep',APP='Ashen Approach',FND='The Foundry',END='The Endless Road';const BOSSES=[['Emberwaste','Sand Tyrant'],['Amberfall Woods','Hunter King'],[APP,'Grave Knight'],[KEEP,'Hollow King']];
const ZO=['Greenhollow Fields','Stillwater Lagoon','Thornwood','Ironvein Caverns','Emberwaste','Amberfall Woods',APP,KEEP,FND];
const srt=a=>a.filter(v=>v!=null&&!isNaN(v)).sort((x,y)=>x-y),med=a=>{a=srt(a);return a.length?a[Math.floor((a.length-1)/2)]:null},f=(v,d=1)=>v==null?'-':(+v).toFixed(d),sum=a=>a.reduce((x,y)=>x+(y||0),0);
const rd=(d,p,s)=>{const fp=path.join(__dirname,d,p+'_'+s+'.json');return fs.existsSync(fp)?JSON.parse(fs.readFileSync(fp,'utf8')):null;};
const pair=(va,vb,d=1)=>{const dd=va.map((v,i)=>(vb[i]==null||v==null)?null:vb[i]-v).filter(x=>x!=null);return 'med '+f(med(va),d)+' -> '+f(med(vb),d)+(dd.length?' (paired med '+f(med(dd),d)+', +'+dd.filter(x=>x>0).length+' 0'+dd.filter(x=>x===0).length+' -'+dd.filter(x=>x<0).length+')':'');};
function m(r){const o={};const rz=r.runZones||{},rc=r.runClears||{},sh=r.shatters||[],spe=(r.deadTime&&r.deadTime.secPerEncounter)||60;
  o.simH=r.simHours;o.nsh=sh.length;o.sh=sh;o.gapMin=sh.length>1?Math.min(...sh.slice(1).map((s,i)=>s.h-sh[i].h)):null;o.reclearMin=sh.length>1?Math.min(...sh.slice(1).map((s,i)=>Object.keys(rc[String((sh[i].run||0)+1)]||{}).length)):null;
  o.zAt={};for(const h of H){let cur=0,best=0;for(const rk of Object.keys(rc)){const c=Object.values(rc[rk]).filter(t=>t<=h).length;best=Math.max(best,c);const started=rk==='0'?0:(sh[Number(rk)-1]?sh[Number(rk)-1].h:1e9);if(started<=h)cur=c;}o.zAt[h]=[cur,best];}
  o.runs={};for(const rk of Object.keys(rc)){const c=rc[rk],z=rz[rk]||{};o.runs[rk]={clears:Object.keys(c).length,list:ZO.filter(zz=>c[zz]!=null).map(zz=>zz.split(' ')[0].slice(0,4)+'@'+f(c[zz],1)).join(' '),keepIn:z[KEEP]?z[KEEP].enterH:null,keepLv:z[KEEP]?z[KEEP].lvAtEntry:null,keep:c[KEEP],fnd:c[FND],fndIn:z[FND]?z[FND].enterH:null,fndLv:z[FND]?z[FND].lvAtEntry:null,fndPw:z[FND]?z[FND].power:null,endIn:z[END]?z[END].enterH:null};}
  const bz=(r.byZone||{})[KEEP]||{},zt=(r.zoneTime||{})[KEEP]||{sec:0};o.keepEnc=Math.round(zt.sec/spe);o.keepLoss=bz.defeats||0;o.keepLossPct=o.keepEnc?100*o.keepLoss/o.keepEnc:null;o.keepH=zt.sec/3600;o.keepFar=Math.max(0,...(r.hourly||[]).filter(g=>g.zone===KEEP).map(g=>g.prog),...sh.filter(s=>s.zone===KEEP).map(s=>s.farMark||0),r.final.zone===KEEP?r.final.prog:0);o.fight36=!!(r.bossFailRates||{})[KEEP];
  o.boss={};for(const [z,name] of BOSSES){const b=(r.bossFailRates||{})[z];const out={};if(b)for(const a of b.attemptLog){if(a.run==null||a.win==null)continue;const k=String(a.run),w=a.window==='auto'?'auto':'act';out[k]=out[k]||{auto:[0,0],act:[0,0],atk:a.bossAtk,dur:[],hp:[],sum:0,lv:[]};out[k][w][1]++;if(a.win)out[k][w][0]++;out[k].dur.push(a.dur);out[k].hp.push(a.hpLeft);if(a.summoned)out[k].sum++;out[k].lv.push(a.lv);}o.boss[name]=out;}
  o.keepClears=Object.keys(rc).filter(k=>rc[k][KEEP]!=null).map(k=>({run:+k,h:rc[k][KEEP]}));o.fndClears=Object.keys(rc).filter(k=>rc[k][FND]!=null).map(k=>({run:+k,h:rc[k][FND]}));o.fndIn=Object.keys(rz).filter(k=>rz[k][FND]).map(k=>({run:+k,h:rz[k][FND].enterH,lv:rz[k][FND].lvAtEntry,pw:rz[k][FND].power}));o.endIn=Object.keys(rz).filter(k=>rz[k][END]).map(k=>({run:+k,h:rz[k][END].enterH,lv:rz[k][END].lvAtEntry}));o.endless=r.endless||{};
  o.afterKeep=o.keepClears.length?r.simHours-Math.min(...o.keepClears.map(c=>c.h)):null;
  o.def=r.final.defeats||0;o.train=(r.autoTrain&&r.autoTrain.timeSec||0)/3600;o.gold=(r.econPerHour.goldEarned||0)*r.simHours/1e6;o.goldSp=(r.econPerHour.goldSpent||0)*r.simHours/1e6;o.ore=(r.econPerHour.oreEarned||0)*r.simHours;o.dustE=sum(sh.map(s=>s.gain));o.dustL=r.final.dust;o.final=(r.final.shatters||0)+' '+r.final.zone+' f'+r.final.prog+' Lv'+r.final.partyLv;const l72=(r.hourly||[]).filter(x=>x.h<=72).pop();o.lv72=l72?l72.lv:null;o.asc=(r.ascensions||[]).length;
  return o;}
const bossTxt=(o,name)=>Object.entries(o.boss[name]).map(([k,v])=>'r'+k+' auto '+v.auto[0]+'/'+v.auto[1]+' act '+v.act[0]+'/'+v.act[1]+' atk'+v.atk+(v.dur.length?' L'+f(med(v.dur),0)+'s '+f(100*(med(v.hp)||0),0)+'%':'')+(v.sum?' sum'+v.sum:'')).join(' | ')||'none';
for(const p of P){
  console.log('\n===== '+p.toUpperCase()+'   control '+A+' (1.25 override) -> candidate '+B+' (production 1.10)');
  const MA=[],MB=[],V={h:0,cap:0,audit:0,n:0},outliers=[];
  for(let s=S0;s<S0+N;s++){const a=rd(A,p,s),b=rd(B,p,s);if(!a||!b){console.log('seed '+s+': missing');continue;}const ma=m(a),mb=m(b);MA.push(ma);MB.push(mb);V.n++;
    if(ma.simH>=71.9&&mb.simH>=71.9)V.h++;if(ma.nsh<=3&&mb.nsh<=3)V.cap++;
    const h0=a.shatters[0]?a.shatters[0].h:1e9;const ra=(a.hourly||[]).filter(g=>g.h<h0),rb=(b.hourly||[]).filter(g=>g.h<h0);let same=0;for(let i=0;i<Math.min(ra.length,rb.length);i++)if(JSON.stringify(ra[i])===JSON.stringify(rb[i]))same++;
    const s0=a.shatters[0],s1=b.shatters[0];const shSame=(!s0&&!s1)||(!!s0&&!!s1&&s0.h===s1.h&&s0.zone===s1.zone&&s0.gain===s1.gain&&s0.lv===s1.lv&&s0.power===s1.power&&s0.dustBefore===s1.dustBefore);
    const buysSame=JSON.stringify((a.dustBuys||[]).filter(x=>x.h<h0))===JSON.stringify((b.dustBuys||[]).filter(x=>x.h<h0));
    const r0=z=>{const x=(a.bossFailRates||{})[z],y=(b.bossFailRates||{})[z];const fa=x?x.attemptLog.filter(t=>t.run===0).map(t=>[t.n,t.win,t.bossAtk,t.dur]):[],fb=y?y.attemptLog.filter(t=>t.run===0).map(t=>[t.n,t.win,t.bossAtk,t.dur]):[];return JSON.stringify(fa)===JSON.stringify(fb);};
    const run0Same=ZO.every(r0);const ok=same===ra.length&&ra.length===rb.length&&shSame&&buysSame&&run0Same;if(ok)V.audit++;
    console.log('\nseed '+s+'  hours '+f(ma.simH,2)+'/'+f(mb.simH,2)+'  Shatters '+ma.nsh+' -> '+mb.nsh+'  audit through first Shatter: hourly '+same+'/'+ra.length+', first Shatter '+(shSame?'same':'DIFFERS')+', dust buys '+(buysSame?'same':'DIFFER')+', run-0 boss attempts '+(run0Same?'same':'DIFFER')+' -> '+(ok?'OK':'MISMATCH'));
    console.log('  Shatters: '+ma.sh.map(x=>'h'+x.h+' '+x.zone.split(' ')[0]+' +'+x.gain).join(', ')+'  ->  '+mb.sh.map(x=>'h'+x.h+' '+x.zone.split(' ')[0]+' +'+x.gain).join(', ')+' (min gap '+f(ma.gapMin,1)+'->'+f(mb.gapMin,1)+'h, min zones re-cleared between '+ma.reclearMin+'->'+mb.reclearMin+')');
    const runTxt=o=>Object.entries(o.runs).map(([k,v])=>'run'+k+' ['+v.list+']'+(v.keepIn!=null?' Keep in@'+v.keepIn+' Lv'+v.keepLv:'')+(v.fndIn!=null?' FOUNDRY in@'+v.fndIn+' Lv'+v.fndLv+' pw'+v.fndPw:'')+(v.endIn!=null?' ENDLESS in@'+v.endIn:'')).join(' ; ');
    console.log('  runs: '+runTxt(ma)+'\n     -> '+runTxt(mb));
    console.log('  Keep ordinary: enc '+ma.keepEnc+' L'+ma.keepLoss+' ('+f(ma.keepLossPct,0)+'%) far '+ma.keepFar+' '+f(ma.keepH,1)+'h  ->  enc '+mb.keepEnc+' L'+mb.keepLoss+' ('+f(mb.keepLossPct,0)+'%) far '+mb.keepFar+' '+f(mb.keepH,1)+'h'+(mb.endless.best?'  | Endless best '+ma.endless.best+'->'+mb.endless.best+' milestones '+ma.endless.milestones+'->'+mb.endless.milestones:''));
    for(const [,name] of BOSSES)console.log('  '+name+': '+bossTxt(ma,name)+'\n     -> '+bossTxt(mb,name));
    console.log('  zones cur/best '+H.map(h=>h+'h '+ma.zAt[h].join('/')+'->'+mb.zAt[h].join('/')).join(', ')+' | defeats '+ma.def+'->'+mb.def+' | training '+f(ma.train,1)+'->'+f(mb.train,1)+'h | gold '+f(ma.gold,1)+'->'+f(mb.gold,1)+'M | ore '+Math.round(ma.ore/1000)+'K->'+Math.round(mb.ore/1000)+'K | dust '+ma.dustE+'/'+ma.dustL+'->'+mb.dustE+'/'+mb.dustL+' | Lv@72h '+ma.lv72+'->'+mb.lv72+' | final '+ma.final+' -> '+mb.final);
    const gd=ma.gold?100*(mb.gold-ma.gold)/ma.gold:null;if(mb.endIn.length||(gd!=null&&Math.abs(gd)>30)||mb.fndClears.length)outliers.push('seed '+s+': '+(mb.endIn.length?'Endless entered run'+mb.endIn[0].run+' @'+mb.endIn[0].h+'h Lv'+mb.endIn[0].lv+' (best wave '+mb.endless.best+'); ':'')+(mb.fndClears.length?'Foundry cleared '+mb.fndClears.map(c=>'run'+c.run+'@'+c.h).join(' ')+'; ':'')+(gd!=null&&Math.abs(gd)>30?'gold earned '+f(gd,0)+'%':''));}
  console.log('\n-- '+p+' validity: 72h '+V.h+'/'+V.n+', Shatter cap '+V.cap+'/'+V.n+', audit through first Shatter OK '+V.audit+'/'+V.n+', ascensions '+sum(MA.map(x=>x.asc))+'->'+sum(MB.map(x=>x.asc)));
  const agg=(M,name)=>{const t={};for(const o of M)for(const [k,v] of Object.entries(o.boss[name])){t[k]=t[k]||{auto:[0,0],act:[0,0],runs:0,sum:0,dur:[],hp:[]};t[k].auto[0]+=v.auto[0];t[k].auto[1]+=v.auto[1];t[k].act[0]+=v.act[0];t[k].act[1]+=v.act[1];t[k].runs++;t[k].sum+=v.sum;t[k].dur=t[k].dur.concat(v.dur);t[k].hp=t[k].hp.concat(v.hp);}return Object.entries(t).map(([k,v])=>'r'+k+' auto '+v.auto[0]+'/'+v.auto[1]+' act '+v.act[0]+'/'+v.act[1]+' ('+v.runs+' runs, loss '+f(med(v.dur),0)+'s '+f(100*(med(v.hp)||0),0)+'%, sum'+v.sum+')').join(' | ')||'none';};
  console.log('-- '+p+' summary:');
  console.log('   zones cur/best med '+H.map(h=>h+'h '+med(MA.map(x=>x.zAt[h][0]))+'/'+med(MA.map(x=>x.zAt[h][1]))+'->'+med(MB.map(x=>x.zAt[h][0]))+'/'+med(MB.map(x=>x.zAt[h][1]))).join(', '));
  console.log('   Shatters per run '+pair(MA.map(x=>x.nsh),MB.map(x=>x.nsh),0)+' | first h '+pair(MA.map(x=>x.sh[0]&&x.sh[0].h),MB.map(x=>x.sh[0]&&x.sh[0].h),1)+' | min gap h '+pair(MA.map(x=>x.gapMin),MB.map(x=>x.gapMin),1)+' | min zones re-cleared between '+pair(MA.map(x=>x.reclearMin),MB.map(x=>x.reclearMin),0));
  for(const rk of ['1','2','3']){const ka=MA.map(x=>x.runs[rk]&&x.runs[rk].keepIn),kb=MB.map(x=>x.runs[rk]&&x.runs[rk].keepIn);const la=MA.map(x=>x.runs[rk]&&x.runs[rk].keepLv),lb=MB.map(x=>x.runs[rk]&&x.runs[rk].keepLv);console.log('   run'+rk+': Keep entered '+ka.filter(v=>v!=null).length+'->'+kb.filter(v=>v!=null).length+' runs (h '+f(med(ka),1)+'->'+f(med(kb),1)+', Lv '+f(med(la),0)+'->'+f(med(lb),0)+'); Keep cleared '+MA.filter(x=>x.runs[rk]&&x.runs[rk].keep!=null).length+'->'+MB.filter(x=>x.runs[rk]&&x.runs[rk].keep!=null).length+'; Foundry entered '+MA.filter(x=>x.runs[rk]&&x.runs[rk].fndIn!=null).length+'->'+MB.filter(x=>x.runs[rk]&&x.runs[rk].fndIn!=null).length+', cleared '+MA.filter(x=>x.runs[rk]&&x.runs[rk].fnd!=null).length+'->'+MB.filter(x=>x.runs[rk]&&x.runs[rk].fnd!=null).length+'; Endless entered '+MA.filter(x=>x.runs[rk]&&x.runs[rk].endIn!=null).length+'->'+MB.filter(x=>x.runs[rk]&&x.runs[rk].endIn!=null).length);}
  console.log('   Keep ordinary (all runs): encounters '+pair(MA.map(x=>x.keepEnc),MB.map(x=>x.keepEnc),0)+' | loss% '+pair(MA.map(x=>x.keepLossPct),MB.map(x=>x.keepLossPct),0)+' | furthest '+pair(MA.map(x=>x.keepFar),MB.map(x=>x.keepFar),0)+' | hours '+pair(MA.map(x=>x.keepH),MB.map(x=>x.keepH),1)+' | fight 36 reached '+MA.filter(x=>x.fight36).length+'->'+MB.filter(x=>x.fight36).length+' runs | Keep clears '+MA.filter(x=>x.keepClears.length).length+'->'+MB.filter(x=>x.keepClears.length).length+' | hours after first Keep clear med '+f(med(MA.map(x=>x.afterKeep)),1)+'->'+f(med(MB.map(x=>x.afterKeep)),1));
  for(const [,name] of BOSSES)console.log('   '+name+' by run: '+agg(MA,name)+'\n     -> '+agg(MB,name));
  console.log('   totals: defeats '+pair(MA.map(x=>x.def),MB.map(x=>x.def),0)+' | training h '+pair(MA.map(x=>x.train),MB.map(x=>x.train),1)+' | gold earned M '+pair(MA.map(x=>x.gold),MB.map(x=>x.gold),2)+' | ore earned '+pair(MA.map(x=>x.ore),MB.map(x=>x.ore),0)+' | dust earned '+pair(MA.map(x=>x.dustE),MB.map(x=>x.dustE),0)+' | Lv@72h '+pair(MA.map(x=>x.lv72),MB.map(x=>x.lv72),0));
  console.log('   outliers (candidate): '+(outliers.length?outliers.join(' || '):'none'));
}
