// Pass 51 audit fixes, all through PRODUCTION functions: attention on kill XP, the warp without attention, drill isolation of stats /
// roundTick / shake, villager assignments after a horde loss, castle storage never shrinking, entry consumption saved before the
// activity blocks saving, developer controls hidden off a ?dev page, and the drill targets without the rejected scalar.
// Run: node tests/contract/audit.test.js   (exit code 1 on any failure)
'use strict';
const H=require('../sim/headless.js');
let pass=0,fail=0;const out=[];
function ok(c,m){if(c)pass++;else{fail++;out.push('FAIL '+m);}}
function near(a,b,eps,m){ok(Math.abs(a-b)<=eps,m+' (got '+a+', want '+b+')');}
async function game(seed=1){const S=H.load({seed,startMs:1700000000000});await S.ready;const G=S.G;G.title=false;G.tut=null;G.mult='max';G.screen='vael';for(const def of S.HEROES.slice(0,4)){if(!G.roster.find(h=>h.id===def.id))S.addHero(def,30);}G.active=G.roster.slice(0,4);G.campfireDone=true;for(const h of G.roster){h.lvl=30;S.refreshStats(h);h.hp=h.maxhp;h.charge=0;}return S;}
function toBattle(S){const G=S.G;G.zone=0;G.mode='walk';G.enc=0.01;let n=0;while(G.mode!=='battle'&&n<30000){S.setRT(S.getRT()+1/60);S.clock.frame();G.tut=null;S.update(1/60,true);n++;}if(G.mode!=='battle')throw new Error('no battle');}
(async()=>{
  // ---- attention multiplies kill XP exactly like kill gold (production killReward)
  {const S=await game(),G=S.G;toBattle(S);const e=G.enemies.find(x=>!x.dead);const snap=()=>({xp:G.active.reduce((a,h)=>a+h.xp,0),gold:G.gold});S.setRT(1000);G.attnUntil=0;e.lvl=40;for(const h of G.active){h.lvl=200;h.xp=0;} /* far from a level-up, so XP only accumulates */const a0=snap();for(let k=0;k<20;k++)S.killReward(e);const a1=snap();S.noteAttention();const b0=snap();for(let k=0;k<20;k++)S.killReward(e);const b1=snap();const xr=(b1.xp-b0.xp)/Math.max(1,a1.xp-a0.xp);near(xr,1.25,0.02,'kill XP with attention is 1.25x the kill XP without (20 kills each)');ok(b1.gold-b0.gold>a1.gold-a0.gold,'kill gold rises with attention as before');}
  // ---- the time warp ignores attention entirely
  {const S=await game(),G=S.G;G.castle.b.mine=2;G.castle.vil.mine=3;S.setRT(2000);G.attnUntil=0;const w0=S.warpGains();S.noteAttention();ok(S.attnOn(),'attention on');const w1=S.warpGains();ok(w0.gold===w1.gold&&w0.xp===w1.xp&&w0.ore===w1.ore,'warp gold, XP and ore are identical with and without attention ('+w0.gold+' vs '+w1.gold+')');ok(S.attnOn(),'attention is still on afterwards (restored)');}
  // ---- drill isolation: stats, roundTick and shake belong to the drill
  {const S=await game(),G=S.G;const mage=G.roster.find(h=>h.cls==='mage')||G.roster[0];G.stats.casts=5;G.stats.taps=7;G.roundTick=7;G.shake=0;const tap0=((G.stats.dmgBy||{}).tap)||0;const br=S.drillBrackets()[0];ok(S.startDrill(mage,br),'drill starts');let f=0;const rt0=Math.ceil(S.getRT());while(G.drill.running&&f<60*40){S.clock.frame();f++;S.setRT(rt0+f/60);S.update(1/60,true);S.drillTick(1/60);if(f%30===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}ok(!G.drill.running,'drill finished');ok(G.stats.casts===5,'road casts untouched by the drill (got '+G.stats.casts+')');ok(G.stats.taps===7,'road tap count untouched (got '+G.stats.taps+')');ok(G.roundTick===7,'road roundTick untouched (got '+G.roundTick+')');ok(G.shake<=1e-9,'no drill shake left on the road (got '+G.shake+')');ok((((G.stats.dmgBy||{}).tap)||0)===tap0,'the drill taps never reach the road tap tally');ok(G.drill.g.stats.casts>0||G.drill.stats.hits>0,'the drill kept its own tallies ('+G.drill.g.stats.casts+' casts)');}
  // ---- horde loss: no villager stays assigned to a job after being lost
  {const S=await game(),G=S.G;const C=G.castle;C.b.mine=1;C.b.market=1;C.vil.total=2;C.vil.mine=1;C.vil.market=1;C.b.walls=0;C.hordeDue=true;S.resolveHorde(false);ok(C.vil.total===0&&C.vil.mine===0&&C.vil.market===0&&S.idleVil()===0,'two villagers lost at the gate: assignments cleared, idle 0 (total '+C.vil.total+', mine '+C.vil.mine+', market '+C.vil.market+', idle '+S.idleVil()+')');}
  // ---- castle storage: a falling rate never deletes what is stored
  {const S=await game(),G=S.G;const C=G.castle;C.b.mine=4;C.vil.total=12;C.vil.mine=12;C.vil.market=0;const rate=S.orePerHour();C.stored.ore=rate*8;C.last=S.gameNow();S.clock.advance(60*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6,'at the cap the store holds ('+C.stored.ore.toFixed(1)+')');C.vil.mine=3;const low=S.orePerHour();ok(low<rate,'rate dropped');C.last=S.gameNow();S.clock.advance(60*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6,'nothing stored was lost when the rate fell ('+C.stored.ore.toFixed(1)+' >= '+(rate*8).toFixed(1)+')');C.last=S.gameNow();S.clock.advance(3600*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6&&C.stored.ore<=rate*8+1e-6,'and it does not grow past the old store while the low rate cannot reach it');}
  // ---- entry consumption is on disk before the activity blocks saving
  {const S=await game(),G=S.G;G.title=false;G.delveKeys=2;G.keyAt=S.gameNow();const h=G.roster[0];S.startDelve(h);ok(!!G.delve,'delve started');const saved=JSON.parse(S.storeGet('crystal_road_save_v1')||'{}');ok(saved.delveKeys===1,'the spent key is already in the save ('+saved.delveKeys+')');}
  {const S=await game(),G=S.G;G.title=false;G.castle.hordeDue=true;G.castle.hordeLog=[];G.castle.b.walls=1;G.zone=0;G.mode='walk';S.startHordeFight();const saved=JSON.parse(S.storeGet('crystal_road_save_v1')||'{}');ok(!!G.hordeFight,'horde fight started');ok(saved.castle&&Array.isArray(saved.castle.hordeLog)&&saved.castle.hordeLog.length===1,'the horde window use is already in the save ('+(saved.castle&&saved.castle.hordeLog&&saved.castle.hordeLog.length)+')');}
  // ---- developer controls are off by default
  {const S=await game();ok(S.DEV_TOOLS===false,'DEV_TOOLS is false without ?dev');}
  // ---- drill targets: the bracket's enemies only, no Shatter scalar
  {const S=await game(),G=S.G;const br=S.drillBrackets()[0];G.reforges=0;G.tree.b_dmg=0;G.tree.b_start=0;const c0=S.drillCrystal(br);G.tree.b_dmg=5;G.tree.b_start=5;ok(S.drillCrystal(br)===c0,'dust ranks do not move the target');G.reforges=2;ok(S.drillCrystal(br)>c0*1.6&&S.drillCrystal(br)<c0*1.8,'two Shatters raise it only through the enemy pool (about 1.69x)');ok(typeof S.shatterCombatScalar==='undefined','the scalar is gone');}
  if(out.length)console.log(out.join('\n'));console.log((fail?'FAIL  ':'PASS  ')+pass+' passed, '+fail+' failed');process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
