// Pass 51 audit fixes, all through PRODUCTION functions: attention on kill XP, the warp without attention, drill isolation of stats /
// roundTick / shake, villager assignments after a horde loss, castle storage never shrinking, entry consumption saved before the
// activity blocks saving, developer controls hidden off a ?dev page, and the drill targets without the rejected scalar.
// Run: node tests/contract/audit.test.js   (exit code 1 on any failure)
'use strict';
const H=require('../sim/headless.js');
let pass=0,fail=0;const out=[];
function ok(c,m){if(c)pass++;else{fail++;out.push('FAIL '+m);}}
function near(a,b,eps,m){ok(Math.abs(a-b)<=eps,m+' (got '+a+', want '+b+')');}
async function game(seed=1){const S=H.load({seed,startMs:1700000000000});await S.ready;const G=S.G;G.title=false;G.tut=null;G.mult='max';G.screen='vael';for(const def of S.HEROES.slice(0,4)){if(!G.roster.find(h=>h.id===def.id))S.addHero(def,30);}G.active=G.roster.slice(0,4);G.campfireDone=true;for(const h of G.roster){h.lvl=30;S.refreshStats(h);h.hp=h.maxhp;h.charge=0;}return S;}
function toBattle(S){const G=S.G;G.zone=0;G.mode='walk';G.enc=0.01;let n=0;while(G.mode!=='battle'&&n<30000){S.setRT(S.getRT()+1/60);S.clock.frame();G.tut=null;S.update(1/60,true);n++;}if(G.mode!=='battle')throw new Error('no battle');}
(async()=>{
  // ---- attention multiplies kill XP exactly like kill gold (production killReward)
  {const S=await game(),G=S.G;toBattle(S);const e=G.enemies.find(x=>!x.dead);const snap=()=>({xp:G.active.reduce((a,h)=>a+h.xp,0),gold:G.gold});S.setRT(1000);G.attnUntil=0;e.lvl=40;for(const h of G.active){h.lvl=200;h.xp=0;} /* far from a level-up, so XP only accumulates */const a0=snap();for(let k=0;k<20;k++)S.killReward(e);const a1=snap();S.noteAttention();const b0=snap();for(let k=0;k<20;k++)S.killReward(e);const b1=snap();const xr=(b1.xp-b0.xp)/Math.max(1,a1.xp-a0.xp);near(xr,1.25,0.02,'kill XP with attention is 1.25x the kill XP without (20 kills each)');ok(b1.gold-b0.gold>a1.gold-a0.gold,'kill gold rises with attention as before');}
  // ---- the time warp ignores attention entirely
  {const S=await game(),G=S.G;G.castle.b.mine=2;G.castle.vil.mine=3;S.setRT(2000);G.attnUntil=0;const w0=S.warpGains();S.noteAttention();ok(S.attnOn(),'attention on');const w1=S.warpGains();ok(w0.gold===w1.gold&&w0.xp===w1.xp&&w0.ore===w1.ore,'warp gold, XP and ore are identical with and without attention ('+w0.gold+' vs '+w1.gold+')');ok(S.attnOn(),'attention is still on afterwards (restored)');}
  // ---- drill isolation: stats, roundTick and shake belong to the drill
  {const S=await game(),G=S.G;const mage=G.roster.find(h=>h.cls==='mage')||G.roster[0];G.stats.casts=5;G.stats.taps=7;G.roundTick=7;G.shake=0;const tap0=((G.stats.dmgBy||{}).tap)||0;const br=S.drillBrackets()[0];ok(S.startDrill(mage,br),'drill starts');let f=0;const rt0=Math.ceil(S.getRT());while(G.drill.running&&f<60*40){S.clock.frame();f++;S.setRT(rt0+f/60);S.update(1/60,true);S.drillTick(1/60);if(f%30===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}ok(!G.drill.running,'drill finished');ok(G.stats.casts===5,'road casts untouched by the drill (got '+G.stats.casts+')');ok(G.stats.taps===7,'road tap count untouched (got '+G.stats.taps+')');ok(G.roundTick===7,'road roundTick untouched (got '+G.roundTick+')');ok(G.shake<=1e-9,'no drill shake left on the road (got '+G.shake+')');ok((((G.stats.dmgBy||{}).tap)||0)===tap0,'the drill taps never reach the road tap tally');ok(G.drill.g.stats.casts>0||G.drill.stats.hits>0,'the drill kept its own tallies ('+G.drill.g.stats.casts+' casts)');}
  // ---- horde loss: no villager stays assigned to a job after being lost
  {const S=await game(),G=S.G;const C=G.castle;C.b.mine=1;C.b.market=1;C.vil.total=2;C.vil.mine=1;C.vil.market=1;C.b.walls=0;C.hordeDue=true;S.resolveHorde(false);ok(C.vil.total===0&&C.vil.mine===0&&C.vil.market===0&&S.idleVil()===0,'two villagers lost at the gate: assignments cleared, idle 0 (total '+C.vil.total+', mine '+C.vil.mine+', market '+C.vil.market+', idle '+S.idleVil()+')');}
  // ---- castle storage: a falling rate never deletes what is stored
  {const S=await game(),G=S.G;const C=G.castle;C.b.mine=4;C.vil.total=12;C.vil.mine=12;C.vil.market=0;const rate=S.orePerHour();C.stored.ore=rate*8;C.last=S.gameNow();S.clock.advance(60*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6,'at the cap the store holds ('+C.stored.ore.toFixed(1)+')');C.vil.mine=3;const low=S.orePerHour();ok(low<rate,'rate dropped');C.last=S.gameNow();S.clock.advance(60*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6,'nothing stored was lost when the rate fell ('+C.stored.ore.toFixed(1)+' >= '+(rate*8).toFixed(1)+')');C.last=S.gameNow();S.clock.advance(3600*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6&&C.stored.ore<=rate*8+1e-6,'and it does not grow past the old store while the low rate cannot reach it');}
  // ---- entry consumption is on disk before the activity blocks saving
  {const S=await game(),G=S.G;G.title=false;G.delveKeys=2;G.keyAt=S.gameNow();const h=G.roster[0];S.startDelve(h);ok(!!G.delve,'delve started');const saved=JSON.parse(S.storeGet('crystal_road_save_v1')||'{}');ok(saved.delveKeys===1,'the spent key is already in the save ('+saved.delveKeys+')');}
  {const S=await game(),G=S.G;G.title=false;G.castle.hordeDue=true;G.castle.hordeLog=[];G.castle.b.walls=1;G.zone=0;G.mode='walk';S.startHordeFight();const saved=JSON.parse(S.storeGet('crystal_road_save_v1')||'{}');ok(!!G.hordeFight,'horde fight started');ok(saved.castle&&Array.isArray(saved.castle.hordeLog)&&saved.castle.hordeLog.length===1,'the horde window use is already in the save ('+(saved.castle&&saved.castle.hordeLog&&saved.castle.hordeLog.length)+')');}
  // ---- developer controls are off by default
  // ---- developer controls: what the Settings sheet actually draws and lets a player tap, on a normal page and on a ?dev page
  {const DEVTEXT=/\bDev\b|Layout:|Fast quests|testing|\+1T|loop seam|milestone boss|auto-cast boost|road speed/i;
    const render=async(search)=>{const S=H.load({seed:1,startMs:1700000000000,search});await S.ready;const G=S.G;G.title=false;G.tut=null;G.screen='road';G.noSave=true;S.openSheet('settings');const seen=[],orig=S.win.text;S.win.text=function(x,y,str){seen.push(String(str));return orig.apply(this,arguments);};try{S.draw();}finally{S.win.text=orig;}
      const rowHits=S.getHits().filter(h=>h.h===22&&(h.w===242||h.w===56)).map(h=>({y:h.y,fn:h.fn}));return{S,G,seen,rowHits};};
    const n=await render('');ok(n.S.DEV_TOOLS===false,'DEV_TOOLS is false without ?dev');ok(n.seen.includes('Settings')&&n.seen.length>5,'the Settings sheet was drawn ('+n.seen.length+' strings)');
    const devShown=n.seen.filter(t=>DEVTEXT.test(t));ok(devShown.length===0,'a normal page draws no developer text ('+devShown.slice(0,3).join(' | ')+')');
    const labels=n.S.settingsRows().map(r=>String(r[0]));ok(labels.length===5&&/^Music /.test(labels[0])&&/^Sound effects /.test(labels[1])&&labels[2]==='Statistics'&&labels[3]==='Backup or restore your save'&&labels[4]==='Reset the road (wipes the save)','a player has five rows: Music, Sound effects, Statistics, Backup or restore, Reset the road');
    ok(labels.every(l=>n.seen.includes(l))&&n.rowHits.length===5,'exactly those five rows are drawn and tappable ('+n.rowHits.length+' row regions)');
    ok(n.rowHits.every(h=>typeof h.fn==='function'),'every row region carries a handler');
    {const G=n.G,S=n.S;G.gold=123;G.ore=45;G.dust=6;const c=G.castle,horde0=c.hordeAt,auto0=G.autoUntil,tiers=G.roster.map(h=>h.tier||0).join(),prog=JSON.stringify(G.prog),far=JSON.stringify(G.far);
      for(const h of n.rowHits.slice(0,4)){h.fn();G.sheet=null;} /* everything a player can tap, except the wipe */
      ok(G.gold===123&&G.ore===45&&G.dust===6,'tapping every row adds no gold, ore or dust');ok(!G.fast&&!G.fastRoad&&G.autoUntil===auto0&&c.hordeAt===horde0,'no testing speed, no road speed, no free boost, no summoned horde');ok(G.roster.map(h=>h.tier||0).join()===tiers&&JSON.stringify(G.prog)===prog&&JSON.stringify(G.far)===far,'no promotion reset and no progression skip');}
    const d=await render('?dev');ok(d.S.DEV_TOOLS===true,'DEV_TOOLS is true on a ?dev page');const dl=d.S.settingsRows().map(r=>String(r[0]));ok(dl.length===16&&d.rowHits.length===16&&dl.filter(l=>DEVTEXT.test(l)).length===11,'a ?dev page draws sixteen rows, eleven of them developer rows');
    ok(dl.every(l=>d.seen.includes(l))&&d.seen.some(t=>/\+1T gold/.test(t)),'and their labels are drawn');ok(labels.every((l,i)=>dl.includes(l))&&dl.indexOf('Statistics')>dl.findIndex(l=>/^Sound/.test(l))&&dl[dl.length-1]===labels[4],'the player rows keep their places among them');
    {const G=d.G,i=dl.findIndex(l=>/\+1T gold/.test(l));G.gold=0;d.rowHits[i].fn();ok(G.gold===1e12,'the developer treasury row works on a ?dev page');}
    // a save cannot carry the testing speed into a normal page
    {const S0=H.load({seed:2,startMs:1700000000000,search:'?dev'});await S0.ready;S0.G.title=false;S0.G.fast=true;const raw=S0.serialize();ok(JSON.parse(raw).fast===true,'a save written with the testing speed on');
      const S1=H.load({seed:2,startMs:1700000000000});await S1.ready;S1.storeSet(raw);ok(S1.loadGame()&&S1.G.fast===false,'loads with the testing speed off on a normal page');
      const S2=H.load({seed:2,startMs:1700000000000,search:'?dev'});await S2.ready;S2.storeSet(raw);ok(S2.loadGame()&&S2.G.fast===true,'and keeps it on a ?dev page');}
    const src=require('fs').readFileSync(require('path').join(__dirname,'..','..','source','game.js'),'utf8');{const a=src.indexOf('function settingsRows(){'),z=src.indexOf('function draw(){'),at=[];const re=/'(Dev[: ]|Layout: |Fast quests)/g;let m;while((m=re.exec(src)))at.push(m.index);ok(a>0&&z>a&&at.length===11&&at.every(i=>i>a&&i<z),'the eleven developer labels live inside settingsRows and nowhere else ('+at.length+')');}ok(/const rows=settingsRows\(\);\s*rows\.forEach\(/.test(src),'the sheet draws the rows of settingsRows and nothing else');}
  // ---- drill targets: the bracket's enemies only, no Shatter scalar
  {const S=await game(),G=S.G;const br=S.drillBrackets()[0];G.reforges=0;G.tree.b_dmg=0;G.tree.b_start=0;const c0=S.drillCrystal(br);G.tree.b_dmg=5;G.tree.b_start=5;ok(S.drillCrystal(br)===c0,'dust ranks do not move the target');G.reforges=2;ok(S.drillCrystal(br)>c0*1.6&&S.drillCrystal(br)<c0*1.8,'two Shatters raise it only through the enemy pool (about 1.69x)');ok(typeof S.shatterCombatScalar==='undefined','the scalar is gone');}
  // ---- the Camp panel makes every Bunks rank usable: ordinary Send rows until more quests are out than fit, then a summary row with the hidden heroes and Send another
  {const S=await game(),G=S.G;const drawn=()=>{const seen=[],sprites=[],ot=S.win.text,od=S.win.drawSprite;S.win.text=function(x,y,str){seen.push(String(str));return ot.apply(this,arguments);};S.win.drawSprite=function(u){sprites.push(u&&u.id);return od.apply(this,arguments);};S.getHits().length=0;try{S.drawCamp();}finally{S.win.text=ot;S.win.drawSprite=od;}return{seen,sprites,hits:S.getHits().filter(h=>h.w===62)};};
    for(const id of ['ash','bram','fitz','kit','lark'])S.addHero(S.HEROES.find(d=>d.id===id),20);G.active=G.roster.slice(0,4);S.layout();const camp=()=>G.roster.filter(h=>S.heroStatus(h)==='camp');const t=S.clock.get();const mk=(h,q,end)=>({hero:h,q:S.QUESTS[q],end});
    G.tree.slots=0;G.quests=[];let r=drawn();ok(S.questSlots()===2&&r.seen.filter(s=>s==='Empty slot').length===2&&r.seen.includes('Locked slot')&&r.hits.length===3,'without Bunks: two empty slots and the locked third row');
    G.tree.slots=3;ok(S.questSlots()===5,'Bunks rank 3 gives five quest slots');const free=camp();
    r=drawn();ok(r.seen.filter(s=>s==='Empty slot').length===3&&r.seen.filter(s=>s==='Send hero').length===3&&!r.seen.some(s=>/more|another|Full/.test(s)),'no quests: three ordinary empty rows, each with Send hero');
    G.quests=[mk(free[0],0,t+900e3),mk(free[1],1,t+1800e3)];r=drawn();ok(r.seen.filter(s=>/^Returns in/.test(s)).length===2&&r.seen.filter(s=>s==='Empty slot').length===1&&r.seen.filter(s=>s==='Send hero').length===1&&!r.seen.some(s=>/more|another/.test(s)),'two quests out: two quest rows from the top and a third ordinary Send hero row');
    G.quests.push(mk(free[2],2,t+3600e3));r=drawn();ok(r.seen.filter(s=>/^Returns in/.test(s)).length===2&&r.seen.includes('1 more on quests')&&r.seen.includes('Quests 3 / 5 · a slot is open')&&r.seen.includes('Send another')&&!r.seen.includes('Empty slot'),'a third quest: two quest rows and the summary row with Send another');
    ok(r.sprites.length===3&&r.sprites[2]===free[2].id,'the hidden quest\'s hero is drawn in the summary row like the others ('+r.sprites.join(',')+')');
    const send=r.hits.find(h=>h.fn&&/openSheet\('send'\)|toast\(/.test(String(h.fn)));ok(!!send,'the summary row is tappable');G.sheet=null;send.fn();ok(G.sheet&&G.sheet.kind==='send','tapping it opens the Send a hero sheet: the fourth and fifth heroes go out from here');G.sheet=null;
    G.quests.push(mk(free[3],3,t-1));r=drawn();ok(r.seen.indexOf('Returned')>=0&&r.seen.indexOf('Returned')<r.seen.findIndex(s=>/^Returns in/.test(s))&&r.seen.includes('2 more on quests')&&r.sprites.length===4,'a returned quest jumps to the top row with Collect; the summary shows the two hidden heroes');
    G.quests.push(mk(camp()[0],0,t+7200e3));r=drawn();ok(G.quests.length===5&&r.seen.includes('3 more on quests')&&r.seen.includes('Quests 5 / 5 · every slot is busy')&&r.seen.includes('Full')&&!r.seen.includes('Send another')&&r.sprites.length===5,'five out: the summary shows three hidden heroes and Full');
    G.tree.slots=1;G.quests=G.quests.slice(0,3);r=drawn();ok(S.questSlots()===3&&r.seen.filter(s=>/^Returns in|^Returned/.test(s)).length===3&&!r.seen.some(s=>/more|another|Full/.test(s)),'Bunks rank 1 with three quests: three quest rows, no summary');
    G.quests=[];ok(S.campItems().length===3&&S.campItems().every(it=>!it.q),'no quests: every open slot listed');}

  // ---- the Shatter summary sheet holds its buttons inside the frame, whatever its rows
  {const S=await game(),G=S.G;G.noSave=true;G.screen='road';G.reforges=2;G.run={start:S.clock.get()-7*3600e3,fights:712,bosses:8,gold:12.7e6,bestFloor:0,endless:0};G.cleared=S.ZONES.map((z,i)=>i<8);for(const h of G.roster)h.lvl=113;
    const check=label=>{S.openSheet('shatter');S.getHits().length=0;S.draw();const hits=S.getHits();const hh=S.shatterSheetH(),frame=hits.find(h=>h.w===254&&h.h===hh),btns=hits.filter(h=>h.w===110&&h.h===22);ok(!!frame&&btns.length===2,label+': the sheet frame and both buttons are drawn');if(frame&&btns.length===2)ok(btns.every(b=>b.y+b.h<=frame.y+frame.h-6&&b.y>frame.y),label+': Begin run and Not yet sit inside the frame (button bottom '+Math.max(...btns.map(b=>b.y+b.h))+', frame bottom '+(frame.y+frame.h)+')');S.closeSheet();};
    G.oath=null;G.tree.b_dust=0;check('no oath, no blessing');G.oath='silence';for(const h of G.roster)S.refreshStats(h);check('an oath');G.tree.b_dust=3;check('an oath and a dust blessing');ok(S.shatterSheetH()>352,'the sheet is taller than the old fixed 352 when the blessing and oath lines are present ('+S.shatterSheetH()+')');G.oath=null;G.tree.b_dust=0;}
  if(out.length)console.log(out.join('\n'));console.log((fail?'FAIL  ':'PASS  ')+pass+' passed, '+fail+' failed');process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
