// Pass 51 audit fixes, all through PRODUCTION functions: attention on kill XP, the warp without attention, drill isolation of stats /
// roundTick / shake, villager assignments after a horde loss, castle storage never shrinking, entry consumption saved before the
// activity blocks saving, developer controls hidden off a ?dev page, and the drill targets without the rejected scalar.
// Run: node tests/contract/audit.test.js   (exit code 1 on any failure)
'use strict';
const H=require('../sim/headless.js');
let pass=0,fail=0;const out=[];
function ok(c,m){if(c)pass++;else{fail++;out.push('FAIL '+m);}}
function near(a,b,eps,m){ok(Math.abs(a-b)<=eps,m+' (got '+a+', want '+b+')');}
async function game(seed=1){const S=H.load({seed,startMs:1700000000000});await S.ready;const G=S.G;G.title=false;G.tut=null;G.mult='max';G.screen='vael';for(const def of S.HEROES.slice(0,4)){if(!G.roster.find(h=>h.id===def.id))S.addHero(def,30);}G.active=G.roster.slice(0,4);G.campfireDone=true;for(const h of G.roster){h.lvl=30;S.refreshStats(h);h.hp=h.maxhp;h.charge=0;}return S;}
function toBattle(S){const G=S.G;G.zone=0;G.mode='walk';G.enc=0.01;let n=0;while(G.mode!=='battle'&&n<30000){S.setRT(S.getRT()+1/60);S.clock.frame();G.tut=null;S.update(1/60,true);n++;}if(G.mode!=='battle')throw new Error('no battle');}
(async()=>{
  // ---- attention multiplies kill XP exactly like kill gold (production killReward)
  {const S=await game(),G=S.G;toBattle(S);const e=G.enemies.find(x=>!x.dead);const snap=()=>({xp:G.active.reduce((a,h)=>a+h.xp,0),gold:G.gold});S.setRT(1000);G.attnUntil=0;e.lvl=40;for(const h of G.active){h.lvl=200;h.xp=0;} /* far from a level-up, so XP only accumulates */const a0=snap();for(let k=0;k<20;k++)S.killReward(e);const a1=snap();S.noteAttention();const b0=snap();for(let k=0;k<20;k++)S.killReward(e);const b1=snap();const xr=(b1.xp-b0.xp)/Math.max(1,a1.xp-a0.xp);near(xr,1.25,0.02,'kill XP with attention is 1.25x the kill XP without (20 kills each)');ok(b1.gold-b0.gold>a1.gold-a0.gold,'kill gold rises with attention as before');}
  // ---- the time warp ignores attention entirely
  {const S=await game(),G=S.G;G.castle.b.mine=2;G.castle.vil.mine=3;S.setRT(2000);G.attnUntil=0;const w0=S.warpGains();S.noteAttention();ok(S.attnOn(),'attention on');const w1=S.warpGains();ok(w0.gold===w1.gold&&w0.xp===w1.xp&&w0.ore===w1.ore,'warp gold, XP and ore are identical with and without attention ('+w0.gold+' vs '+w1.gold+')');ok(S.attnOn(),'attention is still on afterwards (restored)');}
  // ---- drill isolation: stats, roundTick and shake belong to the drill
  {const S=await game(),G=S.G;const mage=G.roster.find(h=>h.cls==='mage')||G.roster[0];G.stats.casts=5;G.stats.taps=7;G.roundTick=7;G.shake=0;const tap0=((G.stats.dmgBy||{}).tap)||0;const br=S.drillBrackets()[0];ok(S.startDrill(mage,br),'drill starts');let f=0;const rt0=Math.ceil(S.getRT());while(G.drill.running&&f<60*40){S.clock.frame();f++;S.setRT(rt0+f/60);S.update(1/60,true);S.drillTick(1/60);if(f%30===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}ok(!G.drill.running,'drill finished');ok(G.stats.casts===5,'road casts untouched by the drill (got '+G.stats.casts+')');ok(G.stats.taps===7,'road tap count untouched (got '+G.stats.taps+')');ok(G.roundTick===7,'road roundTick untouched (got '+G.roundTick+')');ok(G.shake<=1e-9,'no drill shake left on the road (got '+G.shake+')');ok((((G.stats.dmgBy||{}).tap)||0)===tap0,'the drill taps never reach the road tap tally');ok(G.drill.g.stats.casts>0||G.drill.stats.hits>0,'the drill kept its own tallies ('+G.drill.g.stats.casts+' casts)');}
  // ---- horde loss: no villager stays assigned to a job after being lost
  {const S=await game(),G=S.G;const C=G.castle;C.b.mine=1;C.b.market=1;C.vil.total=2;C.vil.mine=1;C.vil.market=1;C.b.walls=0;C.hordeDue=true;S.resolveHorde(false);ok(C.vil.total===0&&C.vil.mine===0&&C.vil.market===0&&S.idleVil()===0,'two villagers lost at the gate: assignments cleared, idle 0 (total '+C.vil.total+', mine '+C.vil.mine+', market '+C.vil.market+', idle '+S.idleVil()+')');}
  // ---- castle storage: a falling rate never deletes what is stored
  {const S=await game(),G=S.G;const C=G.castle;C.b.mine=4;C.vil.total=12;C.vil.mine=12;C.vil.market=0;const rate=S.orePerHour();C.stored.ore=rate*8;C.last=S.gameNow();S.clock.advance(60*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6,'at the cap the store holds ('+C.stored.ore.toFixed(1)+')');C.vil.mine=3;const low=S.orePerHour();ok(low<rate,'rate dropped');C.last=S.gameNow();S.clock.advance(60*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6,'nothing stored was lost when the rate fell ('+C.stored.ore.toFixed(1)+' >= '+(rate*8).toFixed(1)+')');C.last=S.gameNow();S.clock.advance(3600*1000);S.castleTick();ok(C.stored.ore>=rate*8-1e-6&&C.stored.ore<=rate*8+1e-6,'and it does not grow past the old store while the low rate cannot reach it');}
  // ---- entry consumption is on disk before the activity blocks saving
  {const S=await game(),G=S.G;G.title=false;G.delveKeys=2;G.keyAt=S.gameNow();const h=G.roster[0];S.startDelve(h);ok(!!G.delve,'delve started');const saved=JSON.parse(S.storeGet('crystal_road_save_v1')||'{}');ok(saved.delveKeys===1,'the spent key is already in the save ('+saved.delveKeys+')');}
  {const S=await game(),G=S.G;G.title=false;G.castle.hordeDue=true;G.castle.hordeLog=[];G.castle.b.walls=1;G.zone=0;G.mode='walk';S.startHordeFight();const saved=JSON.parse(S.storeGet('crystal_road_save_v1')||'{}');ok(!!G.hordeFight,'horde fight started');ok(saved.castle&&Array.isArray(saved.castle.hordeLog)&&saved.castle.hordeLog.length===1,'the horde window use is already in the save ('+(saved.castle&&saved.castle.hordeLog&&saved.castle.hordeLog.length)+')');}
  // ---- developer controls are off by default
  // ---- developer controls: what the Settings sheet actually draws and lets a player tap, on a normal page and on a ?dev page
  {const DEVTEXT=/\bDev\b|Layout:|Fast quests|testing|\+1T|loop seam|milestone boss|auto-cast boost|road speed/i;
    const render=async(search)=>{const S=H.load({seed:1,startMs:1700000000000,search});await S.ready;const G=S.G;G.title=false;G.tut=null;G.screen='road';G.noSave=true;S.openSheet('settings');const seen=[],orig=S.win.text;S.win.text=function(x,y,str){seen.push(String(str));return orig.apply(this,arguments);};try{S.draw();}finally{S.win.text=orig;}
      const rowHits=S.getHits().filter(h=>h.h===22&&(h.w===242||h.w===56)).map(h=>({y:h.y,fn:h.fn}));return{S,G,seen,rowHits};};
    const n=await render('');ok(n.S.DEV_TOOLS===false,'DEV_TOOLS is false without ?dev');ok(n.seen.includes('Settings')&&n.seen.length>5,'the Settings sheet was drawn ('+n.seen.length+' strings)');
    const devShown=n.seen.filter(t=>DEVTEXT.test(t));ok(devShown.length===0,'a normal page draws no developer text ('+devShown.slice(0,3).join(' | ')+')');
    const labels=n.S.settingsRows().map(r=>String(r[0]));ok(labels.length===5&&/^Music /.test(labels[0])&&/^Sound effects /.test(labels[1])&&labels[2]==='Statistics'&&labels[3]==='Backup or restore your save'&&labels[4]==='Reset the road (wipes the save)','a player has five rows: Music, Sound effects, Statistics, Backup or restore, Reset the road');
    ok(labels.every(l=>n.seen.includes(l))&&n.rowHits.length===5,'exactly those five rows are drawn and tappable ('+n.rowHits.length+' row regions)');
    ok(n.rowHits.every(h=>typeof h.fn==='function'),'every row region carries a handler');
    {const G=n.G,S=n.S;G.gold=123;G.ore=45;G.dust=6;const c=G.castle,horde0=c.hordeAt,auto0=G.autoUntil,tiers=G.roster.map(h=>h.tier||0).join(),prog=JSON.stringify(G.prog),far=JSON.stringify(G.far);
      for(const h of n.rowHits.slice(0,4)){h.fn();G.sheet=null;} /* everything a player can tap, except the wipe */
      ok(G.gold===123&&G.ore===45&&G.dust===6,'tapping every row adds no gold, ore or dust');ok(!G.fast&&!G.fastRoad&&G.autoUntil===auto0&&c.hordeAt===horde0,'no testing speed, no road speed, no free boost, no summoned horde');ok(G.roster.map(h=>h.tier||0).join()===tiers&&JSON.stringify(G.prog)===prog&&JSON.stringify(G.far)===far,'no promotion reset and no progression skip');}
    const d=await render('?dev');ok(d.S.DEV_TOOLS===true,'DEV_TOOLS is true on a ?dev page');const dl=d.S.settingsRows().map(r=>String(r[0]));ok(dl.length===16&&d.rowHits.length===16&&dl.filter(l=>DEVTEXT.test(l)).length===11,'a ?dev page draws sixteen rows, eleven of them developer rows');
    ok(dl.every(l=>d.seen.includes(l))&&d.seen.some(t=>/\+1T gold/.test(t)),'and their labels are drawn');ok(labels.every((l,i)=>dl.includes(l))&&dl.indexOf('Statistics')>dl.findIndex(l=>/^Sound/.test(l))&&dl[dl.length-1]===labels[4],'the player rows keep their places among them');
    {const G=d.G,i=dl.findIndex(l=>/\+1T gold/.test(l));G.gold=0;d.rowHits[i].fn();ok(G.gold===1e12,'the developer treasury row works on a ?dev page');}
    // a save cannot carry the testing speed into a normal page
    {const S0=H.load({seed:2,startMs:1700000000000,search:'?dev'});await S0.ready;S0.G.title=false;S0.G.fast=true;const raw=S0.serialize();ok(JSON.parse(raw).fast===true,'a save written with the testing speed on');
      const S1=H.load({seed:2,startMs:1700000000000});await S1.ready;S1.storeSet(raw);ok(S1.loadGame()&&S1.G.fast===false,'loads with the testing speed off on a normal page');
      const S2=H.load({seed:2,startMs:1700000000000,search:'?dev'});await S2.ready;S2.storeSet(raw);ok(S2.loadGame()&&S2.G.fast===true,'and keeps it on a ?dev page');}
    const src=require('fs').readFileSync(require('path').join(__dirname,'..','..','source','game.js'),'utf8');{const a=src.indexOf('function settingsRows(){'),z=src.indexOf('function draw(){'),at=[];const re=/'(Dev[: ]|Layout: |Fast quests)/g;let m;while((m=re.exec(src)))at.push(m.index);ok(a>0&&z>a&&at.length===11&&at.every(i=>i>a&&i<z),'the eleven developer labels live inside settingsRows and nowhere else ('+at.length+')');}ok(/const rows=settingsRows\(\);[\s\S]{0,220}rows\.forEach\(/.test(src)&&!/const rows=\[\['Music/.test(src),'the sheet draws the rows of settingsRows and nothing else');}
  // ---- drill targets: the bracket's enemies only, no Shatter scalar
  {const S=await game(),G=S.G;const br=S.drillBrackets()[0];G.reforges=0;G.tree.b_dmg=0;G.tree.b_start=0;const c0=S.drillCrystal(br);G.tree.b_dmg=5;G.tree.b_start=5;ok(S.drillCrystal(br)===c0,'dust ranks do not move the target');G.reforges=2;ok(S.drillCrystal(br)>c0*1.6&&S.drillCrystal(br)<c0*1.8,'two Shatters raise it only through the enemy pool (about 1.69x)');ok(typeof S.shatterCombatScalar==='undefined','the scalar is gone');}
  // ---- the Camp panel makes every Bunks rank usable: ordinary Send rows until more quests are out than fit, then a summary row with the hidden heroes and Send another
  {const S=await game(),G=S.G;const drawn=()=>{const seen=[],sprites=[],ot=S.win.text,od=S.win.drawSprite;S.win.text=function(x,y,str){seen.push(String(str));return ot.apply(this,arguments);};S.win.drawSprite=function(u){sprites.push(u&&u.id);return od.apply(this,arguments);};S.getHits().length=0;try{S.drawCamp();}finally{S.win.text=ot;S.win.drawSprite=od;}return{seen,sprites,hits:S.getHits().filter(h=>h.w===62)};};
    for(const id of ['ash','bram','fitz','kit','lark'])S.addHero(S.HEROES.find(d=>d.id===id),20);G.active=G.roster.slice(0,4);S.layout();const camp=()=>G.roster.filter(h=>S.heroStatus(h)==='camp');const t=S.clock.get();const mk=(h,q,end)=>({hero:h,q:S.QUESTS[q],end});
    G.tree.slots=0;G.quests=[];let r=drawn();ok(S.questSlots()===2&&r.seen.filter(s=>s==='Empty slot').length===2&&r.seen.includes('Locked slot')&&r.hits.length===3,'without Bunks: two empty slots and the locked third row');
    G.tree.slots=3;ok(S.questSlots()===5,'Bunks rank 3 gives five quest slots');const free=camp();
    r=drawn();ok(r.seen.filter(s=>s==='Empty slot').length===3&&r.seen.filter(s=>s==='Send hero').length===3&&!r.seen.some(s=>/more|another|Full/.test(s)),'no quests: three ordinary empty rows, each with Send hero');
    G.quests=[mk(free[0],0,t+900e3),mk(free[1],1,t+1800e3)];r=drawn();ok(r.seen.filter(s=>/^Returns in/.test(s)).length===2&&r.seen.filter(s=>s==='Empty slot').length===1&&r.seen.filter(s=>s==='Send hero').length===1&&!r.seen.some(s=>/more|another/.test(s)),'two quests out: two quest rows from the top and a third ordinary Send hero row');
    G.quests.push(mk(free[2],2,t+3600e3));r=drawn();ok(r.seen.filter(s=>/^Returns in/.test(s)).length===2&&r.seen.includes('1 more on quests')&&r.seen.includes('Quests 3 / 5 · a slot is open')&&r.seen.includes('Send another')&&!r.seen.includes('Empty slot'),'a third quest: two quest rows and the summary row with Send another');
    ok(r.sprites.length===3&&r.sprites[2]===free[2].id,'the hidden quest\'s hero is drawn in the summary row like the others ('+r.sprites.join(',')+')');
    const send=r.hits.find(h=>h.fn&&/openSheet\('send'\)|toast\(/.test(String(h.fn)));ok(!!send,'the summary row is tappable');G.sheet=null;send.fn();ok(G.sheet&&G.sheet.kind==='send','tapping it opens the Send a hero sheet: the fourth and fifth heroes go out from here');G.sheet=null;
    G.quests.push(mk(free[3],3,t-1));r=drawn();ok(r.seen.indexOf('Returned')>=0&&r.seen.indexOf('Returned')<r.seen.findIndex(s=>/^Returns in/.test(s))&&r.seen.includes('2 more on quests')&&r.sprites.length===4,'a returned quest jumps to the top row with Collect; the summary shows the two hidden heroes');
    G.quests.push(mk(camp()[0],0,t+7200e3));r=drawn();ok(G.quests.length===5&&r.seen.includes('3 more on quests')&&r.seen.includes('Quests 5 / 5 · every slot is busy')&&r.seen.includes('Full')&&!r.seen.includes('Send another')&&r.sprites.length===5,'five out: the summary shows three hidden heroes and Full');
    G.tree.slots=1;G.quests=G.quests.slice(0,3);r=drawn();ok(S.questSlots()===3&&r.seen.filter(s=>/^Returns in|^Returned/.test(s)).length===3&&!r.seen.some(s=>/more|another|Full/.test(s)),'Bunks rank 1 with three quests: three quest rows, no summary');
    G.quests=[];ok(S.campItems().length===3&&S.campItems().every(it=>!it.q),'no quests: every open slot listed');}

  // ---- the Shatter summary sheet holds its buttons inside the frame, whatever its rows
  {const S=await game(),G=S.G;G.noSave=true;G.screen='road';G.reforges=2;G.run={start:S.clock.get()-7*3600e3,fights:712,bosses:8,gold:12.7e6,bestFloor:0,endless:0};G.cleared=S.ZONES.map((z,i)=>i<8);for(const h of G.roster)h.lvl=113;
    const check=label=>{S.openSheet('shatter');S.getHits().length=0;S.draw();const hits=S.getHits();const hh=S.shatterSheetH(),frame=hits.find(h=>h.w===254&&h.h===hh),btns=hits.filter(h=>h.w===110&&h.h===22);ok(!!frame&&btns.length===2,label+': the sheet frame and both buttons are drawn');if(frame&&btns.length===2)ok(btns.every(b=>b.y+b.h<=frame.y+frame.h-6&&b.y>frame.y),label+': Begin run and Not yet sit inside the frame (button bottom '+Math.max(...btns.map(b=>b.y+b.h))+', frame bottom '+(frame.y+frame.h)+')');S.closeSheet();};
    G.oath=null;G.tree.b_dust=0;check('no oath, no blessing');G.oath='silence';for(const h of G.roster)S.refreshStats(h);check('an oath');G.tree.b_dust=3;check('an oath and a dust blessing');ok(S.shatterSheetH()>352,'the sheet is taller than the old fixed 352 when the blessing and oath lines are present ('+S.shatterSheetH()+')');G.oath=null;G.tree.b_dust=0;}
  // ==================================================== pass 54: the reviewer's six defects (2026-09-30), each through production functions
  const KEY='crystal_road_save_v1',srcP54=require('fs').readFileSync(require('path').join(__dirname,'..','..','source','game.js'),'utf8');
  const stored=S=>S.win.localStorage.getItem(KEY),countReloads=S=>{const c={n:0};S.win.location.reload=()=>{c.n++;};return c;};
  // ---- 1. opening Settings never writes to the save
  {const S=await game(21),G=S.G;G.screen='road';G.noSave=false;S.saveGame();const raw=stored(S);ok(!!raw&&JSON.parse(raw).v===1,'a real save is stored');
    S.openSheet('settings');const seen=[],orig=S.win.text;S.win.text=function(x,y,str){seen.push(String(str));return orig.apply(this,arguments);};try{for(let k=0;k<5;k++)S.draw();}finally{S.win.text=orig;}
    ok(stored(S)===raw,'after five frames of the Settings sheet the stored save is byte-identical');ok(seen.includes('Progress saves automatically on this device.'),'the footer still reports that saving works');
    ok(S.storeOk()===true&&S.win.localStorage.getItem(S.SAVE_PROBE)===null&&S.SAVE_PROBE!==KEY,'the storage test uses its own key and leaves nothing behind');
    ok(!/storeSet\(\s*'__probe'/.test(srcP54),'no code path saves a probe through storeSet');
    S.win.localStorage.setItem(KEY,'__probe');ok(S.loadGame()===false,'a save an older build already overwrote with the probe word is treated as no save, not a crash');}
  // ---- 2. Reset the road needs two separate taps
  {const S=await game(22),G=S.G;G.screen='road';G.noSave=false;S.saveGame();const raw=stored(S),rl=countReloads(S);S.openSheet('settings');
    const row=()=>S.settingsRows().find(r=>/Reset the road|delete ALL progress/.test(r[0]));ok(/^Reset the road/.test(row()[0]),'the row reads Reset the road');
    S.setRT(100);row()[2]();ok(stored(S)===raw&&rl.n===0&&S.resetArmed(),'the first tap deletes nothing and arms the row');ok(row()[0]==='Tap again to delete ALL progress','the armed row says what the next tap does');
    S.setRT(100.2);row()[2]();ok(stored(S)===raw&&rl.n===0,'a second tap 0.2 s later (a double tap) is ignored');
    S.setRT(106);ok(!S.resetArmed()&&/^Reset the road/.test(row()[0]),'the row disarms by itself after five seconds');row()[2]();ok(stored(S)===raw&&S.resetArmed(),'a tap after that only arms it again');
    S.closeSheet();ok(!S.resetArmed(),'closing the sheet disarms');S.openSheet('settings');S.setRT(200);row()[2]();S.setRT(201);row()[2]();ok(stored(S)===null&&rl.n===1&&G.noSave===true,'tap, wait, tap: the save is deleted and the page reloads once');}
  // ---- 3. a posted hero cannot enter the Catacombs
  {const S=await game(23),G=S.G;const wall=S.addHero(S.HEROES.find(d=>!G.roster.find(h=>h.id===d.id)),30),camp=S.addHero(S.HEROES.find(d=>!G.roster.find(h=>h.id===d.id)),30);G.delveKeys=3;G.mode='walk';G.screen='road';
    G.castle.garrison.push(wall.id);wall.postedAt=S.gameNow();ok(S.heroStatus(wall)==='garrison'&&S.heroStatus(camp)==='camp','one hero on the wall, one at camp');
    S.startDelve(wall);ok(G.delve==null&&G.delveKeys===3&&G.castle.garrison.includes(wall.id),'startDelve refuses the posted hero: no delve, no key spent, still on the wall');ok(/posted on the wall/.test(S.delveBlock(wall)),'and says why: '+S.delveBlock(wall));
    S.openSheet('delve');const seen=[],orig=S.win.text;S.win.text=function(x,y,str){seen.push(String(str));return orig.apply(this,arguments);};try{S.draw();}finally{S.win.text=orig;}
    {const rowOf=h=>h.name+' · '+S.CLASSES[h.cls].name+' Lv '+h.lvl;ok(seen.includes(rowOf(camp))&&seen.includes(rowOf(G.active[0]))&&!seen.includes(rowOf(wall)),'the Catacombs sheet lists the camp hero and the marching ones, and not the posted one');}S.closeSheet();
    ok(S.delveBlock(camp)===''&&S.delveBlock(G.active[0])==='','camp and marching heroes may go');S.startDelve(camp);ok(!!G.delve&&G.delve.hero===camp&&G.delveKeys===2,'the camp hero descends and a key is spent');}
  // ---- 4. the chosen road speed survives a reload
  {const trip=async(speed,until)=>{const S=await game(24),G=S.G;G.screen='road';G.noSave=false;G.speed=speed;G.speedUntil=until(S.gameNow());S.saveGame();G.speed=1;ok(S.loadGame()===true,'speed '+speed+': the save loads');return G.speed;};
    ok(await trip(2,()=>0)===2,'2x is still 2x after a reload');ok(await trip(1,()=>0)===1,'1x stays 1x');
    ok(await trip(4,n=>n+3600e3)===4,'4x with an hour of boost left is still 4x');ok(await trip(4,n=>n-1)===2,'4x whose boost has run out comes back as 2x, as speedNow would leave it');
    const S=await game(24);ok(S.savedSpeed({speed:7})===1&&S.savedSpeed({})===1&&S.savedSpeed({speed:'4',speedUntil:9e15})===1,'anything that is not a real speed loads as 1x');ok(/fast:G\.fast,speed:G\.speed\|\|1\}\)/.test(srcP54),'serialize writes the speed');}
  // ---- 5. duplicate heroes: one copy survives and nothing is lost
  {const S=await game(25),G=S.G;G.screen='road';G.noSave=false;const mk=(slot,rank,lvl)=>{const it=S.makeItem(0,rank);it.slot=slot;it.rank=rank;it.lvl=lvl;if(slot==='weapon')it.kind=S.CLASSES.cleric.weapon;return it;};
    const a=G.roster.find(h=>h.id==='sera');ok(!!a,'Sera is on the roster');a.lvl=40;a.abLvl=1;a.tier=0;a.tierMax=0;a.talents={};a.eq={weapon:mk('weapon',0,0),cape:mk('cape',3,20)};
    const b=S.mkHero(S.HEROES.find(d=>d.id==='sera'));b.lvl=30;b.abLvl=4;b.tier=1;b.tierMax=1;const tk=Object.keys(S.TALENTS.cleric||{})[0]||'t0';b.talents={[tk]:1};b.eq={weapon:mk('weapon',4,30),cape:mk('cape',0,0),charm:mk('charm',2,5)};G.roster.push(b);
    const ids=h=>Object.values(h.eq).map(it=>it.id),all=new Set(ids(a).concat(ids(b)).concat(G.pack.map(it=>it.id))),best={weapon:b.eq.weapon.id,cape:a.eq.cape.id,charm:b.eq.charm.id},packBefore=G.pack.length;
    S.saveGame();ok(JSON.parse(stored(S)).roster.filter(r=>r.id==='sera').length===2,'the save carries two Seras');ok(S.loadGame()===true,'it loads');
    const seras=G.roster.filter(h=>h.id==='sera'),k=seras[0];ok(seras.length===1&&k.lvl===40,'one Sera remains, the Lv 40 one');ok(k.abLvl===4&&k.tier===1&&k.tierMax===1&&k.uid===S.heroUid(k),'she has the higher ability rank and the promotion of the other copy (ability '+k.abLvl+', rank '+k.tier+')');
    ok(k.talents[tk]===1,'and the other copy\'s talent');ok(k.eq.weapon.id===best.weapon&&k.eq.cape.id===best.cape&&k.eq.charm.id===best.charm,'each slot wears the better of the two items, and an empty slot takes the other copy\'s');
    const after=new Set(Object.values(k.eq).map(it=>it.id).concat(G.pack.map(it=>it.id)));ok([...all].every(id=>after.has(id))&&G.pack.length===packBefore+2,'the two items she does not wear are in the pack: no item was destroyed');
    ok(new Set(G.roster.map(h=>h.id)).size===G.roster.length&&new Set(G.active).size===G.active.length&&G.campfireDone===true,'every id is unique, the party holds no duplicate, the campfire is done');
    const raw2=S.serialize();S.win.localStorage.setItem(KEY,raw2);S.loadGame();ok(G.roster.filter(h=>h.id==='sera').length===1&&G.pack.length===packBefore+2,'loading again changes nothing');}
  // ---- 6. save codes: shape check, trial load, and a start that cannot get stuck
  {const S=await game(26),G=S.G;G.screen='road';G.noSave=false;S.saveGame();const good=stored(S),d0=()=>JSON.parse(good);ok(S.saveProblems(d0())==='','a real save has no problems');
    const bad=(f,why)=>{const d=d0();f(d);ok(S.saveProblems(d)!=='','rejected: '+why+' ('+S.saveProblems(d)+')');};
    bad(d=>{d.v=2;},'another version');bad(d=>{delete d.prog;},'no road progress');bad(d=>{d.prog='x';},'progress that is not a list');bad(d=>{d.zone=99;},'a zone off the map');bad(d=>{d.zone=1.5;},'a fractional zone');bad(d=>{d.gold='lots';},'gold that is not a number');bad(d=>{d.ore=-5;},'negative ore');bad(d=>{d.gold=null;},'no gold');
    bad(d=>{d.roster=[];},'an empty roster');bad(d=>{d.roster=[{id:'nobody',lvl:5,xp:0}];},'no known hero');bad(d=>{d.roster[0].lvl='9';},'a hero level that is not a number');bad(d=>{d.roster[0].eq=7;},'hero gear that is not an object');bad(d=>{d.roster.push(null);},'a null hero');
    bad(d=>{d.pack={};},'a pack that is not a list');bad(d=>{d.pack=[5];},'a pack item that is not an item');bad(d=>{d.castle=[];},'a castle that is not an object');bad(d=>{d.castle={};},'a castle without its parts');bad(d=>{d.quests='x';},'quests that are not a list');bad(d=>{d.tree=3;},'a tree that is not an object');bad(d=>{delete d.t;},'no save time');
    ok(S.saveProblems(null)!==''&&S.saveProblems([])!==''&&S.saveProblems('x')!=='','not an object at all');{const d=d0();d.roster[0].id='aldric';ok(S.saveProblems(d)==='','a save from before the renames is still valid');}
    for(const k of ['TextDecoder','TextEncoder','atob','btoa'])if(!S.win[k])S.win[k]=globalThis[k]; /* the headless page has no text codecs of its own */
    const code=json=>{const bytes=new TextEncoder().encode(json);return'CR1.'+S.b64u(bytes)+'.'+S.hash32(bytes);};
    ok(await S.readSaveCode(code(good))===good,'a sound code reads back to the save');
    let err='';try{const d=d0();delete d.prog;await S.readSaveCode(code(JSON.stringify(d)));}catch(e){err=e.message;}ok(/does not hold a valid save: the road progress is malformed/.test(err),'a code with a valid checksum but a malformed save is refused before anything is stored: '+err);
    err='';try{await S.readSaveCode(code('{not json'));}catch(e){err=e.message;}ok(/does not hold a valid save/.test(err),'so is a code whose payload is not JSON');ok(stored(S)===good,'the stored save is untouched by refused codes');}
  {const S=await game(27),G=S.G;G.screen='road';G.noSave=false;S.saveGame();const mine=stored(S),rl=countReloads(S);const d=JSON.parse(mine);d.prog=null; /* parses as JSON, is not a save */const why=S.importSave(JSON.stringify(d));
    ok(why===S.IMPORT_FAIL&&why==='Import failed. Your existing save was not changed.'&&rl.n===0,'a malformed import returns the failure line and the page does not reload');ok(stored(S)===mine,'the stored save is byte-identical');ok(S.sideGet(S.SAVE_PREV)===null&&S.sideGet(S.SAVE_NOTE)===null&&G.noSave===false,'no backup, no note, and saving is still on');ok(/road progress/.test(G.importWhy),'the reason is kept for the box: '+G.importWhy);}
  {const S=await game(28),G=S.G;G.screen='road';G.noSave=false;G.gold=111;S.saveGame();const mine=stored(S),rl=countReloads(S);const d=JSON.parse(mine);d.gold=987654;const theirs=JSON.stringify(d);
    ok(S.importSave(theirs)===''&&rl.n===1,'a sound import is accepted and the page reloads');ok(stored(S)===theirs&&S.sideGet(S.SAVE_PREV)===mine&&S.sideGet(S.SAVE_NOTE)==='saved'&&G.noSave===true,'the import is stored, the replaced save is kept aside, and the next start will show Saved');
    G.savedAt=null;G.toast=null;S.setRT(50);S.bootNote();ok(G.savedAt===50&&S.sideGet(S.SAVE_NOTE)===null&&!G.toast,'the start after an import shows the Saved mark once');}
  {const S=await game(29),G=S.G;G.screen='road';G.noSave=false;S.saveGame();const mine=stored(S),rl=countReloads(S);ok(S.bootLoad()===true&&rl.n===0,'a sound save starts normally');
    const d=JSON.parse(mine);d.prog=null;const broken=JSON.stringify(d);S.win.localStorage.setItem(KEY,broken);S.sideSet(S.SAVE_PREV,mine);
    ok(S.bootLoad()==='reload'&&rl.n===1,'a stored save that throws does not stop the start: the page reloads');ok(stored(S)===mine&&S.sideGet(S.SAVE_BAD)===broken&&S.sideGet(S.SAVE_PREV)===null,'the save from before the restore is back, the broken one is set aside, the backup is used up');
    ok(/before the last restore is back/.test(S.sideGet(S.SAVE_NOTE)||''),'the note says so');G.toast=null;S.bootNote();ok(S.sideGet(S.SAVE_NOTE)===null&&!!G.toast,'the note is shown once and cleared');}
  {const S=await game(30),G=S.G;G.screen='road';G.noSave=false;S.saveGame();const d=JSON.parse(stored(S));d.prog=null;const broken=JSON.stringify(d),rl=countReloads(S);S.win.localStorage.setItem(KEY,broken);S.sideSet(S.SAVE_PREV,null);
    ok(S.bootLoad()==='reload'&&stored(S)===null&&S.sideGet(S.SAVE_BAD)===broken&&rl.n===1,'with no backup the broken save is set aside and the road starts new, once');ok(S.bootLoad()===false&&rl.n===1,'the next start finds no save and does not reload again: no loop');
    ok(/const resumed=bootLoad\(\);if\(resumed==='reload'\)return;/.test(srcP54)&&/const fail=importSave\(json\);if\(fail\)/.test(srcP54),'the page start and the Replace button use these paths');}
  // ==================================================== pass 55: MVP requirement 1, trustworthy saving (acceptance tests)
  const codecs=S=>{for(const k of ['TextDecoder','TextEncoder','atob','btoa'])if(!S.win[k])S.win[k]=globalThis[k];};const codeOf=(S,json)=>{const bytes=new TextEncoder().encode(json);return'CR1.'+S.b64u(bytes)+'.'+S.hash32(bytes);};
  const norm=raw=>{const d=JSON.parse(raw);delete d.t;return JSON.stringify(d);}; /* a save without its timestamp */
  const diffOf=(a,b)=>{const x=JSON.parse(a),y=JSON.parse(b),out=[];for(const k of new Set(Object.keys(x).concat(Object.keys(y))))if(JSON.stringify(x[k])!==JSON.stringify(y[k]))out.push(k+': '+String(JSON.stringify(x[k])).slice(0,60)+' => '+String(JSON.stringify(y[k])).slice(0,60));return out.join(' ; ');};
  const rich=async seed=>{const S=await game(seed),G=S.G;G.screen='road';G.noSave=false;G.gold=5e6;G.ore=4e5;G.dust=77;G.zone=2;G.prog[2]=7;G.cleared[0]=G.cleared[1]=true;G.reforges=1;G.tree.atk=3;G.speed=2;G.autoCast=true;G.autoUntil=S.gameNow()+3600e3;G.delveKeys=2;
    const camp=S.addHero(S.HEROES.find(d=>!G.roster.find(h=>h.id===d.id)),12),wall=S.addHero(S.HEROES.find(d=>!G.roster.find(h=>h.id===d.id)),12);G.castle.garrison.push(wall.id);wall.postedAt=S.gameNow();G.quests.push({hero:camp,q:S.QUESTS[0],end:S.gameNow()+1800e3});
    const it=S.makeItem(1,2);it.slot='cape';it.lvl=4;G.active[0].eq.cape=it;G.pack.push(S.makeItem(1,1));G.active[1].tier=1;G.active[1].tierMax=1;G.active[1].uid=S.heroUid(G.active[1]);G.active[0].abLvl=5;const rec=S.drillRecords();rec.claimed['zone:0']=2;rec.best['zone:0']=[{hero:'hale',total:1234}];for(const h of G.roster)S.refreshStats(h);return S;};
  // ---- opening Settings, and repeated storage checks, do not change the save
  {const S=await rich(41),G=S.G;S.saveGame();const raw=stored(S);S.openSheet('settings');for(let k=0;k<10;k++)S.draw();ok(stored(S)===raw,'opening Settings and drawing it ten times leaves the save byte-identical');
    let all=true;for(let k=0;k<25;k++)all=S.storeProbe()&&all;ok(all&&stored(S)===raw&&S.win.localStorage.getItem(S.SAVE_PROBE)===null,'25 storage probes succeed, leave the save byte-identical and leave no probe key');
    ok(S.storeSet('__probe')===false&&S.storeSet('{"x":1}')===false&&S.storeSet('')===false&&S.storeSet(null)===false&&stored(S)===raw,'the save key refuses anything that is not a serialized save');ok(S.isSaveText(S.serialize()),'and accepts what serialize() writes');
    S.win.localStorage.setItem=()=>{throw new Error('quota');};ok(S.storeProbe()===false,'a device that cannot store reports false instead of throwing');}
  // ---- a malformed import is rejected without changing current progress, with the exact line
  {const S=await rich(42),G=S.G;codecs(S);S.saveGame();const mine=stored(S),before=norm(S.serialize()),rl=countReloads(S),hp=G.roster.map(h=>h.hp).join(),tut0=S.TUT.length;
    const tryBad=(f,label)=>{const d=JSON.parse(mine);f(d);const r=S.importSave(JSON.stringify(d).replace(/"INF"/g,'1e999'));ok(r==='Import failed. Your existing save was not changed.','refused: '+label+' ('+G.importWhy+')');{const now2=norm(S.serialize());let diff='';if(now2!==before){const x=JSON.parse(before),y=JSON.parse(now2);for(const k of Object.keys(y))if(JSON.stringify(x[k])!==JSON.stringify(y[k])){diff=k+': '+JSON.stringify(x[k]).slice(0,80)+' => '+JSON.stringify(y[k]).slice(0,80);break;}}ok(stored(S)===mine&&now2===before&&rl.n===0,'  and the stored save and the running game are unchanged ['+label+'] '+(stored(S)===mine)+' '+rl.n+' '+diff);}};
    tryBad(d=>{d.gold='INF';},'infinite gold');tryBad(d=>{d.gold=null;},'gold that was NaN when written');tryBad(d=>{d.ore=-1;},'negative ore');tryBad(d=>{d.dust=-3;},'negative dust');tryBad(d=>{d.roster[0].lvl=0;},'a level 0 hero');tryBad(d=>{d.roster[0].lvl=2.5;},'a fractional level');
    tryBad(d=>{d.roster[0].tier=9;},'a rank past the last promotion');tryBad(d=>{d.roster[0].abLvl=0;},'ability rank 0');tryBad(d=>{d.zone=-1;},'a negative zone');tryBad(d=>{d.prog[1]=-4;},'negative progress');tryBad(d=>{d.active=['nobody'];},'a party member who is not on the roster');
    tryBad(d=>{d.active=['hale','sera','vex','morrow','hale'];},'five in the party');tryBad(d=>{d.roster[0].eq.cape.slot='weapon';},'an item in the wrong slot');tryBad(d=>{d.roster[0].eq.cape.rank=42;},'an item of an impossible rank');tryBad(d=>{d.roster[0].eq.hat={slot:'hat',rank:0,lvl:0};},'an unknown slot');
    tryBad(d=>{d.pack.push({slot:'weapon',kind:'spoon',rank:0,lvl:0});},'a weapon of an unknown kind');tryBad(d=>{d.quests[0].hero='ghost';},'a quest for a hero who is not on the roster');tryBad(d=>{d.quests[0].q='nap';},'an unknown quest');tryBad(d=>{d.castle.garrison=['ghost'];},'a post held by nobody');
    tryBad(d=>{d.speed=3;},'a road speed of 3');tryBad(d=>{d.tree.atk=-2;},'a negative tree rank');tryBad(d=>{d.tree.atk=5000;},'a tree rank no node ever allowed');tryBad(d=>{d.tree.atk=1.5;},'a fractional tree rank');tryBad(d=>{d.stats.kills='INF';},'an infinite number deep inside');tryBad(d=>{delete d.roster;},'no roster section');tryBad(d=>{delete d.prog;},'no progress section');
    ok(S.importSave('{"v":1')===S.IMPORT_FAIL&&S.importSave('[]')===S.IMPORT_FAIL&&S.importSave('')===S.IMPORT_FAIL&&stored(S)===mine,'text that is not a save object is refused the same way');
    let err='';try{await S.readSaveCode(codeOf(S,JSON.stringify(Object.assign(JSON.parse(mine),{gold:-9}))));}catch(e){err=e.message;}ok(/does not hold a valid save: gold is not a valid amount/.test(err)&&stored(S)===mine,'a save CODE with a valid checksum and a malformed save is refused before the confirm step: '+err);
    ok(G.roster.map(h=>h.hp).join()===hp&&S.TUT.length===tut0&&G.noSave===false&&!G.trial,'after all those trial boots the live heroes, the tutorial list and the save switch are exactly as they were');}
  // ---- the trial boot runs on an isolated copy: a save that passes the shape checks but cannot start is refused, and the live game is untouched
  {const S=await rich(43),G=S.G;S.saveGame();const mine=stored(S),before=norm(S.serialize()),ref=G.roster,gold=G.gold;const d=JSON.parse(mine);d.roster[0].eq.cape.lvl=100000; /* a legal shape (a whole, positive item level) that no hero can carry: its stats overflow */ok(S.saveProblems(d)==='','an item of level 100000 passes the shape checks');const why=S.trialBoot(d);
    ok(/became invalid/.test(why),'but the isolated copy that boots with it is not sane, so it fails the trial boot: '+why);
    {const d2=JSON.parse(mine);d2.prog=null;const w2=S.trialBoot(d2);ok(/does not start/.test(w2)&&G.roster===ref&&norm(S.serialize())===before,'a save that makes the loader throw is caught on the copy too ('+w2+')');}ok(G.roster===ref&&G.gold===gold&&norm(S.serialize())===before&&stored(S)===mine,'the live state is the same objects and the same save text after the failed trial');
    ok(S.trialBoot(JSON.parse(mine))===''&&G.roster===ref&&norm(S.serialize())===before,'the player\'s own save passes the trial boot, again without touching the live game');ok(S.importSave(JSON.stringify(d))===S.IMPORT_FAIL&&stored(S)===mine,'and importSave refuses the broken one');}
  // ---- a valid old save migrates successfully
  {const S=await rich(44),G=S.G;codecs(S);S.saveGame();const d=JSON.parse(stored(S));for(const k of ['speed','treeTab','highestZoneEver','everReachedEndless','migV','drill','heroesSeen','keepPushing','powerHist','omens','omenMarks','autoTrainOff','endMilestone','renown','boostSeen','far','zoneT','musicVol','sfxVol','surge','dustFrac'])delete d[k];
    for(const r of d.roster){delete r.tierMax;delete r.talents;delete r.postedAt;if(r.id==='hale')r.id='aldric';if(r.id==='ash')r.id='wren';}d.active=d.active.map(id=>id==='hale'?'aldric':id==='ash'?'wren':id);d.castle.garrison=d.castle.garrison.map(id=>id==='ash'?'wren':id);for(const q of d.quests)if(q.hero==='ash')q.hero='wren';d.tree.b_start=9; /* above today's cap of 5: migration 2 refunds it */d.tree.crit=30;
    const old=JSON.stringify(d);ok(S.saveProblems(JSON.parse(old))==='','an old save (old hero ids, no newer fields, ranks above today\'s caps) passes validation');ok(S.trialBoot(JSON.parse(old))==='','and boots on the isolated copy');
    const S2=H.load({seed:44,startMs:d.t,save:old});await S2.ready;const G2=S2.G;ok(G2.roster.some(h=>h.id==='hale')&&!G2.roster.some(h=>h.id==='aldric'),'loaded for real: the renamed hero is Hale');ok(G2.tree.b_start===5&&G2.tree.crit===20&&G2.migV===2,'the tree ranks above the caps were brought down by the migration (b_start '+G2.tree.b_start+', crit '+G2.tree.crit+', migV '+G2.migV+')');
    ok(G2.gold>=d.gold&&G2.dust>=d.dust,'and the migration refunded what the removed ranks cost (gold '+d.gold+' -> '+G2.gold+', dust '+d.dust+' -> '+G2.dust+')');ok(S2.stateProblems()===''&&G2.speed===1&&G2.roster.every(h=>h.tierMax>=(h.tier||0)),'missing fields took their defaults and the running state is sane');}
  // ---- exporting and importing produces the same gameplay state
  {const S0=await rich(45);S0.saveGame();const raw0=stored(S0),t0=JSON.parse(raw0).t;const S=H.load({seed:45,startMs:t0,save:raw0});await S.ready;const G=S.G;G.title=false;codecs(S); /* the hand-built state, loaded once so that it is a state the game itself produced */S.saveGame();const raw=stored(S);ok(!!raw,'the game saved');const code=await S.makeSaveCode();ok(/^CR[12]\./.test(code),'an export code is made ('+code.length+' characters)');
    const S2=H.load({seed:99,startMs:t0});await S2.ready;codecs(S2);const rl=countReloads(S2);const json=await S2.readSaveCode(code);ok(S2.importSave(json)===''&&rl.n===1,'a fresh device accepts the code');
    const S3=H.load({seed:99,startMs:t0,save:S2.win.localStorage.getItem(KEY)});await S3.ready;S3.G.noSave=true;ok(norm(S3.serialize())===norm(raw),'after the reload the game serializes to the same save, field for field '+diffOf(norm(raw),norm(S3.serialize())));
    const G3=S3.G;ok(G3.gold===G.gold&&G3.zone===G.zone&&G3.prog[2]===7&&G3.reforges===1&&G3.active.map(h=>h.id).join()===G.active.map(h=>h.id).join()&&G3.roster.length===G.roster.length&&G3.active[0].eq.cape.lvl===4&&G3.active[1].tier===1&&G3.active[0].abLvl===5,'currencies, road, party, gear, promotion and ability rank all match');
    ok(G3.quests.length===1&&G3.quests[0].end===G.quests[0].end&&G3.castle.garrison.join()===G.castle.garrison.join()&&G3.delveKeys===2&&S3.drillRecords().claimed['zone:0']===2&&S3.drillRecords().best['zone:0'][0].total===1234,'the quest timer, the garrison post, the Catacombs keys and the drill claims and records match');
    ok(G3.autoCast===true&&G3.autoUntil===G.autoUntil&&G3.speed===2,'Auto-Cast, its end time and the road speed match');}
  // ---- reloading: 2x, a running 4x boost with its real remaining time, an expired boost, Auto-Cast, timers
  {const base=1700000000000,mk=async()=>{const S=await rich(46);return S;};
    {const S=await mk(),G=S.G;G.speed=2;S.saveGame();const S2=H.load({seed:1,startMs:base,save:stored(S)});await S2.ready;ok(S2.G.speed===2&&S2.speedNow()===2,'reloading keeps 2x');}
    {const S=await mk(),G=S.G;S.buySpeed4();const until=G.speedUntil;ok(G.speed===4&&until===S.gameNow()+2*3600e3,'a 4x boost is bought: two hours');S.saveGame();const raw=stored(S),t0=JSON.parse(raw).t;
      const S2=H.load({seed:1,startMs:t0+40*60e3,save:raw});await S2.ready;ok(S2.G.speed===4&&S2.speedNow()===4&&S2.G.speedUntil===until&&Math.round((S2.G.speedUntil-S2.gameNow())/60e3)===80,'reloading 40 minutes later: still 4x, the same end time, 80 minutes left (the time away was not given back)');
      const S3=H.load({seed:1,startMs:t0+3*3600e3,save:raw});await S3.ready;ok(S3.G.speed===2&&S3.speedNow()===2&&S3.G.speedUntil===until,'reloading after the boost has run out: back to 2x, and the end time is not moved');}
    {const S=await mk(),G=S.G;const raw=(S.saveGame(),stored(S)),t0=JSON.parse(raw).t,au=G.autoUntil;const S2=H.load({seed:1,startMs:t0+20*60e3,save:raw});await S2.ready;ok(S2.G.autoCast===true&&S2.G.autoUntil===au&&S2.G.autoUntil-S2.gameNow()===40*60e3,'Auto-Cast is still on with 40 of its 60 minutes left after 20 minutes away');
      const S3=H.load({seed:1,startMs:t0+2*3600e3,save:raw});await S3.ready;ok(S3.G.autoUntil===au&&!(S3.G.autoUntil>S3.gameNow()),'after two hours away the Auto-Cast boost has run out and was not extended');
      ok(S2.G.zone===2&&S2.G.prog[2]===7&&S2.G.quests[0].end===G.quests[0].end&&S2.G.castle.garrison.length===1&&S2.G.delveKeys===2&&S2.drillRecords().claimed['zone:0']===2,'the zone, its progress, the quest timer, the garrison, the Catacombs keys and the drill claims come back');}}
  // ---- a save made immediately after Shattering reloads correctly
  {const S=await rich(47),G=S.G;G.cleared[3]=true;G.active[1].tier=2;G.active[1].tierMax=2;const dust0=G.dust,gain=S.reforgeGain(),n0=G.reforges;S.doReforge();const raw=stored(S);ok(!!raw&&JSON.parse(raw).reforges===n0+1,'the Shatter itself writes the save');
    const S2=H.load({seed:1,startMs:JSON.parse(raw).t,save:raw});await S2.ready;const G2=S2.G;ok(G2.reforges===n0+1&&G2.dust===dust0+gain&&G2.zone===0&&G2.prog.every(v=>v===0)&&G2.cleared.every(v=>!v),'reloaded: the Shatter count, the dust and a fresh road');
    ok(G2.roster.every(h=>(h.tier||0)===0&&h.uid===S2.heroUid(h))&&G2.roster.find(h=>h.id===G.active[1].id).tierMax===2&&S2.stateProblems()==='','every hero is back at rank 0 with the matching sheet, the best rank is remembered, the state is sane');S2.G.noSave=true;const raw2=S2.serialize();const S3=H.load({seed:1,startMs:JSON.parse(raw2).t,save:raw2});await S3.ready;S3.G.noSave=true;ok(norm(S3.serialize())===norm(raw2),'and saving and loading it again changes nothing '+diffOf(norm(raw2),norm(S3.serialize())));}
  // ---- player actions are saved through the one path and show Saved; fights and timers do not
  {const S=await rich(48),G=S.G;S.setRT(10);S.saveGame();const tap=fn=>S.spendCall(fn,0,0,null);const flushed=()=>{const due=!!G.saveDue;S.setRT(S.getRT()+0.05);const early=S.flushSave();S.setRT(S.getRT()+0.4);const late=S.flushSave();return{due,early,late};};
    const check=(label,fn,show=true)=>{G.savedAt=null;const before=stored(S);tap(fn);const r=flushed();ok(r.due&&!r.early&&r.late,label+': a save is asked for, waits out the burst, then is written');ok(stored(S)!==before&&norm(stored(S))===norm(S.serialize()),'  the stored save is the current game');ok(show?G.savedAt!=null:G.savedAt==null,'  '+(show?'Saved is shown':'no Saved mark (a minor choice)'));};
    const it=G.pack[0];it.slot='charm';check('equipping an item',()=>S.equipItem(G.active[0],it));check('taking it off',()=>S.unequip(G.active[0],'charm'));
    check('upgrading gear',()=>S.upgradeItem(G.active[0].eq.cape,G.active[0]));check('a tree purchase',()=>S.buyTreeRank(S.TREE.find(n=>n.id==='atk')));check('a promotion',()=>{const h=G.active[2];h.lvl=30;S.promoteHero(h);});
    {const bench=G.active[3];check('a party change',()=>S.partyToCamp(3));ok(!G.active.includes(bench)&&S.heroStatus(bench)==='camp','  the hero is at camp');check('a hero taking a post on the wall',()=>{G.castle.garrison.push(bench.id);bench.postedAt=S.gameNow();});}check('claiming a drill reward',()=>{S.drillRecords().claimed['zone:1']=1;});check('buying the 4x boost',()=>S.buySpeed4());
    check('a Shatter',()=>{G.cleared[3]=true;S.doReforge();});check('changing the road speed',()=>{G.speed=G.speed===1?2:1;},false);
    {G.savedAt=null;const before=stored(S);tap(()=>{G.enemies.length;});ok(!G.saveDue&&stored(S)===before&&G.savedAt==null,'a tap that changes nothing (a tap on the road) asks for no save and shows nothing');}
    {G.savedAt=null;G.saveDue=false;G.gold+=500;G.pack.push(S.makeItem(1,1));for(let k=0;k<30;k++)S.update(1/30,true);S.setRT(S.getRT()+1);ok(S.flushSave()===false&&G.savedAt==null,'gold earned, a drop and thirty frames of the road ask for no save: combat never shows Saved');}
    {G.savedAt=null;tap(()=>S.buyTreeRank(S.TREE.find(n=>n.id==='atk')));G.delve={floor:1};S.setRT(S.getRT()+1);ok(S.flushSave()===false&&G.saveDue===true,'inside the Catacombs the save waits');G.delve=null;ok(S.flushSave()===true&&G.savedAt!=null,'and is written with its mark once the run is over');}
    {G.savedAt=null;G.saveFailAt=null;tap(()=>S.buyTreeRank(S.TREE.find(n=>n.id==='atk')));S.win.localStorage.setItem=()=>{throw new Error('quota');};S.setRT(S.getRT()+1);ok(S.flushSave()===false&&G.savedAt==null&&G.saveFailAt!=null,'when the device refuses the write the mark says Not saved, never Saved');}
    {const seen=[],orig=S.win.text;S.win.text=function(x,y,str){seen.push(String(str));return orig.apply(this,arguments);};try{G.sheet=null;G.screen='road';G.saveFailAt=null;G.savedAt=S.getRT();S.draw();const a=seen.includes('Saved');seen.length=0;S.setRT(S.getRT()+1.2);S.draw();const b=seen.includes('Saved');seen.length=0;G.saveFailAt=S.getRT();S.draw();const c=seen.includes('Not saved');ok(a&&!b&&c,'the mark is drawn while fresh, gone 1.2 s later, and reads Not saved after a failed write');}finally{S.win.text=orig;}}
    ok(/try\{playerDid\(fn\);\}finally\{G\.toastKey=null;\}/.test(srcP54)&&/drillTick\(dt\);flushSave\(\);draw\(\);/.test(srcP54)&&/addEventListener\('pagehide',\(\)=>\{flushSave\(true\);saveGame\(\);\}\)/.test(srcP54),'every tap handler runs through playerDid, the frame loop flushes, and leaving the page writes at once');
    ok((srcP54.match(/localStorage\.setItem\(SAVE_KEY/g)||[]).length===1,'exactly one line in the game writes the save key');}
  // ==================================================== pass 56: MVP requirements 5-7 (the first five minutes, the objective line, mobile controls)
  const srcP56=require('fs').readFileSync(require('path').join(__dirname,'..','..','source','game.js'),'utf8');
  const frames=(S,sec)=>{for(let k=0;k<sec*30;k++){S.setRT(S.getRT()+1/30);S.clock.frame();S.update(1/30,true);}};
  const drawn=S=>{const seen=[],o=S.win.text;S.win.text=function(x,y,s){seen.push(String(s));return o.apply(this,arguments);};try{S.draw();}finally{S.win.text=o;}return seen;};
  // ---- 5. the opening is three live steps: watch, tap (required), cast (required)
  {const S=H.load({seed:61,startMs:1700000000000});await S.ready;const G=S.G;G.noSave=false;ok(G.title===true&&G.roster.length===1&&!G.tutDone&&G.wins===0,'a new game: the title, one hero, no tutorial done');
    ok(S.TUT.length===3&&S.TUT_OPEN===3,'the opening has three steps (it had seven)');const T=i=>typeof S.TUT[i].t==='function'?S.TUT[i].t():S.TUT[i].t;
    ok(T(0)==='Your hero attacks automatically'&&T(1)==='Tap the enemy to deal extra damage'&&T(2)==="Use Hale's ability",'the three lines: '+[T(0),T(1),T(2)].join(' / '));
    G.title=false;S.tutStart();ok(G.tut===0&&S.tutLive()&&G.mode==='battle'&&G.enemies.length===1&&G.enemies[0].id==='slime'&&G.screen==='road','step 1 starts inside a fight with one slime');
    ok(S.tabLocked('heroes')&&S.tabLocked('gear')&&S.tabLocked('vael')&&S.tabLocked('tree')&&!S.tabLocked('road')&&S.lockHint('gear')==='Finish the first fight','only the Road is open during the opening');
    const e=G.enemies[0],h=G.active[0],hp0=e.hp;frames(S,8);ok(e.hp<hp0&&G.tut===0,'the game runs under the step: the hero has hit the slime on his own ('+hp0+' -> '+e.hp+'), and step 1 waits for Next');
    S.tapEnemy(e);S.tapCastHero(h);frames(S,1);h.tapCast=false;ok(G.tut===0,'tapping or casting does not skip step 1');
    frames(S,90);ok(!e.dead&&e.hp>=Math.ceil(e.maxhp*0.3)&&!h.dead&&h.hp>=1&&G.enemies.length===1&&G.mode==='battle','ninety seconds later nobody has fallen: the slime rests at 30% ('+e.hp+' of '+e.maxhp+'), the hero at '+h.hp);
    const seen=drawn(S);ok(seen.includes('Your hero attacks automatically')&&seen.includes('Next')&&seen.includes('1 / 3'),'step 1 is drawn with its Next button and 1 / 3');const next=S.getHits().find(x=>x.w===96&&x.h===28);ok(!!next,'the Next button has a 96 x 28 tap area');
    ok(S.getHits().some(x=>x.w===S.win.BS||(x.w>=30&&x.w<=40&&x.h===x.w)),'the ability buttons still take taps (nothing is swallowed)');next.fn();ok(G.tut===1&&S.tutLive(),'Next opens step 2');
    frames(S,20);ok(G.tut===1,'step 2 does not end by waiting');S.tapCastHero(h);frames(S,3);ok(G.tut===1,'nor by casting: it requires a tap on the enemy');
    S.tapEnemy(e);frames(S,0.2);ok(G.tut===2&&h.charge===100&&!h.tapCast,'one tap on the enemy opens step 3, with the ability charged');ok(drawn(S).includes("Use Hale's ability"),'step 3 is drawn');
    S.tapEnemy(e);S.tapEnemy(e);frames(S,10);ok(G.tut===2&&h.charge===100,'step 3 does not end by tapping the enemy or waiting; the ability stays charged');
    const b=S.TUT[2].box(),btn=S.getHits().find(x=>x.x>=b[0]&&x.x<=b[0]+4&&x.w===b[2]-4);ok(!!btn,'the framed box sits on the first ability button');S.draw();(S.getHits().find(x=>x.x>=b[0]&&x.x<=b[0]+4&&x.w===b[2]-4)).fn();frames(S,0.1);
    ok(G.tut===null&&G.tutDone===true&&!S.tutLive(),'tapping the ability button ends the opening');ok(JSON.parse(stored(S)).tutDone===true,'and it is saved');ok(S.TUT.length===3,'the step list is unchanged');
    for(const k of ['gearTaught','treeTaught','drillTaught','shatterTaught'])G[k]=true; /* the single cards are tested below; here they would cover the objective line */frames(S,12);ok(e.dead&&G.wins===1,'the slime then falls and the first fight is won ('+G.wins+' win)');
    G.pack.length=0;ok(S.nextObjective().text==='Win 2 fights to unlock the Tree','back on the Road the objective line reads: '+S.nextObjective().text);
    G.wins=0;ok(S.nextObjective().text==='Win 3 fights to unlock the Tree','with no wins: Win 3 fights to unlock the Tree');G.wins=2;G.campfireDone=false;ok(S.nextObjective().text==='Sera joins at the next campfire','two wins, no campfire yet: '+S.nextObjective().text);
    G.campfireDone=true;ok(S.nextObjective().text==='Win 1 fight to unlock the Tree','after the campfire: '+S.nextObjective().text);ok(!S.tabLocked('heroes')&&S.tabLocked('tree')&&S.tabLocked('vael'),'the tabs follow their own rules again');}
  // ---- 5. each other subject gets one card when it first matters, never twice
  {const S=await game(62),G=S.G;G.tutDone=true;G.screen='road';G.mode='walk';G.enc=99;G.wins=1;G.noSave=false;G.speedHinted=true;G.cpHinted=true;G.gearHinted=true;for(const k of ['gearTaught','treeTaught','drillTaught','shatterTaught'])G[k]=false;G.pack.length=0;for(const h of G.roster)h.eq={};
    frames(S,1);ok(G.tut==null,'nothing to teach yet: no card');G.pack.push(S.makeItem(0,0));frames(S,0.2);ok(G.tut!=null&&S.TUT[G.tut].once&&S.TUT[G.tut].t==='Your first item'&&G.gearTaught===true,'the first item brings the gear card');
    const gotIt=()=>{S.draw();S.getHits().find(x=>x.w===80&&x.h===22).fn();};gotIt();ok(G.tut==null&&S.TUT.length===3,'Got it closes it and the list is back to the three opening steps');frames(S,2);ok(G.tut==null,'it does not come back');
    ok(S.nextObjective().text==='Equip your first item'&&typeof S.nextObjective().go==='function','the objective line says Equip your first item and can be tapped');S.nextObjective().go();ok(G.screen==='gear','the tap opens Gear');G.screen='road';
    G.wins=3;frames(S,0.2);ok(G.tut!=null&&S.TUT[G.tut].t==='The Tree is open'&&G.treeTaught,'the third win brings the Tree card');gotIt();
    G.cleared[3]=true;frames(S,0.2);ok(G.tut!=null&&S.TUT[G.tut].t==='The Crystal can be shattered'&&G.shatterTaught,'the Shatter card comes when a Shatter is first possible');gotIt();
    G.cleared[0]=true;S.openTraining();ok(G.tut!=null&&S.TUT[G.tut].t==='The Training Drill'&&G.drillTaught,'the drill card comes the first time the training grounds open');gotIt();S.closeSheet();S.openTraining();ok(G.tut==null,'and only the first time');S.closeSheet();
    const raw=S.serialize(),d=JSON.parse(raw);ok(d.gearTaught&&d.treeTaught&&d.drillTaught&&d.shatterTaught,'the four flags are saved');for(const k of ['gearTaught','treeTaught','drillTaught','shatterTaught'])delete d[k];d.tutDone=true;d.reforges=0;d.drill=null;
    const S2=H.load({seed:1,startMs:d.t,save:JSON.stringify(d)});await S2.ready;ok(S2.G.gearTaught&&S2.G.treeTaught&&!S2.G.drillTaught&&!S2.G.shatterTaught,'a save from before this change: gear and the Tree count as taught (the old opening covered them), the drill and the Shatter do not');}
  // ---- 6. the objective line follows the state
  {const S=await game(63),G=S.G;G.tutDone=true;G.screen='road';G.mode='walk';G.wins=20;G.campfireDone=true;G.speedHinted=true;for(const k of ['gearTaught','treeTaught','drillTaught','shatterTaught'])G[k]=true;const O=()=>S.nextObjective(),Z=S.ZONES[0],cp=Z.fights/3;
    G.zone=0;G.prog[0]=0;ok(O().text==='Checkpoint in '+Math.ceil(cp)+' fights'&&!O().go,'at the start of a zone: '+O().text);G.prog[0]=Math.ceil(cp)-1;ok(O().text==='Checkpoint in 1 fight','one fight short: '+O().text);
    G.prog[0]=Math.ceil(cp*2);ok(O().text==='Boss in '+(Z.fights-G.prog[0])+' fights · Reward: Crystal Shard','past the last checkpoint: '+O().text);G.prog[0]=Z.fights;ok(O().text==='The boss is next · Reward: Crystal Shard','at the gate: '+O().text);
    G.bossFight=true;ok(O().text==='Defeat '+S.ENEMIES[Z.boss].name+' · Reward: Crystal Shard','in the boss fight: '+O().text);G.bossFight=false;
    G.cleared[0]=true;G.keepPushing={0:true};G.prog[0]=Math.ceil(cp*2);ok(O().text==='Boss in '+(Z.fights-G.prog[0])+' fights','a recovered shard is not promised twice: '+O().text);G.keepPushing={};ok(O().text==='Travel on to '+S.ZONES[1].name&&!!O().go,'a cleared zone points on: '+O().text);O().go();ok(G.screen==='map','and its tap opens the map');G.screen='road';
    G.castle.b.mine=2;G.castle.vil.total=3;G.castle.vil.mine=3;ok(S.orePerHour()>0,'Vael produces ore');G.castle.stored.ore=4*S.orePerHour();ok(O().text==='Vael resources ready'&&!!O().go,'four hours of production waiting: '+O().text);O().go();ok(G.screen==='vael','its tap opens Vael');G.screen='road';G.castle.stored.ore=0;
    G.cleared=G.cleared.map((v,i)=>i<4);G.zone=3;G.prog[3]=S.ZONES[3].fights;ok(S.canReforge()&&O().text==='Shatter available'&&!!O().go,'the road ahead is sealed and a Shatter is possible: '+O().text);O().go();ok(G.screen==='map','its tap opens the map, where the Shatter button is');G.screen='road';
    const iE=S.ZONES.length-1;G.cleared=G.cleared.map(()=>true);G.reforges=3;G.zone=iE;G.prog[iE]=30;ok(/^(Shatter available|Champion in 20 fights)$/.test(O().text),'on the Endless Road: '+O().text);
    G.pack.push(S.makeItem(0,0));for(const h of G.roster)h.eq={};ok(O().text==='Equip your first item','an item and nothing equipped anywhere: Equip your first item comes first');G.roster[0].eq.cape=G.pack.pop();
    G.delve={floor:1};ok(O()===null,'no line inside the Catacombs');G.delve=null;G.screen='gear';ok(O()===null,'nor off the Road');G.screen='road';G.tut=0;ok(O()===null,'nor during the opening');G.tut=null;
    G.zone=1;G.cleared=G.cleared.map((v,i)=>i<1);G.reforges=0;G.prog[1]=3;const seen=drawn(S);ok(seen.includes('Next')&&seen.some(s=>/^Checkpoint in \d+ fights?$/.test(s)),'the line is drawn on the Road: Next + '+seen.find(s=>/^Checkpoint/.test(s)));
    G.castle.stored.ore=4*S.orePerHour();S.draw();const hit=S.getHits().find(x=>x.h===20&&x.x===4&&x.w>=120);ok(!!hit,'a line that leads somewhere has a tap area 20 high');hit.fn();ok(G.screen==='vael','and the tap goes there');}
  // ---- 7. the smallest controls are larger; the smallest text is larger and brighter
  {const S=await game(64),G=S.G;G.tutDone=true;G.screen='road';G.mode='walk';for(const k of ['gearTaught','treeTaught','drillTaught','shatterTaught'])G[k]=true;G.speedHinted=true;G.wins=20;G.campfireDone=true;const area=(pred)=>{S.draw();return S.getHits().find(pred);};
    ok(S.FONT.xs[1]===6&&S.FONT.xsb[1]===6&&S.FONT.xxs[1]===5.25,'small text: xs 5.5 -> 6, the smallest 4.75 -> 5.25');ok(S.C.muted==='#b6bed4'&&S.C.dimt==='#8490b0','muted and dim text are brighter');
    const set=area(x=>x.x===240&&x.w===30),boost=area(x=>x.x===176&&x.w===64),spd=area(x=>x.w===50&&x.h===30);ok(set&&set.h===24,'Settings: 30 x 24 (was 24 x 16)');ok(boost&&boost.h===24,'Boosts: 64 x 24 (was 62 x 15)');ok(!!spd,'the speed selector: 50 x 30 (was 32 x 18)');
    S.openSheet('settings');const cl=area(x=>x.w===42&&x.h===32);ok(!!cl,'sheet close: 42 x 32 (was 30 x 28)');cl.fn();ok(G.sheet==null,'and it closes the sheet');
    G.screen='tree';G.treeTab='Party';G.gold=1e9;const buy=area(x=>x.x===184&&x.w===80&&x.hold);ok(buy&&buy.h>=22,'a tree purchase takes the whole right side of its row: 80 x '+(buy&&buy.h)+' (was 66 x 20)');const chip=area(x=>x.w===42&&x.h===24);ok(!!chip,'the per-tap chips: 42 x 24 (was 40 x 16)');const lv0=S.treeLv(S.TREE.filter(n=>n.branch==='Party')[0].id);buy.fn();ok(S.treeLv(S.TREE.filter(n=>n.branch==='Party')[0].id)===lv0+1,'and the purchase still works');
    G.screen='gear';G.gearHero=0;const it=S.makeItem(0,1);it.slot='cape';G.roster[0].eq.cape=it;G.ore=1e9;const up=area(x=>x.w===86&&x.hold);ok(up&&up.h>=24,'gear Upgrade: 86 x '+(up&&up.h)+' (was 78 x 16)');const l0=it.lvl||0;up.fn();ok((it.lvl||0)>l0,'and it upgrades');
    const asc=area(x=>x.w===86&&!x.hold&&x.h>=23);ok(!!asc,'gear Ascend: 86 x '+(asc&&asc.h));const pk=area(x=>x.w===58&&x.h>=20);ok(!!pk,'the pack buttons are '+(pk&&pk.h)+' high (were 14)');
    ok(/hit\(82,vy-4,vw\+8,vb\+8/.test(srcP56),'the villager minus and plus take taps 8 px larger each way');}
  if(out.length)console.log(out.join('\n'));console.log((fail?'FAIL  ':'PASS  ')+pass+' passed, '+fail+' failed');process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
