// Challenge and income-rate contract tests against PRODUCTION functions: the standardized party test is deterministic, ignores attention,
// omens, oaths and road speed, applies the bracket's zone defense, counts practice taps only up to three per second, and pays each bracket
// tier once, cumulatively, atomically; incomeRate is the one permanent rate shared by offline earnings and rewards.
// Run: node tests/contract/challenge.test.js   (exit code 1 on any failure)
'use strict';
const H=require('../sim/headless.js');
let pass=0,fail=0;const out=[];
function ok(c,m){if(c)pass++;else{fail++;out.push('FAIL '+m);}}
function near(a,b,eps,m){ok(Math.abs(a-b)<=eps,m+' (got '+a+', want '+b+')');}
async function game(seed=1,zone=3){const S=H.load({seed,startMs:1700000000000});await S.ready;const G=S.G;G.title=false;G.tut=null;G.mult='max';G.screen='vael';for(const def of S.HEROES.slice(0,4)){if(!G.roster.find(h=>h.id===def.id))S.addHero(def,30);}G.active=G.roster.slice(0,4);G.campfireDone=true;for(const h of G.roster){h.lvl=30;S.refreshStats(h);h.hp=h.maxhp;h.charge=0;}for(let i=0;i<zone;i++){G.cleared[i]=true;G.prog[i]=S.ZONES[i].fights;}G.zone=zone;G.mode='walk';G.enc=1e9;G.enemies=[];return S;}
const DT=1/60;
function runChallenge(S){const G=S.G;if(!S.startChallenge())throw new Error('no party');while(G.drill.running){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);}G.sheet=null;return G.drill;}
(async()=>{
  // ---- deterministic, standardized, isolated
  {const S=await game(),G=S.G;const a=runChallenge(S),b=runChallenge(S);ok(a.stats.total>0&&a.stats.total===b.stats.total&&a.stats.tap===b.stats.tap&&a.stats.crits===b.stats.crits,'two runs on the same state are identical ('+a.stats.total+')');
    ok(a.stats.taps===2*S.DRILL_SEC,'exactly two scripted taps per second ('+a.stats.taps+')');ok(a.stats.tap>0&&a.stats.hero>0&&a.stats.total===a.stats.hero+a.stats.tap,'party and tap damage stored separately and summed');
    ok(a.bracket.kind==='zone'&&a.bracket.zi===3,'bracket is the highest unlocked zone (Ironvein)');ok(a.g.enemies[0].def===S.challengeDef(a.bracket)&&a.g.enemies[0].def>0,'dummy carries the zone defense ('+a.g.enemies[0].def+')');
    G.omens=['swarm'];G.oath='silence';S.setRT(S.getRT()+1);S.noteAttention();G.speed=4;G.speedUntil=S.clock.get()+7200000;const c=runChallenge(S);ok(c.stats.total===a.stats.total,'omens, an oath, attention and road speed do not change the score');G.omens=[];G.oath=null;G.speed=1;G.speedUntil=0;
    ok(G.omens.length===0&&G.oath===null&&G.mode==='walk'&&!G.drillOn,'context restored');
    const s0={gold:G.gold,ore:G.ore,dust:G.dust};runChallenge(S);ok(G.gold===s0.gold&&G.ore===s0.ore&&G.dust===s0.dust,'no payout while claims are disabled');ok(S.challengeState().best['zone:3']===a.stats.total,'best score recorded');}
  // ---- Endless open: Shatter brackets, Foundry-pool defense with the Shatter scaling
  {const S=await game(1,9),G=S.G;G.reforges=4;const d=runChallenge(S);ok(d.bracket.kind==='shatter'&&d.bracket.key==='4','Shatter bracket once Endless is open');const def4=d.g.enemies[0].def;G.reforges=5;const d5=runChallenge(S);ok(d5.g.enemies[0].def>def4,'defense scales with the Shatter count ('+def4+' -> '+d5.g.enemies[0].def+')');}
  // ---- tiers and one-time cumulative claims
  {const S=await game(),G=S.G;const d=runChallenge(S);const T=d.stats.total;S.CHALLENGE.targets.zone[3]=T/0.8;S.CHALLENGE.claims=true; /* Crystal target set so this party lands Gold (80% of Crystal) */
    G.gold=0;G.ore=0;G.dust=0;const g=runChallenge(S);ok(g.tier===2,'tier Gold at 80% of the target (got '+S.CHALLENGE.tiers[g.tier]+')');const rate=S.incomeRate(3,S.ZONES[3].fights-1);const B=[0,1,2,3].map(i=>S.challengeBundle('zone',i,3));
    near(G.gold,Math.round(B[2].gold*rate.gold),1,'Gold first clear pays the cumulative Gold bundle in gold minutes');near(G.ore,Math.round(B[2].ore*rate.ore),1,'and ore minutes');ok(G.dust===B[2].dust,'and dust');ok(g.paid&&g.paid.to===2&&g.paid.from===-1,'claim recorded from none to Gold');
    const g2=G.gold;runChallenge(S);ok(G.gold===g2&&!G.drill.paid,'repeating the same tier pays nothing');
    S.CHALLENGE.targets.zone[3]=T/1.3;const c=runChallenge(S);ok(c.tier===3&&c.overdrive,'Crystal and Overdrive once the target is lower');near(G.gold-g2,Math.round((B[3].gold-B[2].gold)*rate.gold),1,'Crystal pays only the difference from Gold');ok(G.dust===B[3].dust&&S.challengeState().badges['zone:3']===true,'dust tops up to the Crystal bundle; Overdrive leaves a badge');
    S.CHALLENGE.targets.zone[3]=T*10;const w=runChallenge(S);ok(w.tier<0&&!w.paid&&S.challengeState().claimed['zone:3']===3,'a weaker run later pays nothing and cannot reset the claim');
    ok(S.serialize().includes('"challenge"'),'claims, bests and badges are saved');S.CHALLENGE.claims=false;S.CHALLENGE.targets.zone[3]=null;}
  // ---- dust schedule by zone group (cap 9 over the Road), provisional brackets pay nothing, claims survive a save and load
  {const S=await game();const dust=(zi,t)=>S.challengeBundle('zone',t,zi).dust;ok([0,1,2].every(zi=>dust(zi,3)===0)&&[3,4,5].every(zi=>dust(zi,2)===0&&dust(zi,3)===1)&&[6,7,8].every(zi=>dust(zi,2)===1&&dust(zi,3)===2),'zone dust: none before Ironvein, 1 at Crystal for Ironvein-Amberfall, 1 at Gold and 2 at Crystal for Ashen Approach-Foundry');
    let total=0;for(let zi=0;zi<9;zi++)total+=dust(zi,3);ok(total===9,'clearing every zone at Crystal awards 9 dust in total');ok(S.challengeBundle('shatter',1,3).dust===0&&S.challengeBundle('shatter',2,3).dust===1&&S.challengeBundle('shatter',3,3).dust===3,'Shatter bracket dust 0 / 1 / 3 at Silver / Gold / Crystal');}
  {const S=await game(1,9),G=S.G;G.reforges=8;S.CHALLENGE.claims=true;S.CHALLENGE.targets.shatter['8']=1;const d=runChallenge(S);ok(d.tier===3&&d.provisional&&!d.paid&&G.gold===0,'a provisional bracket shows its tier and pays nothing');S.CHALLENGE.claims=false;delete S.CHALLENGE.targets.shatter['8'];}
  {const S=await game(),G=S.G;S.CHALLENGE.claims=true;S.CHALLENGE.targets.zone[3]=1;runChallenge(S);const st=S.challengeState();ok(st.claimed['zone:3']===3&&st.badges['zone:3']===true,'claimed Crystal with a badge');const saved=S.serialize();S.CHALLENGE.claims=false;S.CHALLENGE.targets.zone[3]=null;
    const S2=H.load({seed:2,startMs:JSON.parse(saved).t,save:saved});await S2.ready;const st2=S2.challengeState();ok(st2.claimed['zone:3']===3&&st2.badges['zone:3']===true&&st2.best['zone:3']===st.best['zone:3'],'claims, badges and bests survive a save and load');}
  // ---- offline parity: offlineGains is unchanged; incomeRate agrees with it whenever the multipliers are permanent-only
  {const S=await game(),G=S.G;const old=(hours,eff)=>{const fights=Math.floor(hours*3600/22*eff);const Z=S.ZONES[G.zone],L=Z.endless?S.endlessLv(Z,G.prog[G.zone]):S.roadLv(Z,Z.lv+Math.min(G.prog[G.zone],Z.fights-1)*0.45);const per=1.8;return{fights,gold:Math.round(fights*per*(3+2*L)*Math.pow(1.05,L)*S.goldMult()*S.zoneBonus()),xp:Math.round(fights*per*(6+3*L)*Math.pow(1.04,L)*S.bless('xp')),ore:Math.round(fights*S.ORE_DROP_CHANCE*1.5*(1+Math.floor(L/6))*S.oreScale(L)*S.oreMult()*S.zoneBonus())};};
    let mism=0,cases=0,rateMism=0;const effs=[0.5,0.65];const hoursList=[0.5,2,8,22/3600*7/0.5,22/3600*7/0.5-1e-9,22/3600*7/0.5+1e-9,22/3600*100/0.65,22/3600*100/0.65-1e-9]; /* hours chosen so hours*3600/22*eff sits exactly on, just below and just above an integer fight count */
    for(let zone=0;zone<S.ZONES.length;zone++)for(const prog of [0,10,35,200])for(const rf of [0,3])for(const b of [0,4])for(const om of [null,'swarm'])for(const oath of [null,'poverty']){G.zone=zone;G.prog[zone]=Math.min(prog,S.ZONES[zone].endless?prog:S.ZONES[zone].fights);G.reforges=rf;G.tree.b_gold=b;G.tree.b_ore=b;G.tree.ore=b;G.renown=rf*1e5;G.omens=om?[om]:[];G.oath=oath;
      for(const hours of hoursList)for(const eff of effs){const a=old(hours,eff),n=S.offlineGains(hours,eff);cases++;if(a.fights!==n.fights||a.gold!==n.gold||a.xp!==n.xp||a.ore!==n.ore)mism++;
        if(!om&&!oath){const r=S.incomeRate(zone,G.prog[zone]);const mins=a.fights/r.fightsPerMin;if(Math.abs(mins*r.gold-a.gold)>Math.max(1,a.gold*1e-9)||Math.abs(mins*r.ore-a.ore)>Math.max(1,a.ore*1e-9))rateMism++;}}}
    ok(mism===0,'offline earnings identical to the previous formula in all '+cases+' cases (10 zones, boundary fight counts, omens and oaths included): '+mism+' mismatches');ok(rateMism===0,'incomeRate times farmed minutes equals offline earnings whenever no temporary modifier is active: '+rateMism+' mismatches');
    G.zone=9;G.prog[9]=200;G.reforges=3;G.omens=['swarm'];const withOmen=S.offlineGains(2,0.5).gold;G.omens=[];const without=S.offlineGains(2,0.5).gold;ok(withOmen>without,'offline earnings still include an active Endless omen, as before ('+withOmen+' vs '+without+')');G.zone=3;G.reforges=0;G.omens=[];G.oath=null;}
  // ---- isolation: normal completion, abandonment, reload and an exception all leave the road, its random stream and the records exactly as they were
  {const S=await game(),G=S.G;const snap=()=>JSON.stringify({gold:G.gold,ore:G.ore,dust:G.dust,mode:G.mode,enemies:G.enemies.length,taps:G.stats.taps,board:G.drillBoard||[],ch:G.challenge||null,seed:S.seed(),rng:S.rngCalls()});
    const s0=snap();const d=runChallenge(S);ok(S.seed()===JSON.parse(s0).seed&&S.rngCalls()===JSON.parse(s0).rng,'completion: the road random stream is untouched by a Challenge ('+S.rngCalls()+' draws before and after)');
    const h=G.roster[0];const s1=snap();S.startDrill(h,false);for(let f=0;f<300;f++){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);if(f%10===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}ok(S.abortDrill()===true&&!G.drill.running&&G.drill.aborted,'abandonment: a running practice drill can be stopped');ok(snap()===s1,'abandonment: road, random stream, board and claims unchanged');ok(!G.drillOn&&G.mode==='walk','abandonment: context restored');
    const plain=S.serialize();S.storeSet(plain);const r0=S.rngCalls();S.loadGame();const loadDraws=S.rngCalls()-r0;const afterPlain=snap(); /* a reload itself draws a few random numbers; the reference is a reload with no drill running */
    S.startDrill(h,false);for(let f=0;f<120;f++){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);}const mid=S.serialize();ok(!mid.includes('"drill"')&&!mid.includes('drillOn'),'reload: a save taken mid-drill carries no drill state');
    S.storeSet(mid);const r1=S.rngCalls();ok(S.loadGame()===true&&G.drill===null&&!G.drillOn,'reload: loading drops the running drill');ok(S.rngCalls()-r1===loadDraws,'reload: the load draws the same '+loadDraws+' random numbers with or without a drill');const afterMid=snap();ok(JSON.stringify(Object.assign(JSON.parse(afterMid),{seed:0,rng:0}))===JSON.stringify(Object.assign(JSON.parse(afterPlain),{seed:0,rng:0})),'reload: road and records identical to a reload without a drill');const s1b=snap();
    S.startDrill(h,false);G.drill.g.enemies[0].uid='no-such-sprite';let threw=false;try{S.drillTick(DT);}catch(e){threw=true;}ok(threw&&!G.drillOn&&G.mode==='walk'&&G.enemies.length===0,'exception inside a drill tick: the road context is restored by the swap');S.abortDrill();ok(snap()===s1b,'exception: road, random stream and records unchanged');
    ok(S.abortDrill()===false,'nothing to abort afterwards');}
  // ---- practice drill: only the first three taps per second score
  {const S=await game(),G=S.G;const h=G.roster[0];S.startDrill(h,false);S.setRT(1000);let f=0;while(G.drill.running){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);f++;if(f%6===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));} /* ten taps a second */
    const st=G.drill.stats;ok(st.taps===S.DRILL_SEC*10&&st.tapsExtra>0&&st.taps-st.tapsExtra<=3*S.DRILL_SEC+3,'ten taps a second: '+st.taps+' taps, '+st.tapsExtra+' ignored, at most three a second scored');}
  // ---- incomeRate: the canonical permanent rate; offline earnings use it; temporary modifiers excluded
  {const S=await game(),G=S.G;const r=S.incomeRate(3,10);ok(r.gold>0&&r.ore>0&&r.xp>0&&r.fightsPerMin>0,'rate has gold, ore, XP per minute');
    const g0=S.offlineGains(2,0.5);ok(g0.fights===Math.floor(2*3600/22*0.5),'offline fights unchanged: a fight every 22 s at the efficiency');near(g0.gold,Math.round(g0.fights/r.fightsPerMin*S.incomeRate(G.zone,G.prog[G.zone]).gold),1,'offline gold is the canonical rate times the farmed minutes');
    S.setRT(50);S.noteAttention();const r1=S.incomeRate(3,10);ok(r1.gold===r.gold,'attention does not change the rate');G.omens=['swarm'];G.oath='poverty';const r2=S.incomeRate(3,10);ok(r2.gold===r.gold&&r2.ore===r.ore,'omens and oaths do not change the rate');G.omens=[];G.oath=null;
    G.reforges=2;const r3=S.incomeRate(3,10);near(r3.gold/r.gold,S.permGoldMult()/(1),1e-9,'Shatter multipliers apply exactly once through permGoldMult');}
  if(out.length)console.log(out.join('\n'));console.log((fail?'FAIL  ':'PASS  ')+pass+' passed, '+fail+' failed');process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
