// Training Drill contract tests against PRODUCTION functions: one selected hero, live taps capped at ten scoring taps a second, fixed
// drill luck, bracket defense, temporary road effects excluded, the road untouched by drill inputs; per-bracket five-best records;
// one-time cumulative claims; incomeRate as the permanent reward rate and offlineGains unchanged.
// Run: node tests/contract/drill.test.js   (exit code 1 on any failure)
'use strict';
const H=require('../sim/headless.js');
let pass=0,fail=0;const out=[];
function ok(c,m){if(c)pass++;else{fail++;out.push('FAIL '+m);}}
function near(a,b,eps,m){ok(Math.abs(a-b)<=eps,m+' (got '+a+', want '+b+')');}
async function game(seed=1,zone=3){const S=H.load({seed,startMs:1700000000000});await S.ready;const G=S.G;G.title=false;G.tut=null;G.mult='max';G.screen='vael';for(const def of S.HEROES.slice(0,4)){if(!G.roster.find(h=>h.id===def.id))S.addHero(def,30);}G.active=G.roster.slice(0,4);G.campfireDone=true;for(const h of G.roster){h.lvl=30;S.refreshStats(h);h.hp=h.maxhp;h.charge=0;}for(let i=0;i<zone;i++){G.cleared[i]=true;G.prog[i]=S.ZONES[i].fights;}G.zone=zone;G.mode='walk';G.enc=1e9;G.enemies=[];return S;}
const DT=1/60;
function cur(S){const b=S.drillBrackets();return b[b.length-1];}
function run(S,hero,br,tapsPerSec){const G=S.G;if(!S.startDrill(hero,br||cur(S)))throw new Error('no drill');let f=0;const every=tapsPerSec?Math.round(60/tapsPerSec):0;const rt0=Math.ceil(S.getRT());while(G.drill.running){S.clock.frame();f++;S.setRT(rt0+f/60); /* exact real time: second boundaries land on whole frames */S.update(DT,true);S.drillTick(DT);if(every&&(f+Math.floor(every/2))%every===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}G.sheet=null;G.screen='vael';return G.drill;} /* taps sit between second boundaries, so every second holds exactly tapsPerSec taps */
(async()=>{
  // ---- deterministic, fixed start, exclusions, bracket defense
  {const S=await game(),G=S.G;const h=G.roster.find(x=>x.cls==='mage')||G.roster[0];const a=run(S,h,null,2),b=run(S,h,null,2);ok(a.stats.total>0&&a.stats.total===b.stats.total&&a.stats.crits===b.stats.crits&&a.stats.tap===b.stats.tap,'two attempts with the same hero and taps are identical ('+a.stats.total+')');
    ok(a.stats.total===a.stats.heroDmg+a.stats.tapDmg&&a.stats.heroDmg===a.stats.basic+a.stats.ability&&a.stats.tapDmg===a.stats.tap,'score = hero damage + tap damage, tracked separately');ok(a.stats.taps===2*S.DRILL_SEC&&a.stats.tapsExtra===0,'two taps a second all score');
    ok(a.bracket.kind==='zone'&&a.bracket.zi===3&&a.g.enemies[0].def===S.drillDef(a.bracket)&&a.g.enemies[0].def>0,'current bracket is the highest unlocked zone and the dummy carries its defense');
    const hc=a.hero;ok(hc!==h&&a.g.active[0]===hc,'the hero fights as a fresh copy');S.startDrill(h,cur(S));const fresh=G.drill.hero;ok(fresh.hp===fresh.maxhp&&fresh.charge===0&&fresh.gauge===0&&fresh.readyT===0&&Object.keys(fresh.status).length===0,'fixed start: full HP, no charge, attack timer at zero, no status');S.abortDrill();
    h.charge=100;h.hp=1;h.gauge=90;G.omens=['swarm'];G.oath='silence';S.setRT(S.getRT()+1);S.noteAttention();G.speed=4;G.speedUntil=S.clock.get()+7200000;G.autoCast=false;G.autoUntil=0;const c=run(S,h,null,2);ok(c.stats.total===a.stats.total,'road combat state, omens, an oath, attention, road speed and the Auto-Cast boost do not change the score');G.omens=[];G.oath=null;G.speed=1;G.speedUntil=0;h.hp=h.maxhp;h.charge=0;h.gauge=0;
    const lower=S.drillBrackets()[1];const l=run(S,h,lower,2);ok(l.bracket.zi===1&&l.g.enemies[0].def<a.g.enemies[0].def&&l.stats.total>a.stats.total,'a lower bracket can be selected: less defense, higher score');
    const idle=run(S,h,null,0);ok(idle.stats.tapDmg===0&&idle.stats.heroDmg>0&&idle.stats.ability>0,'without taps the hero still attacks and Auto-Casts on its own');
    ok(G.screen==='vael'&&!G.drillOn&&G.mode==='walk','back on the castle screen with the road context restored');}
  // ---- taps: ten a second score (the production limiter pays 25% from the fourth), the rest animate; taps never touch the road's attention or stats
  {const S=await game(),G=S.G;const h=G.roster[0];const three=run(S,h,null,10),ten=run(S,h,null,20);ok(three.stats.taps===10*S.DRILL_SEC&&three.stats.tapsExtra===0,'ten taps a second all score ('+three.stats.taps+')');
    ok(ten.stats.taps===20*S.DRILL_SEC&&ten.stats.tapsExtra>0&&ten.stats.taps-ten.stats.tapsExtra<=10*S.DRILL_SEC+10,'twenty taps a second: only ten a second score ('+(ten.stats.taps-ten.stats.tapsExtra)+' scored, '+ten.stats.tapsExtra+' extra)');ok(ten.stats.tapDmg===three.stats.tapDmg,'extra taps add no damage (tap damage '+ten.stats.tapDmg+' with twenty a second equals '+three.stats.tapDmg+' with ten)');
    ok(!G.attnUntil&&G.stats.taps===0,'dummy taps never start the road attention bonus or count as road taps');}
  // ---- the road runs underneath and its random stream is never consumed by a drill
  {const S=await game(),G=S.G;const r0=S.rngCalls(),seed0=S.seed();run(S,G.roster[0],null,3);ok(S.rngCalls()===r0&&S.seed()===seed0,'with the road idle, a drill draws nothing from the road generator');
    G.enc=0.01;G.screen='vael';S.startDrill(G.roster[0],cur(S));let sawBattle=false,wins0=G.wins;while(G.drill.running){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);if(G.mode==='battle')sawBattle=true;}ok(sawBattle&&G.wins>=wins0,'the road fought its own battles during the drill');ok(G.drill.stats.total>0&&G.screen==='drill','and the drill scored on its own screen');G.sheet=null;G.screen='vael';}
  // ---- abandonment, reload, exception
  {const S=await game(),G=S.G;const h=G.roster[0];const snap=()=>JSON.stringify({gold:G.gold,ore:G.ore,dust:G.dust,rec:G.drillRec||null,seed:S.seed(),rng:S.rngCalls(),taps:G.stats.taps});const s1=snap();
    S.startDrill(h,cur(S));ok(G.screen==='drill','the drill opens its own screen');for(let f=0;f<300;f++){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);if(f%20===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));}ok(S.abortDrill()===true&&G.drill.aborted&&G.screen==='vael','Stop ends the attempt and returns to the castle');ok(snap()===s1,'nothing recorded, paid or drawn from the road generator');
    const plain=S.serialize();S.storeSet(plain);const r0=S.rngCalls();S.loadGame();const loadDraws=S.rngCalls()-r0;const afterPlain=snap();
    S.startDrill(h,cur(S));for(let f=0;f<120;f++){S.clock.frame();S.setRT(S.getRT()+DT);S.update(DT,true);S.drillTick(DT);}const mid=S.serialize();ok(!mid.includes('"drillOn"')&&!/"drill":\{"hero"/.test(mid),'a save taken mid-drill carries no running drill');S.storeSet(mid);const r1=S.rngCalls();ok(S.loadGame()===true&&G.drill===null&&!G.drillOn&&G.screen!=='drill','a reload drops the running drill and leaves the yard');ok(S.rngCalls()-r1===loadDraws,'the load draws the same '+loadDraws+' numbers with or without a drill');ok(JSON.stringify(Object.assign(JSON.parse(snap()),{seed:0,rng:0}))===JSON.stringify(Object.assign(JSON.parse(afterPlain),{seed:0,rng:0})),'records identical to a reload without a drill');const s2=snap();
    S.startDrill(h,cur(S));G.drill.g.enemies[0].uid='no-such-sprite';let threw=false;try{S.drillTick(DT);}catch(e){threw=true;}ok(threw&&!G.drillOn&&G.mode==='walk'&&G.enemies.length===0,'an exception inside a drill tick leaves the road context restored');S.abortDrill();ok(snap()===s2,'and nothing recorded or drawn');}
  // ---- records per bracket, tiers, one-time cumulative claims, provisional brackets, persistence
  {const S=await game(),G=S.G;const h=G.roster.find(x=>x.cls==='mage')||G.roster[0];const d=run(S,h,null,2);const T=d.stats.total,key=S.drillBracketKey(d.bracket);const rec=S.drillRecords();ok(rec.best[key].length===1&&rec.best[key][0].hero===h.name&&rec.best[key][0].total===T&&rec.best[key][0].heroDmg===d.stats.heroDmg&&rec.best[key][0].tapDmg===d.stats.tapDmg,'the bracket record stores hero, total, hero damage and tap damage');
    for(let i=0;i<6;i++)run(S,G.roster[i%G.roster.length],null,i%3);ok(rec.best[key].length===5&&rec.best[key].every((b,i,a)=>!i||a[i-1].total>=b.total),'five best per bracket, best first');run(S,h,S.drillBrackets()[0],2);ok((rec.best['zone:0']||[]).length===1&&rec.best[key].length===5,'records are kept per bracket');
    S.DRILL.targets.zone[3]=T/0.8;S.DRILL.rewards.zone[3]=false;G.gold=0;G.ore=0;G.dust=0;const off=run(S,h,null,2);ok(off.tier===2&&!off.paid&&!off.rewardsOn&&G.gold===0,'a calibrated bracket with rewards switched off shows its tier and pays nothing');S.DRILL.rewards.zone[3]=true;const g=run(S,h,null,2);ok(g.tier===2,'tier Gold at 80% of the Crystal target (Gold is 75%)');ok(JSON.stringify(S.drillTarget(g.bracket))===JSON.stringify([0.25,0.5,0.75,1].map(p=>S.drillRound(p*T/0.8))),'thresholds are 25 / 50 / 75 / 100% of Crystal, each rounded to end in 0');ok(S.drillTarget(g.bracket).every(v=>v%10===0),'every threshold ends in 0');const rate=S.incomeRate(3,S.ZONES[3].fights-1),B=[0,1,2,3].map(i=>S.drillBundle('zone',i,3));
    near(G.gold,Math.round(B[2].gold*rate.gold),1,'Gold first clear pays the cumulative Gold bundle');near(G.ore,Math.round(B[2].ore*rate.ore),1,'and its ore');ok(G.dust===B[2].dust&&g.paid&&g.paid.from===-1&&g.paid.to===2,'and its dust; claim recorded');
    const g2=G.gold;run(S,h,null,2);ok(G.gold===g2&&!G.drill.paid,'repeating the tier pays nothing');S.DRILL.targets.zone[3]=T/1.3;const c=run(S,h,null,2);ok(c.tier===3&&c.beyond&&rec.badges[key]===true,'Crystal and the Beyond Crystal badge (125% of Crystal) once the target is lower');near(G.gold-g2,Math.round((B[3].gold-B[2].gold)*rate.gold),1,'Crystal pays only the difference');ok(G.dust===B[3].dust,'dust tops up to the Crystal bundle');
    S.DRILL.targets.zone[3]=T*10;const w=run(S,h,null,2);ok(w.tier<0&&!w.paid&&rec.claimed[key]===3,'a weaker attempt later pays nothing and cannot reset the claim');
    const saved=S.serialize();ok(saved.includes('"drill":{"best"'),'records, claims and badges are saved');S.DRILL.targets.zone[3]=null;const S2=H.load({seed:2,startMs:JSON.parse(saved).t,save:saved});await S2.ready;const r2=S2.drillRecords();ok(r2.claimed[key]===3&&r2.badges[key]===true&&r2.best[key].length===5,'and survive a reload');S2.G.cleared[3]=true;S2.doReforge();const r3=S2.drillRecords();ok(Object.keys(r3.claimed).length===0&&r3.best[key].length===5&&r3.badges[key]===true,'a Shatter clears every claimed reward and keeps the records and badges (human 2026-09-16)');}
  {const S=await game(1,9),G=S.G;G.reforges=8;const brs=S.drillBrackets();ok(brs.some(b=>b.kind==='shatter'&&b.key==='8')&&!brs.some(b=>b.kind==='shatter'&&b.key==='9'),'Shatter brackets 3 to the current count once Endless is open');const d=run(S,G.roster[0],cur(S),2);ok(d.tier<0&&d.provisional&&!d.paid&&!d.rewardsOn&&G.gold===0&&S.drillTarget(d.bracket)==null,'Shatter 8 is calibration pending: no target, no tier, no reward');ok(['7','8','9','10'].every(k=>S.DRILL.rewards.shatter[k]===false&&S.DRILL.targets.shatter[k]==null)&&['3','4','5','6'].every(k=>S.DRILL.rewards.shatter[k]===true&&S.DRILL.targets.shatter[k]>0)&&S.DRILL.rewards.zone.every(v=>v===true),'rewards on for every zone and Shatter 3-6, off and untargeted for Shatter 7-10');S.DRILL.targets.shatter['7']=1;S.DRILL.rewards.shatter['7']=true;G.reforges=7;const seven=run(S,G.roster[0],cur(S),2);ok(seven.tier===3&&seven.paid&&G.gold>0,'a bracket pays only when it has both a target and its own switch');delete S.DRILL.targets.shatter['7'];S.DRILL.rewards.shatter['7']=false;G.gold=0;const seven2=run(S,G.roster[0],cur(S),2);ok(!seven2.paid&&seven2.provisional,'and never without them');G.reforges=8;
    const def8=S.drillDef({kind:'shatter',key:'8',n:8});G.reforges=7;const def7=S.drillDef({kind:'shatter',key:'7',n:7});ok(def7<def8,'Shatter-bracket defense follows the road Shatter scaling of the save ('+def7+' at 7 Shatters, '+def8+' at 8)');}
  {const S=await game(1,5),G=S.G;G.highestZoneEver=5;G.everReachedEndless=false;for(let i=0;i<5;i++)G.cleared[i]=true;G.zone=5;let brs=S.drillBrackets();ok(brs.length===6&&brs.every(b=>b.kind==='zone'),'before Endless: zone brackets through the highest zone unlocked this run, no Shatter brackets');G.zone=2;ok(S.drillBrackets().length===6,'standing in an earlier zone does not lock later unlocked zones');G.zone=5;
    G.reforges=3;G.everReachedEndless=true;brs=S.drillBrackets();ok(brs.filter(b=>b.kind==='zone').length===6&&brs.filter(b=>b.kind==='shatter').map(b=>b.key).join()==='3','after Endless: the unlocked zone brackets plus Shatter brackets through the current count');
    G.run={endless:0};S.doReforge();G.sheet=null;G.screen='vael';brs=S.drillBrackets();ok((G.reforges||0)===4&&G.cleared.filter(Boolean).length===0,'a production Shatter resets the road');ok(brs.filter(b=>b.kind==='zone').length===1&&brs.filter(b=>b.kind==='shatter').map(b=>b.key).join()==='3,4','after the Shatter only Greenhollow is drillable until zones are unlocked again, with the new Shatter bracket added (human 2026-09-16)');
    const saved=S.serialize();ok(saved.includes('"highestZoneEver":5')&&saved.includes('"everReachedEndless":true'),'both eligibility fields are saved');const S2=H.load({seed:2,startMs:JSON.parse(saved).t,save:saved});await S2.ready;ok(S2.G.highestZoneEver===5&&S2.G.everReachedEndless===true&&S2.drillBrackets().length===3,'and survive a reload');
    const old=JSON.parse(saved);delete old.highestZoneEver;delete old.everReachedEndless;old.zone=9;old.cleared=[true,true,true,true,true,true,true,true,true,false];old.reforges=3;const S3=H.load({seed:3,startMs:old.t,save:JSON.stringify(old)});await S3.ready;ok(S3.G.highestZoneEver>=8&&S3.G.everReachedEndless===true&&S3.drillBrackets().some(b=>b.kind==='shatter'),'a save from before the fields migrates from its road position and cleared zones');
    const old2=JSON.parse(saved);delete old2.highestZoneEver;delete old2.everReachedEndless;old2.zone=2;old2.cleared=[true,true,false,false,false,false,false,false,false,false];old2.reforges=0;old2.far=[24,30,5,0,0,0,0,0,0,0];const S4=H.load({seed:4,startMs:old2.t,save:JSON.stringify(old2)});await S4.ready;ok(S4.G.highestZoneEver===2&&S4.G.everReachedEndless===false&&S4.drillBrackets().length===3,'a pre-Endless save migrates to zone brackets through its highest zone');}
  // ---- frozen build: purchases, levels and gear earned on the road during the attempt do not change the in-progress score
  {const S=await game(),G=S.G;const h=G.roster.find(x=>x.cls==='mage')||G.roster[0];const base=run(S,h,null,2).stats.total;
    S.startDrill(h,cur(S));let f=0;const rt0=Math.ceil(S.getRT());while(G.drill.running){S.clock.frame();f++;S.setRT(rt0+f/60);S.update(DT,true);S.drillTick(DT);if((f+15)%30===0)S.withDrill(()=>S.tapEnemy(G.enemies[0]));
      if(f===300){G.gold=1e15;G.dust=1e15;for(const id of ['atk','abil','crit','b_dmg','b_ab','tap'])for(let k=0;k<5;k++)S.buyTreeRank(S.TREE.find(n=>n.id===id));h.lvl=99;S.refreshStats(h);h.abLvl=20;G.castle.built=Object.assign({},G.castle.built||{},{watchtower:true,forge:true});}}
    G.sheet=null;G.screen='vael';ok(G.drill.stats.total===base,'tree ranks, levels, ability ranks and structures gained mid-drill leave the score unchanged ('+G.drill.stats.total+' vs '+base+')');ok(S.treeLv('atk')===5&&h.lvl===99,'while the road itself kept the purchases');}
  // ---- dust schedule (cap 9 over the Road; Shatter 1 at Gold, 3 at Crystal)
  {const S=await game();const dust=(zi,t)=>S.drillBundle('zone',t,zi).dust;ok([0,1,2].every(zi=>dust(zi,3)===0)&&[3,4,5].every(zi=>dust(zi,2)===0&&dust(zi,3)===1)&&[6,7,8].every(zi=>dust(zi,2)===1&&dust(zi,3)===2),'zone dust schedule');let total=0;for(let zi=0;zi<9;zi++)total+=dust(zi,3);ok(total===9,'9 dust over the Road at Crystal');ok(S.drillBundle('shatter',1,3).dust===0&&S.drillBundle('shatter',2,3).dust===1&&S.drillBundle('shatter',3,3).dust===3,'Shatter dust 0 / 1 / 3 at Silver / Gold / Crystal');}
  // ---- offline earnings unchanged; incomeRate agrees whenever no temporary modifier is active
  {const S=await game(),G=S.G;const old=(hours,eff)=>{const fights=Math.floor(hours*3600/22*eff);const Z=S.ZONES[G.zone],L=Z.endless?S.endlessLv(Z,G.prog[G.zone]):S.roadLv(Z,Z.lv+Math.min(G.prog[G.zone],Z.fights-1)*0.45);const per=1.8;return{fights,gold:Math.round(fights*per*(3+2*L)*Math.pow(1.05,L)*S.goldMult()*S.zoneBonus()),xp:Math.round(fights*per*(6+3*L)*Math.pow(1.04,L)*S.bless('xp')),ore:Math.round(fights*S.ORE_DROP_CHANCE*1.5*(1+Math.floor(L/6))*S.oreScale(L)*S.oreMult()*S.zoneBonus())};};
    let mism=0,cases=0,rateMism=0;const hoursList=[0.5,2,8,22/3600*7/0.5,22/3600*7/0.5-1e-9,22/3600*7/0.5+1e-9,22/3600*100/0.65,22/3600*100/0.65-1e-9];
    for(let zone=0;zone<S.ZONES.length;zone++)for(const prog of [0,10,35,200])for(const rf of [0,3])for(const b of [0,4])for(const om of [null,'swarm'])for(const oath of [null,'poverty']){G.zone=zone;G.prog[zone]=Math.min(prog,S.ZONES[zone].endless?prog:S.ZONES[zone].fights);G.reforges=rf;G.tree.b_gold=b;G.tree.b_ore=b;G.tree.ore=b;G.renown=rf*1e5;G.omens=om?[om]:[];G.oath=oath;
      for(const hours of hoursList)for(const eff of [0.5,0.65]){const a=old(hours,eff),n=S.offlineGains(hours,eff);cases++;if(a.fights!==n.fights||a.gold!==n.gold||a.xp!==n.xp||a.ore!==n.ore)mism++;if(!om&&!oath){const r=S.incomeRate(zone,G.prog[zone]);const mins=a.fights/r.fightsPerMin;if(Math.abs(mins*r.gold-a.gold)>Math.max(1,a.gold*1e-9)||Math.abs(mins*r.ore-a.ore)>Math.max(1,a.ore*1e-9))rateMism++;}}}
    ok(mism===0,'offline earnings identical to the previous formula in all '+cases+' cases (10 zones, boundary fight counts, omens and oaths): '+mism+' mismatches');ok(rateMism===0,'incomeRate times farmed minutes equals offline earnings without temporary modifiers: '+rateMism+' mismatches');
    G.zone=9;G.prog[9]=200;G.reforges=3;G.omens=['swarm'];const withOmen=S.offlineGains(2,0.5).gold;G.omens=[];const without=S.offlineGains(2,0.5).gold;ok(withOmen>without,'offline earnings still include an active Endless omen, as before');S.setRT(50);S.noteAttention();const r1=S.incomeRate(3,10);G.omens=['swarm'];G.oath='poverty';const r2=S.incomeRate(3,10);ok(r1.gold===r2.gold&&r1.ore===r2.ore,'incomeRate ignores attention, omens and oaths');G.omens=[];G.oath=null;}
  if(out.length)console.log(out.join('\n'));console.log((fail?'FAIL  ':'PASS  ')+pass+' passed, '+fail+' failed');process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
