// Reward-source matrix: every way gold, ore and XP are earned, executed through the PRODUCTION action at rank 0 and again with one bonus rank,
// on identical state and identical RNG; the delta must scale by the multiplier exactly once. Exclusions (salvage, refunds, dev grants) must not scale.
// Run: node tests/contract/sources.test.js   (exit code 1 on any failure)
'use strict';
const H=require('../sim/headless.js');
let pass=0,fail=0;const out=[],covered=[];
function ok(cond,msg){if(cond)pass++;else{fail++;out.push('FAIL '+msg);}}
function ratioOk(dA,dB,mult,msg,tol=0.03){if(dA===0&&dB===0){fail++;out.push('FAIL '+msg+' (no delta at all)');return;}const r=dB/dA;const good=Math.abs(r-mult)<=Math.max(tol*mult,1.5/Math.max(1,Math.abs(dA)));ok(good,msg+' (rank0 '+dA+', rank1 '+dB+', ratio '+r.toFixed(4)+', want '+mult.toFixed(4)+')');if(good)covered.push(msg.split(':')[0]);}
async function game(seed){const S=H.load({seed,startMs:1700000000000});await S.ready;const G=S.G;G.title=false;G.tut=null;G.mult='max';return S;}
function buy(S,id,r){const G=S.G,n=S.TREE.find(x=>x.id===id);const g0=G.gold,d0=G.dust;G.gold=1e15;G.dust=1e15;let k=0;while(k<r&&S.buyTreeRank(n))k++;G.gold=g0;G.dust=d0;if(k!==r)throw new Error('could not buy '+r+' of '+id);for(const h of G.roster){S.refreshStats(h);h.hp=h.maxhp;}}
function heroes(S,lv=40){const G=S.G;for(const def of S.HEROES.slice(0,4)){if(!G.roster.find(h=>h.id===def.id))S.addHero(def,lv);}G.active=G.roster.slice(0,4);G.campfireDone=true;for(const h of G.roster){h.lvl=lv;h.xp=0;S.refreshStats(h);h.maxhp*=50;h.hp=h.maxhp;h.charge=0;}}
function toBattle(S,zone=0){const G=S.G;G.zone=zone;for(let i=0;i<zone;i++){G.cleared[i]=true;G.prog[i]=S.ZONES[i].fights;}G.mode='walk';G.enemies=[];let n=0;while(G.mode!=='battle'&&n<60000){S.setRT(S.getRT()+1/60);S.clock.advance(1000/60);G.tut=null;S.update(1/60,true);n++;}if(G.mode!=='battle')throw new Error('no battle');return G.enemies;}
function finishFight(S){const G=S.G;let n=0;while(G.mode==='battle'&&n<60000){for(const e of G.enemies){if(!e.dead)e.hp=1;}S.setRT(S.getRT()+1/60);S.clock.advance(1000/60);G.tut=null;S.update(1/60,true);n++;}} // every enemy, summons included, dies to the next hit
const xpOf=G=>G.active.reduce((a,h)=>a+h.xp+h.lvl*1e9,0); // level-ups would break a plain xp sum; heroes are far from levelling in these tests
// paired run: same seed and setup, arm B has one rank of node; returns deltas for gold, ore, xp
async function paired(seed,node,setup,action){const res=[];for(const rank of [0,1]){const S=await game(seed);const G=S.G;setup(S,G);if(rank)buy(S,node,1);S.reseed(seed+1000);const g0=G.gold,o0=G.ore,x0=xpOf(G);action(S,G);res.push({gold:G.gold-g0,ore:G.ore-o0,xp:xpOf(G)-x0,S});}return res;}
const GM=1.15,OM_B=1.15,OM_P=1.05,XM=1.15; // one rank: Gilded Road 15%, Deep Veins 15%, Prospecting 5%, Old Wisdom 15%

(async()=>{
// ---- kills (road win path): gold, ore, xp; the win path also grants the checkpoint bonus when prog hits one, which scales identically
for(const [node,key,mult] of [['b_gold','gold',GM],['b_ore','ore',OM_B],['ore','ore',OM_P],['b_xp','xp',XM]]){let found=false;for(let seed=1;seed<=8&&!found;seed++){const [a,b]=await paired(seed,node,(S,G)=>{heroes(S,60);},(S,G)=>{toBattle(S,3);G.prog[3]=1;finishFight(S);});if(a[key]!==0){ratioOk(a[key],b[key],mult,'kills '+key+' via '+node+': scaled once');found=true;}}ok(found,'kills '+key+' via '+node+': a kill that granted '+key+' was found');}
// ---- checkpoint gold (win that reaches a checkpoint): kill + checkpoint gold, both once
{let found=false;for(let seed=1;seed<=6&&!found;seed++){const [a,b]=await paired(seed,'b_gold',(S,G)=>{heroes(S,60);},(S,G)=>{toBattle(S,3);G.prog[3]=S.ZONES[3].fights/3-1;G.far=G.far||[];G.far[3]=0;finishFight(S);});if(a.gold>0){ratioOk(a.gold,b.gold,GM,'checkpoint gold via b_gold: scaled once');found=true;}}ok(found,'checkpoint gold: reached');}
// ---- Endless milestone gold (the milestone boss fight sits at prog 100; its win pays milestone gold once)
{let found=false;for(let seed=1;seed<=6&&!found;seed++){const [a,b]=await paired(seed,'b_gold',(S,G)=>{heroes(S,300);G.reforges=3;for(let i=0;i<9;i++){G.cleared[i]=true;G.prog[i]=S.ZONES[i].fights;}G.prog[9]=100;G.endlessSeen=true;G.endMilestone=0;},(S,G)=>{G.zone=9;G.mode='walk';G.enemies=[];let n=0;while(G.mode!=='battle'&&n<60000){S.setRT(S.getRT()+1/60);S.clock.advance(1000/60);G.tut=null;S.update(1/60,true);n++;}finishFight(S);});if(a.gold>0&&a.S.G.endMilestone>=1){ratioOk(a.gold,b.gold,GM,'Endless milestone gold via b_gold: scaled once');found=true;}}ok(found,'Endless milestone: reached');}
// ---- hordes: fought (resolveHorde(true)) and repelled without a fight (resolveHorde(false) with defense >= strength)
{const [a,b]=await paired(3,'b_gold',(S,G)=>{heroes(S,40);G.castle.lastHordeLv=20;G.hordeFight={lvl:20};G.castle.vil.total=5;},(S,G)=>{S.resolveHorde(true);});ratioOk(a.gold,b.gold,GM,'horde fought gold via b_gold: scaled once');}
{const [a,b]=await paired(3,'b_gold',(S,G)=>{heroes(S,40);G.castle.lastHordeLv=20;G.hordeFight=null;G.castle.b.walls=99;G.castle.vil.total=5;},(S,G)=>{try{S.resolveHorde(false);}catch(e){}});if(a.gold>0)ratioOk(a.gold,b.gold,GM,'horde repelled gold via b_gold: scaled once');else out.push('NOTE horde repelled path granted no gold in this setup (defense check); covered by the fought path');}
// ---- road treasure: gold chest and ore chest
{const [a,b]=await paired(2,'b_gold',(S,G)=>{heroes(S,40);G.zone=2;G.cleared[0]=G.cleared[1]=true;G.prog[2]=5;G.treasure={kind:'gold',y:200,t:1,life:30};},(S,G)=>{S.grabTreasure();});ratioOk(a.gold,b.gold,GM,'treasure gold chest via b_gold: scaled once');}
for(const [node,mult] of [['b_ore',OM_B],['ore',OM_P]]){const [a,b]=await paired(2,node,(S,G)=>{heroes(S,40);G.zone=2;G.cleared[0]=G.cleared[1]=true;G.prog[2]=5;G.treasure={kind:'ore',y:200,t:1,life:30};},(S,G)=>{S.grabTreasure();});ratioOk(a.ore,b.ore,mult,'treasure ore chest via '+node+': scaled once');}
// ---- quests: gold quest, ore quest, quest xp; dust quest must NOT scale with gold nodes
for(const [node,key,mult,qi] of [['b_gold','gold',GM,0],['b_ore','ore',OM_B,1],['ore','ore',OM_P,1],['b_xp','xp',XM,0]]){const [a,b]=await paired(4,node,(S,G)=>{heroes(S,40);G.active=[];},(S,G)=>{const h=G.roster[1];const q={hero:h,q:S.QUESTS[qi],end:0};G.quests=[q];const x0=h.xp;S.collectQuest(q);G._hx=h.xp-x0;});const dA=key==='xp'?a.S.G._hx:a[key],dB=key==='xp'?b.S.G._hx:b[key];ratioOk(dA,dB,mult,'quest '+S_name(qi)+' '+key+' via '+node+': scaled once');}
{const [a,b]=await paired(4,'b_gold',(S,G)=>{heroes(S,40);G.active=[];},(S,G)=>{const h=G.roster[1];const q={hero:h,q:S.QUESTS[3],end:0};G.quests=[q];const d0=G.dust;S.collectQuest(q);G._dd=G.dust-d0;});ok(a.S.G._dd===b.S.G._dd&&a.S.G._dd>0,'quest dust does not scale with Gilded Road ('+a.S.G._dd+' vs '+b.S.G._dd+')');}
function S_name(i){return ['forage','hunt','scout','pilgrimage'][i];}
// ---- quest events: gold, ore and xp events; each event kind must scale by its multiplier once. Same seed picks the same event in both arms.
{const seen={gold:0,ore:0,xp:0};for(let seed=1;seed<=40&&(!seen.gold||!seen.ore||!seen.xp);seed++){for(const [node,key,mult] of [['b_gold','gold',GM],['b_ore','ore',OM_B],['b_xp','xp',XM]]){if(seen[key])continue;const [a,b]=await paired(seed,node,(S,G)=>{heroes(S,40);G.active=[];G.castle.vil.total=0;},(S,G)=>{const h=G.roster[1];const x0=h.xp;S.questEvent(h);G._ex=h.xp-x0;});const dA=key==='xp'?a.S.G._ex:a[key],dB=key==='xp'?b.S.G._ex:b[key];if(dA>0){ratioOk(dA,dB,mult,'quest event '+key+' via '+node+': scaled once');seen[key]=1;}}}
  ok(seen.gold&&seen.xp,'quest events: gold and xp events reached');if(!seen.ore)out.push('NOTE quest event ore needs a ranger or berserker hero; roster here has none, so the ore event is covered by the quest ore reward path only');}
// ---- Vael income: market gold and mine ore per hour
{const [a,b]=await paired(5,'b_gold',(S,G)=>{G.castle.b.market=2;G.castle.vil.market=3;},(S,G)=>{G._v=S.goldPerHour();});ratioOk(a.S.G._v,b.S.G._v,GM,'Vael market gold via b_gold: scaled once');}
for(const [node,mult] of [['b_ore',OM_B],['ore',OM_P]]){const [a,b]=await paired(5,node,(S,G)=>{G.castle.b.mine=2;G.castle.vil.mine=3;},(S,G)=>{G._v=S.orePerHour();});ratioOk(a.S.G._v,b.S.G._v,mult,'Vael mine ore via '+node+': scaled once');}
// ---- Catacombs: floor-win gold and the ore chest door
{const [a,b]=await paired(6,'b_gold',(S,G)=>{heroes(S,40);G.delve={hero:G.roster[0],floor:5,relics:[],bag:{gold:0,ore:0,items:[]},doors:[],keys:0};},(S,G)=>{S.delveWin();G._bg=G.delve?G.delve.bag.gold:0;});ratioOk(a.S.G._bg,b.S.G._bg,GM,'Catacombs floor gold via b_gold: scaled once');}
for(const [node,mult] of [['b_ore',OM_B],['ore',OM_P]]){let found=false;for(let seed=1;seed<=10&&!found;seed++){const [a,b]=await paired(seed,node,(S,G)=>{heroes(S,40);G.delve={hero:G.roster[0],floor:5,relics:[],bag:{gold:0,ore:0,items:[]},doors:['chest'],keys:0,nextFloorAt:0,choose:true};},(S,G)=>{try{S.chooseDoor('chest');}catch(e){}G._bo=G.delve?G.delve.bag.ore:0;});if(a.S.G._bo>0){ratioOk(a.S.G._bo,b.S.G._bo,mult,'Catacombs ore chest via '+node+': scaled once');found=true;}}ok(found,'Catacombs ore chest via '+node+': an ore chest was opened');}
// ---- offline gains (also the time-warp path, which calls the same function with 4h at full efficiency)
for(const [node,key,mult] of [['b_gold','gold',GM],['b_ore','ore',OM_B],['ore','ore',OM_P],['b_xp','xp',XM]]){const [a,b]=await paired(7,node,(S,G)=>{heroes(S,40);G.zone=2;G.cleared[0]=G.cleared[1]=true;G.prog[2]=10;},(S,G)=>{const g=S.offlineGains(8,0.5);G._og={gold:g.gold,ore:g.ore,xp:g.xp};});ratioOk(a.S.G._og[key],b.S.G._og[key],mult,'offline '+key+' via '+node+': scaled once');}
// ---- Pickpocket taps (accumulated over many weighted taps)
{const [a,b]=await paired(8,'b_gold',(S,G)=>{heroes(S,40);buy(S,'tapgold',5);},(S,G)=>{const es=toBattle(S,0);const e=es[0];e.hp=1e12;e.maxhp=1e12;const t0=Math.floor(S.getRT())+1;for(let sec=0;sec<20;sec++)for(let k=0;k<3;k++){S.setRT(t0+sec+k*0.3);S.tapEnemy(e);}});ratioOk(a.gold,b.gold,GM,'Pickpocket tap gold via b_gold: scaled once',0.05);}
// ---- garrison XP (posted hero trains during update)
{const [a,b]=await paired(9,'b_xp',(S,G)=>{heroes(S,40);G.castle.b.walls=2;G.active=[G.roster[0]];G.castle.garrison=[];},(S,G)=>{const h=G.roster[1];S.postHero(h);G.screen='vael';G.mode='walk';G.enc=1e9;G._x0=h.xp;for(let i=0;i<600;i++){S.setRT(S.getRT()+0.1);S.clock.advance(100);S.update(0.1,true);}G._gx=h.xp-G._x0;});ratioOk(a.S.G._gx,b.S.G._gx,XM,'garrison XP via b_xp: scaled once');}
// ---- exclusions: salvage, refund migration, dev grant do not scale
{const [a,b]=await paired(10,'b_ore',(S,G)=>{heroes(S,40);},(S,G)=>{const it=S.makeItem(2,2);it.lvl=8;G.pack.push(it);S.salvageItem(it);});ok(a.ore===b.ore&&a.ore>0,'salvage ore does not scale with Deep Veins ('+a.ore+' vs '+b.ore+')');}
{const [a,b]=await paired(10,'ore',(S,G)=>{heroes(S,40);},(S,G)=>{const it=S.makeItem(2,2);it.lvl=8;G.pack.push(it);S.salvageItem(it);});ok(a.ore===b.ore&&a.ore>0,'salvage ore does not scale with Prospecting');}
{const [a,b]=await paired(10,'b_gold',(S,G)=>{G.tree.crit=25;G.migV=0;},(S,G)=>{S.migrateSave();});ok(a.gold===b.gold&&a.gold>0,'refund migration gold does not scale with Gilded Road ('+a.gold+')');}
{const [a,b]=await paired(10,'b_gold',(S,G)=>{},(S,G)=>{G.gold+=1e12;});ok(a.gold===b.gold&&a.gold===1e12,'dev grant does not scale');}
console.log(out.join('\n'));console.log('covered: '+[...new Set(covered)].join(' | '));console.log((fail?'FAIL':'PASS')+'  '+pass+' passed, '+fail+' failed');process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
